src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Assigned_Map__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned Map</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Owner_Assignment_Map__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>RM</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Owner_Assignment_Map__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact_Owner_Override__c</fullName>
        <label>Contact Owner Override</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Always RM</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Always TSM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Reset_Owner_Assignment__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Reset Owner Assignment</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Contractor</fullName>
        <active>true</active>
        <label>Contractor</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Assigned_To_Last_Deal__c</fullName>
        <label>Assigned To Last Deal</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Called_In_By_Last_Deal__c</fullName>
        <label>Called In By Last Deal</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Manual_Owner_Override__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Manual Owner Override</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Adjuster</fullName>
        <active>true</active>
        <description>All contacts that work in the Insurance Industry. Includes Company Adjusters, Independent Adjusters, Public Adjusters, Supervisors, Managers, Procurement etc.</description>
        <label>Adjuster</label>
    </recordTypes>
    <recordTypes>
        <fullName>Contractor</fullName>
        <active>true</active>
        <label>Contractor</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Owner_Assignment_Map__c.object
<CustomObject>
    <label>Owner Assignment Map</label>
    <nameField>
        <label>Owner Assignment Map</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Owner Assignment Maps</pluralLabel>
    <recordTypes>
        <fullName>RM</fullName>
        <active>true</active>
        <description>Relationship Manager map.</description>
        <label>RM</label>
    </recordTypes>
    <recordTypes>
        <fullName>TSM</fullName>
        <active>true</active>
        <description>Territory Sales Manager map. There can only be one.</description>
        <label>TSM</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Owner_Territory__c.object
<CustomObject>
    <fields>
        <fullName>Owner_Assignment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Owner Assignment</label>
        <referenceTo>Owner_Assignment_Map__c</referenceTo>
        <relationshipName>Owner_Maps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>States__c</fullName>
        <label>States</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DC</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
                <value>
                    <fullName>MN</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
                <value>
                    <fullName>MS</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
                <value>
                    <fullName>NC</fullName>
                </value>
                <value>
                    <fullName>ND</fullName>
                </value>
                <value>
                    <fullName>NE</fullName>
                </value>
                <value>
                    <fullName>NJ</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Territory_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Territory Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Owner_Maps</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Owner Territory</label>
    <nameField>
        <label>Owner Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Owner Territories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TriggerControlSetting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Name hold the trigger Name which we need to control without activating or de-activating the trigger from Object UI.</description>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsAfter__c</fullName>
        <defaultValue>true</defaultValue>
        <label>IsAfter</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsBefore__c</fullName>
        <defaultValue>true</defaultValue>
        <label>IsBefore</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsInsert__c</fullName>
        <defaultValue>true</defaultValue>
        <label>IsInsert</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsUpdate__c</fullName>
        <defaultValue>true</defaultValue>
        <label>IsUpdate</label>
        <type>Checkbox</type>
    </fields>
    <label>Trigger Control Setting</label>
</CustomObject>

src/classes/ContactOwnerUpdateHelper_TC.cls
@isTest
public class ContactOwnerUpdateHelper_TC{
    public static testMethod void InsertRecords(){
    TriggerControlSetting__c tg = new TriggerControlSetting__c(name = 'ContactOwnerUpdate', IsActive__c = true, IsBefore__c = true, IsAfter__c = true, IsInsert__c = true, IsUpdate__c = true);
         insert tg; 
     RecordType rt3 = [SELECT id,Name 
                             FROM RecordType 
                             WHERE SobjectType='Owner_Assignment_Map__c' AND Name='RM'];
     RecordType rt4 = [SELECT id,Name 
                             FROM RecordType 
                             WHERE SobjectType='Owner_Assignment_Map__c' AND Name='Default RM'];
     RecordType rt5 = [SELECT id,Name 
                             FROM RecordType 
                             WHERE SobjectType='Owner_Assignment_Map__c' AND Name='TSM'];    
     Owner_Assignment_Map__c oa = new Owner_Assignment_Map__c();
     oa.Name = 'test';
     oa.recordtypeId = rt3.id;
     insert oa;
     
     Owner_Assignment_Map__c oa4 = new Owner_Assignment_Map__c();
     oa4.Name = 'test';
     oa4.recordtypeId = rt3.id;
     insert oa4;
     
     Owner_Assignment_Map__c oa1 = new Owner_Assignment_Map__c();
     oa1.Name = 'test';
     oa1.recordtypeId = rt4.id;
     insert oa1;
     
     
     Owner_Assignment_Map__c oa2 = new Owner_Assignment_Map__c();
     oa2.Name = 'test';
     oa2.recordtypeId = rt5.id;
     insert oa2;
     
     Owner_Territory__c om =  new Owner_Territory__c();
     om.Name = 'Test Map';
     om.Owner_Assignment__c = oa.id;
     om.Territory_Owner__c = UserInfo.getUserId();
     om.States__c = 'AK;AL';
     insert om;
     
     Owner_Territory__c om1 =  new Owner_Territory__c();
     om1.Name = 'Test Map';
     om1.Owner_Assignment__c = oa1.id;
     om1.Territory_Owner__c = UserInfo.getUserId();
     om1.States__c = 'AK;AL';
     insert om1;
     
     Owner_Territory__c om2 =  new Owner_Territory__c();
     om2.Name = 'Test Map';
     om2.Owner_Assignment__c = oa2.id;
     om2.Territory_Owner__c = UserInfo.getUserId();
     om2.States__c = 'AK;AL';
     insert om2;
     
     RecordType rt = [SELECT id,Name 
                             FROM RecordType 
                             WHERE SobjectType='Account' AND Name='Insurance Companies'];
                             
     RecordType rt2 = [SELECT id,Name 
                             FROM RecordType 
                             WHERE SobjectType='Contact' AND Name='Adjuster'];
                             List<Contact> conlist = new List<Contact>();
                             
     Account ac = new Account();
     ac.Name = 'test Account';
     ac.type = 'Alliance - Contractor';
     ac.Contact_Owner_Override__c = 'Always RM';
     ac.recordtypeId = rt.id;
     ac.Assigned_Map__c = oa.id;
     insert ac;
     
     Account ac2 = new Account();
     ac2.Name = 'test Account';
     ac2.type = 'Alliance - Contractor';
     ac2.Contact_Owner_Override__c = 'Always RM';
     ac2.recordtypeId = rt.id;
     ac2.Assigned_Map__c = oa4.id;
     ac2.Reset_Owner_Assignment__c = true;
     insert ac2;
     
     Contact c5 = new Contact();
     c5.recordtypeId = rt2.id;
     c5.accountId = ac2.id;
     c5.lastname = 'test';
     c5.Manual_Owner_Override__c = false;
     c5.otherstate =  'NJ';
     c5.Called_In_By_Last_Deal__c  = system.today().addDays(-10);
     insert c5;
     
     Account ac1 = new Account();
     ac1.Name = 'test Account';
     ac1.type = 'Alliance - Contractor';
     ac1.recordtypeId = rt.id;
     insert ac1;
     ac1.Reset_Owner_Assignment__c = true;
     update ac1;
     ac1.Assigned_Map__c = oa.id;
     update ac1;
     
     Contact c = new Contact();
     c.recordtypeId = rt2.id;
     c.accountId = ac.id;
     c.lastname = 'test';
     c.Manual_Owner_Override__c = false;
     c.otherstate =  'AK';
     c.Called_In_By_Last_Deal__c  = system.today().addDays(-10);
     insert c;
     
     
     Contact c1 = new Contact();
     c1.recordtypeId = rt2.id;
     c1.lastname = 'test';
     c1.Manual_Owner_Override__c = false;
     c1.Assigned_To_Last_Deal__c = system.today().addDays(-190);
     insert c1;
     
     c.accountid = ac1.id;
     c.Assigned_To_Last_Deal__c = system.today().addDays(-190);
     ac.Contact_Owner_Override__c = '';
     c.Called_In_By_Last_Deal__c  = null;
     update c;
     
     c1.Called_In_By_Last_Deal__c  = system.today().addDays(-10);
     c1.Assigned_To_Last_Deal__c = null;
     update c1;
     
     Contact c3 = new Contact();
     c3.recordtypeId = rt2.id;
     c3.accountId = ac.id;
     c3.lastname = 'test';
     c3.Manual_Owner_Override__c = false;
     c3.otherstate =  'AK';
     c3.Called_In_By_Last_Deal__c  = system.today().addDays(-10);
     insert c3;
     
      
        Test.startTest();
            ContactOwnerUpdateBatch batchRef = new ContactOwnerUpdateBatch();
            Database.executeBatch(batchRef);
            ContactOwnerSchedule sh1 = new ContactOwnerSchedule();
            String sch = '0 0 23 * * ?'; system.schedule('Test Territory Check', sch, sh1);
        Test.stopTest();
    }
}