src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <description>The email address of the landlord.</description>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>RecordtypeName__c</fullName>
        <formula>RecordType.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>RecordtypeName</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Agent</fullName>
                </value>
                <value>
                    <fullName>Catastrophe</fullName>
                </value>
                <value>
                    <fullName>Company</fullName>
                </value>
                <value>
                    <fullName>Contractor</fullName>
                </value>
                <value>
                    <fullName>FEMA</fullName>
                </value>
                <value>
                    <fullName>Independent</fullName>
                </value>
                <value>
                    <fullName>Landlord</fullName>
                </value>
                <value>
                    <fullName>Lawyer</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Policyholder</fullName>
                </value>
                <value>
                    <fullName>Procurement</fullName>
                </value>
                <value>
                    <fullName>Public</fullName>
                </value>
                <value>
                    <fullName>Restoration</fullName>
                </value>
                <value>
                    <fullName>Supervisor</fullName>
                </value>
                <value>
                    <fullName>TPA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Costs__c.object
<CustomObject>
    <fields>
        <fullName>RecordTypeName__c</fullName>
        <formula>RecordType.Name</formula>
        <label>RecordTypeName</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Searches__c</fullName>
        <label>Search</label>
        <referenceTo>Searches__c</referenceTo>
        <relationshipLabel>Costs</relationshipLabel>
        <relationshipName>Costs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Costs</label>
    <nameField>
        <displayFormat>Cost-{0000000}</displayFormat>
        <label>Cost Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Costs</pluralLabel>
    <recordTypes>
        <fullName>Cost</fullName>
        <active>true</active>
        <label>Cost</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Placement__c.object
<CustomObject>
    <description>Holds information about a housing placement, when the Opportunity stage is set to Moved-In, and a policy holder moves into the temporarry housing.  Besides the detail about the duration of the placement, this object is related to Cases to track any issues related to the placement.</description>
    <fields>
        <fullName>Approved_Through_Date__c</fullName>
        <label>Approved Through Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Move_In_Date__c</fullName>
        <description>Houston populates this based on the quote start date.</description>
        <label>Move In Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Claim Lookup</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Placements</relationshipLabel>
        <relationshipName>Placements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Prorate_Total__c</fullName>
        <formula>Prorate__c +  Prorate_Adjustment__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Prorate Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Placement</label>
    <nameField>
        <label>Placement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Placements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Searches__c.object
<CustomObject>
    <description>Used track the property and hotel searches conducted as part of the Sevice Request</description>
    <fields>
        <fullName>Bathrooms__c</fullName>
        <label>Bathrooms</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>0</fullName>
                </value>
                <value>
                    <fullName>.5</fullName>
                </value>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>1.5</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>2.5</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>3.5</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>4.5</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>5.5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>6.5</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>7.5</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>8.5</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Bedrooms__c</fullName>
        <label>Bedrooms</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>0</fullName>
                </value>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Days_Notice_Required__c</fullName>
        <label>Days Notice Required</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Extension_Increment_Days__c</fullName>
        <label>Extension Increment Days</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Landlord__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Landlord</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Landlord</value>
            </filterItems>
            <filterItems>
                <field>Contact.Status__c</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Searches</relationshipLabel>
        <relationshipName>Searches</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NTV_Send_Via__c</fullName>
        <label>NTV Send Via</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Fax</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Certified Mail</fullName>
                </value>
                <value>
                    <fullName>Insured</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Placement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Placement</label>
        <referenceTo>Placement__c</referenceTo>
        <relationshipName>Searches</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Request__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Service Request</label>
        <referenceTo>ServiceRequest__c</referenceTo>
        <relationshipName>Searches</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>THC_Comments__c</fullName>
        <label>THC Comments</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Temporary_Address_With_Unit__c</fullName>
        <formula>Street_Addr1__c&amp;IF( LEN(Unit__c) &gt; 0 , &quot; &quot;, &quot;&quot;) &amp; Unit__c&amp;IF( LEN(Street_Addr2__c) &gt; 0 , &quot; &quot;, &quot;&quot;) &amp; Street_Addr2__c &amp; &quot;,&quot; &amp; City__c &amp; &quot;, &quot; &amp; State__c &amp; &quot; &quot; &amp; Zip__c &amp; &quot;, &quot; &amp; Country__c</formula>
        <label>Temporary Address With Unit</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unit__c</fullName>
        <label>Unit #</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <label>Search</label>
    <nameField>
        <displayFormat>SR-{000000}</displayFormat>
        <label>Search Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Searches</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/ServiceRequest__c.object
<CustomObject>
    <description>Holds the different services that a request can include, such as: Hotel Stays, Housing requests, Furniture requests, Fair Rental Value, etc.</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Claim</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Service Requests</relationshipLabel>
        <relationshipName>Service_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Service Request</label>
    <nameField>
        <displayFormat>SR#-{000000}</displayFormat>
        <label>Service Request</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/RESTGetTHCInformation.cls
@RestResource(urlMapping='/Searches/GetTHCInformation/*')
global with sharing class RESTGetTHCInformation 
{
	@HttpGet
	global static string doGetTHCInformation(RestRequest req)
	{
		boolean hasCosts = true;
		string searchId = req.RequestURI.substring(req.requestURI.lastIndexOf('/')+1);
		system.debug(searchId);
		system.debug(req.RequestURI.substring(req.requestURI.lastIndexOf('/')+1));
		Searches__c search = [select Service_Request__r.Opportunity__r.Policyholder__r.Name,Temporary_Address_With_Unit__c,Service_Request__r.Opportunity__r.Name,
		    				  Days_Notice_Required__c,Landlord__r.Name,Extension_Increment_Days__c,Bedrooms__c,Bathrooms__c,Placement__r.Prorate_Total__c,
		 					  THC_Comments__c,Landlord__r.Account.Name,Landlord__r.Account.BillingStreet,Landlord__r.Account.BillingCity,Landlord__r.Account.BillingState,
		 					  Landlord__r.Account.BillingPostalCode,Landlord__r.Account.BillingCountry,Landlord__r.Account.Fax,Landlord__r.Account.Email__c,Placement__r.Move_In_Date__c,
		 					  Placement__r.Approved_Through_Date__c,NTV_Send_Via__c,Unit__c from Searches__c where Id =: searchId ];
        
        List<Costs__c> costs = new List<Costs__c>();
        
        costs = [select RecordTypeName__c, Type__c, Type_Description__c, Amount__c, Prorate_Type__c from Costs__c 
        		 where Payable_Party_is_Landlord__c = true and searches__r.Id =: searchId];
               
        if (search.Service_Request__r.Opportunity__r.Name == null){search.Service_Request__r.Opportunity__r.Name = '';}
        if (search.THC_Comments__c == null){search.THC_Comments__c = '';}
        if (search.Landlord__r.Account.Name == null){search.Landlord__r.Account.Name = '';}
        if (search.Landlord__r.Account.BillingStreet == null){search.Landlord__r.Account.BillingStreet = '';}
        if (search.Landlord__r.Account.BillingCity == null){search.Landlord__r.Account.BillingCity = '';}
        if (search.Landlord__r.Account.BillingState == null){search.Landlord__r.Account.BillingState = '';}
        if (search.Landlord__r.Account.BillingPostalCode == null){search.Landlord__r.Account.BillingPostalCode = '';}
        if (search.Landlord__r.Account.BillingCountry == null){search.Landlord__r.Account.BillingCountry = '';}
        if (search.Landlord__r.Account.Email__c == null){search.Landlord__r.Account.Email__c = '';}
        if (search.Landlord__r.Account.Fax == null){search.Landlord__r.Account.Fax = '';}
        
        JSONGenerator gen = JSON.createGenerator(true);
        
        gen.writeStartObject();
        
        gen.writeStringField('PolicyholderName', search.Service_Request__r.Opportunity__r.Policyholder__r.Name);
        gen.writeStringField('TemporaryAddress', search.Temporary_Address_With_Unit__c);
        gen.writeStringField('ClaimName', search.Service_Request__r.Opportunity__r.Name);
        gen.writeNumberField('DaysNoticeRequired', search.Days_Notice_Required__c);
        gen.writeStringField('LandlordName', search.Landlord__r.Name);
        gen.writeNumberField('ExtensionIncrementDays', search.Extension_Increment_Days__c);
        gen.writeStringField('Bedrooms', search.Bedrooms__c);
        gen.writeStringField('Bathrooms', search.Bathrooms__c);
        gen.writeNumberField('ProrateTotal', search.Placement__r.Prorate_Total__c);
        gen.writeDateField('MoveInDate', search.Placement__r.Move_In_Date__c);
        gen.writeDateField('ApprovedThroughDate', search.Placement__r.Approved_Through_Date__c);
        gen.writeStringField('NTVSendVia', search.NTV_Send_Via__c);
       	gen.writeStringField('THCComments', search.THC_Comments__c);
        gen.writeStringField('LandlordAccountName', search.Landlord__r.Account.Name);
        gen.writeStringField('LandlordAccountMailingSteet', search.Landlord__r.Account.BillingStreet);
        gen.writeStringField('LandlordAccountMailingCity', search.Landlord__r.Account.BillingCity);
        gen.writeStringField('LandlordAccountMailingState', search.Landlord__r.Account.BillingState);
        gen.writeStringField('LandlordAccountMailingPostalCode', search.Landlord__r.Account.BillingPostalCode);
        gen.writeStringField('LandlordAccountMailingCountry', search.Landlord__r.Account.BillingCountry);
        gen.writeStringField('LandlordAccountEmail', search.Landlord__r.Account.Email__c);
        gen.writeStringField('LandlordAccountFax', search.Landlord__r.Account.Fax);
                              
       	gen.writeObjectField('cost', costs);
                         
        gen.writeEndObject();
        
        String JSONString = gen.getAsString();
        
        // modify JSON string for mulligan 
        JSONString = JSONString.replaceAll('\n','');
              	
      	system.debug(JSONString);
      	                       
        return JSONString;
	}
}