src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contact_First_Name__c</fullName>
        <description>When the contact is created this is the value that will go into the first name field</description>
        <label>Contact First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Last_Name__c</fullName>
        <description>When the contact is created this is the value that will go into the last name field</description>
        <label>Contact Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Active - potential of doing business
Inactive - not able to do business
No Longer with Company</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>No Longer with Company</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Adjuster</fullName>
        <active>true</active>
        <description>All contacts that work in the Insurance Industry. Includes Company Adjusters, Independent Adjusters, Public Adjusters, Supervisors, Managers, Procurement etc.</description>
        <label>Adjuster</label>
    </recordTypes>
    <recordTypes>
        <fullName>Policyholder</fullName>
        <active>true</active>
        <description>Contacts that are a Policyholder</description>
        <label>Policyholder</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Hotel_Room__c.object
<CustomObject>
    <description>Holds the information related to a Hotel Booking.</description>
    <fields>
        <fullName>Policyholder__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Policyholder</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Hotel Rooms</relationshipLabel>
        <relationshipName>Hotel_Rooms</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Hotel Room</label>
    <nameField>
        <displayFormat>Room-{00000}</displayFormat>
        <label>Hotel Room</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hotel Rooms</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Damaged_Property_Address__c</fullName>
        <label>Damaged Property Address</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Damaged_Property_City__c</fullName>
        <label>Damaged Property City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Damaged_Property_Country__c</fullName>
        <label>Damaged Property Country</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Damaged_Property_State__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>USA</fullName>
                </value>
                <value>
                    <fullName>CAN</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Damaged_Property_State__c</fullName>
        <label>Damaged Property State/Province</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DC</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
                <value>
                    <fullName>MN</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
                <value>
                    <fullName>MS</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
                <value>
                    <fullName>NC</fullName>
                </value>
                <value>
                    <fullName>ND</fullName>
                </value>
                <value>
                    <fullName>NE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Damaged_Property_Type__c</fullName>
        <label>Damaged Property Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Apartment</fullName>
                </value>
                <value>
                    <fullName>Condo</fullName>
                </value>
                <value>
                    <fullName>House</fullName>
                </value>
                <value>
                    <fullName>Mobile Home</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Townhouse</fullName>
                </value>
                <value>
                    <fullName>Travel Trailer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Damaged_Property_Zip__c</fullName>
        <label>Damaged Property Zip/Postal Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Initial_Service_Request__c</fullName>
        <label>Initial Service Request</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Housing</fullName>
                </value>
                <value>
                    <fullName>Hotel</fullName>
                </value>
                <value>
                    <fullName>FRV</fullName>
                </value>
                <value>
                    <fullName>Furniture Only</fullName>
                </value>
                <value>
                    <fullName>Unfurnished</fullName>
                </value>
                <value>
                    <fullName>Trailer-Mobile Home</fullName>
                </value>
                <value>
                    <fullName>Commercial</fullName>
                </value>
                <value>
                    <fullName>Finders Fees</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Policyholder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Policyholder</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Policyholder, Adjuster Policyholder Record Type</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Claims</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type_of_Loss__c</fullName>
        <label>Type of Loss</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CAT</fullName>
                </value>
                <value>
                    <fullName>Fire</fullName>
                </value>
                <value>
                    <fullName>Mold</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Tornado</fullName>
                </value>
                <value>
                    <fullName>Water</fullName>
                </value>
                <value>
                    <fullName>Wind</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Claim</fullName>
        <active>true</active>
        <businessProcess>Standard Request</businessProcess>
        <label>Claim</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Placement__c.object
<CustomObject>
    <description>Holds information about a housing placement, when the Opportunity stage is set to Moved-In, and a policy holder moves into the temporarry housing.  Besides the detail about the duration of the placement, this object is related to Cases to track any issues related to the placement.</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Checked-In</fullName>
                </value>
                <value>
                    <fullName>Checked-Out</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Moved-In</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Moved-Out</fullName>
                </value>
                <value>
                    <fullName>Pending Confirmation</fullName>
                </value>
                <value>
                    <fullName>Quote</fullName>
                </value>
                <value>
                    <fullName>Searching</fullName>
                </value>
                <value>
                    <fullName>Pending Check-In</fullName>
                </value>
                <value>
                    <fullName>Lost Opportunity</fullName>
                </value>
                <value>
                    <fullName>Viewing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Placement</label>
    <nameField>
        <label>Placement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Placements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ServiceRequest__c.object
<CustomObject>
    <description>Holds the different services that a request can include, such as: Hotel Stays, Housing requests, Furniture requests, Fair Rental Value, etc.</description>
    <fields>
        <fullName>Damaged_Property_Address__c</fullName>
        <formula>Opportunity__r.Damaged_Property_Address__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Damaged Property Address</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Damaged_Property_City__c</fullName>
        <formula>Opportunity__r.Damaged_Property_City__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Damaged Property City</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Damaged_Property_State__c</fullName>
        <formula>Text(Opportunity__r.Damaged_Property_State__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Damaged Property State</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Damaged_Property_Type__c</fullName>
        <formula>CASE( Opportunity__r.Damaged_Property_Type__c, &quot;House&quot; , &quot;House&quot; , &quot;Mobile Home&quot; , &quot;Mobile Home&quot; , &quot;Travel Trailer&quot; , &quot;Travel Trailer&quot; , &quot;Condo&quot; , &quot;Condo&quot; , &quot;Apartment&quot; , &quot;Apartment&quot; , &quot;Townhouse&quot; , &quot;Townhouse&quot; , &quot;Other&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Damaged Property Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Damaged_Property_Zip__c</fullName>
        <formula>Opportunity__r.Damaged_Property_Zip__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Damaged Property Zip</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Request</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Searching</fullName>
                </value>
                <value>
                    <fullName>Pending Confirmation</fullName>
                </value>
                <value>
                    <fullName>Moved-In/Closed</fullName>
                </value>
                <value>
                    <fullName>Finders Fee</fullName>
                </value>
                <value>
                    <fullName>Hold</fullName>
                </value>
                <value>
                    <fullName>Checked-In/Closed</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Lost Opportunity</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type_of_Loss__c</fullName>
        <formula>CASE (Opportunity__r.Type_of_Loss__c, &apos;Mold&apos;, &apos;Mold&apos;, &apos;Fire&apos;, &apos;Fire&apos;, &apos;Tornado&apos;, &apos;Tornado&apos;, &apos;Water&apos;, &apos;Water&apos;,&apos;Wind&apos;, &apos;Wind&apos;, &apos;CAT&apos; , &apos;CAT&apos; , &apos;Other&apos;)</formula>
        <label>Type of Loss</label>
        <type>Text</type>
    </fields>
    <label>Service Request</label>
    <nameField>
        <displayFormat>SR#-{000000}</displayFormat>
        <label>Service Request</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Requests</pluralLabel>
    <recordTypes>
        <fullName>Hotel</fullName>
        <active>true</active>
        <description>For Hotel requests</description>
        <label>Hotel</label>
    </recordTypes>
    <recordTypes>
        <fullName>Housing</fullName>
        <active>true</active>
        <description>For Housing requests</description>
        <label>Housing</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PreCheckoutTaskCreatorTest.cls
@isTest
private class PreCheckoutTaskCreatorTest 
{
  @testSetup static void setupTestData()
    {

        DateTime currentDate = DateTime.newInstance(System.today(), Time.newInstance(12,0,0,0));
        DateTime min72hrDate = DateTime.newInstance(System.today(), Time.newInstance(12,0,0,0));
        DateTime max72hrDate = DateTime.newInstance(System.today(), Time.newInstance(12,0,0,0));
        DateTime min24hrDate = DateTime.newInstance(System.today(), Time.newInstance(12,0,0,0));
        DateTime max24hrDate = DateTime.newInstance(System.today(), Time.newInstance(12,0,0,0));
        DateTime minShortTermDate = DateTime.newInstance(System.today(), Time.newInstance(12,0,0,0));

        // Calculate min and max business days out from current date
        min72hrDate = min72hrDate.AddDays(3);
        max72hrDate = max72hrDate.AddDays(3);
        min24hrDate = min24hrDate.AddDays(1);
        max24hrDate = max24hrDate.AddDays(1);
        minShortTermDate = minShortTermDate.AddDays(-2);
    
        
        if (currentDate.format('u') == '1' || currentDate.format('u') == '2')
        {
            minShortTermDate = minShortTermDate.AddDays(-2);
        }
        else
        {
            if (currentDate.format('u') == '3')
            {
                max72hrDate = max72hrDate.AddDays(2);
            }
            else
            {
                if (currentDate.format('u') == '4' || currentDate.format('u') == '5')
                {
                    min72hrDate = min72hrDate.AddDays(2);
                    max72hrDate = max72hrDate.AddDays(2);

                    if (currentDate.format('u') == '5')
                    {
                        max24hrDate = max24hrDate.AddDays(2);
                    }
                }               
            }
        }

    Account account1 = new Account
                (
                    RecordTypeId = recordTypeHelper.landlordAccountRT(),
                    name='testAccountx',
                    Active__c= true,
                    BillingState='CT',
                    BillingStreet='134 Laurel',
                    BillingCity='Mineola',
                    BillingPostalCode='11501',
                    BillingCountry='USA',
                    ShippingState = 'CT',
                    ShippingCountry = 'USA',
                    ShippingPostalCode = '11501',
                    ShippingCity = 'Mineola',
                    ShippingStreet = '134 Laurel',
                    Contact_First_Name__c = 'Test',
                    Contact_Last_Name__c = 'Guy',
                    Fax = '6022345675'
                );
        insert account1;

        Account account2 = new Account
                (
                    RecordTypeId = recordTypeHelper.insuranceCompanyAccountRT(),
                    name='Safeco Insurance Company Headquarters',
                    Active__c= true,
                    BillingState='CT',
                    BillingStreet='134 Laurel',
                    BillingCity='Mineola',
                    BillingPostalCode='11501',
                    BillingCountry='USA',
                    ShippingState = 'CT',
                    ShippingCountry = 'USA',
                    ShippingPostalCode = '11501',
                    ShippingCity = 'Mineola',
                    ShippingStreet = '134 Laurel',
                    Contact_First_Name__c = 'Test',
                    Contact_Last_Name__c = 'Guy',
                    Fax = '6022345675'
                );
        insert account2;

         Account account3 = new Account
                (
                    RecordTypeId = recordTypeHelper.insuranceCompanyAccountRT(),
                    name='Safeco Insurance Company',
                    ParentID = account2.Id,
                    Active__c= true,
                    BillingState='CT',
                    BillingStreet='134 Laurel',
                    BillingCity='Mineola',
                    BillingPostalCode='11501',
                    BillingCountry='USA',
                    ShippingState = 'CT',
                    ShippingCountry = 'USA',
                    ShippingPostalCode = '11501',
                    ShippingCity = 'Mineola',
                    ShippingStreet = '134 Laurel',
                    Contact_First_Name__c = 'Test',
                    Contact_Last_Name__c = 'Guy',
                    Fax = '6022345675'
                );
        insert account3;
    
    
    Contact contactLL = [select Id, Name, FirstName, LastName, AccountId, RecordTypeId
                                                        from Contact 
                                                        where RecordTypeId = :recordTypeHelper.landlordContactRT()
                                                        and AccountId = :account1.Id];

      
        Contact contactPH = new Contact
            (
                RecordTypeId = recordTypeHelper.policyholderContactRT(),
                AccountID = account1.Id,
                LastName='TestPH',
                Status__c='Active',
                MailingCountry='USA',
                MailingState='CT',
                MailingStreet='134 Laurel',
                MailingCity='Mineola',
                MailingPostalCode='11501');
        
        insert contactPH;

        Contact contactADJ = new Contact
            (
                RecordTypeId = recordTypeHelper.adjusterContactRT(),
                AccountId = account3.Id,
                LastName='TestADJ',
                Status__c='Active',
                MailingCountry='USA',
                MailingState='CT',
                MailingStreet='134 Laurel',
                MailingCity='Mineola',
                MailingPostalCode='11501');
        
        insert contactADJ;

        // Insert Users
        Profile p = [SELECT Id FROM Profile WHERE Name='Operations User']; 
        User user1 = new User
                (   
                    Alias = 'opsusr',
                    Email='operationsuser@testorg.com', 
                    EmailEncodingKey='UTF-8', 
                    LastName='Testing', 
                    LanguageLocaleKey='en_US',
                    LocaleSidKey='en_US', 
                    ProfileId = p.Id, 
                    TimeZoneSidKey='America/Los_Angeles', 
                    UserName='operationsuser@crstemphousing.com');
        insert user1; 
  
        // Insert Claim 
        Opportunity opportunity = new Opportunity
                (
                    StageName = 'Submitted',
                    Name = 'TestClaim',
                    policyholder__c = contactPH.Id,
                    Initial_Service_Request__c='Housing',   
                    CloseDate = Date.newInstance(2010,12,10),
                    Type_of_Loss__c = 'Mold',
                    Damaged_Property_Type__c = 'Apartment',
                    Damaged_Property_Address__c = '123 Big Test Lane',
                    Damaged_Property_City__c = 'Mineola',
                    Damaged_Property_State__c = 'CT',
                    Damaged_Property_Zip__c = '11501',
                    Damaged_Property_Country__c = 'USA',
                    Regional_Manager__c = user1.Id,
                    Customer_Care_Specialist__c = user1.Id,
                    Hotel_Customer_Care_Specialist__c = user1.Id);
        insert opportunity;
        
      
        // Insert ServiceRequest 
               
        ServiceRequest__c serviceRequest = new ServiceRequest__c
            (
                  RecordTypeId = recordTypeHelper.hotelServiceRequestRT(),
            Opportunity__c = opportunity.Id,
            Status__c = 'Searching',
            THC_Signed__c = Date.newInstance(2009,10,09),
            THA_Signed__c = Date.newInstance(2009,10,09));
        insert serviceRequest;
               
       
        // Insert placement
               
        Placement__c placement = new Placement__c(
                                        RecordTypeId = recordTypeHelper.hotelPlacementRT(),
                                        ServiceRequest__c = serviceRequest.Id,
                                        Opportunity__c = opportunity.Id,
                                        Status__c = 'Moved-In',
                                        Name = 'testPlacementHotel');                                        
        insert placement;
    
    // Insert Hotel Room
           
      Hotel_Room__c hr1 = new Hotel_Room__c
      (
        Room_Type__c = 'Standard Double',
        Kitchen_Features__c = 'Kitchenette',
        Confirmation__c = '123',
        Check_In__c = Date.Today() - 10,
        Estimated_Check_Out_Date__c = max72hrDate.date(),
        Hotel_Nightly_Rate__c = 100.00,
        Itemized_Tax__c = 10,
        Placement__c = placement.Id,
        Policyholder__c = contactPH.Id);
        
        insert hr1;
       

        Hotel_Room__c hr2 = new Hotel_Room__c
        (
        Room_Type__c = 'Standard Double',
        Kitchen_Features__c = 'Kitchenette',
        Confirmation__c = '123',
        Check_In__c = min24hrDate.date() - 1,
        Estimated_Check_Out_Date__c = min24hrDate.date(),
        Hotel_Nightly_Rate__c = 100.00,
        Itemized_Tax__c = 10,
        Placement__c = placement.Id,
        Policyholder__c = contactPH.Id);
        
        insert hr2;

    }

    @isTest static void PreCheckoutTaskCreatorTest1() 
    {
       Test.StartTest();
       SchedulableContext sc;
       PreCheckoutTaskCreatorScheduler pcTCS =  new PreCheckoutTaskCreatorScheduler();
       pcTCS.execute(sc);
       Test.StopTest();

       AggregateResult tasks72HourPH = [Select COUNT(Id)recCount from Task where type = '72 Hour Policyholder Follow Up'];
       system.assertEquals(1,tasks72HourPH.get('recCount'));

       AggregateResult tasks24Hour = [Select COUNT(Id)recCount from Task where type = '24 Hour Follow Up'];
       system.assertEquals(1,tasks24Hour.get('recCount'));
       
    }

    @isTest static void PreCheckoutTaskCreatorTest2() 
    {
       Contact adj = [select id from Contact where LastName='TestADJ'];
       Opportunity opp = [select id from Opportunity where Damaged_Property_Address__c = '123 Big Test Lane'];
       opp.Adjuster__c = adj.Id;
       update opp;
      
       Test.StartTest();
       SchedulableContext sc;
       PreCheckoutTaskCreatorScheduler pcTCS =  new PreCheckoutTaskCreatorScheduler();
       pcTCS.execute(sc);
       Test.StopTest();

       AggregateResult tasks72HourADJ = [Select COUNT(Id)recCount from Task where type = '72 Hour Adjuster Follow Up'];
       system.assertEquals(1,tasks72HourADJ.get('recCount'));
       
    }
}