src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Assigned_Map__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned Map</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Owner_Assignment_Map__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>RM</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Owner_Assignment_Map__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact_Owner_Override__c</fullName>
        <label>Contact Owner Override</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Always RM</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Always TSM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Reset_Owner_Assignment__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Reset Owner Assignment</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Manual_Owner_Override__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Manual Owner Override</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sales_Status__c</fullName>
        <formula>IF( OR( TODAY() - Called_In_By_Last_Deal__c &lt;= 180  , TODAY() - Assigned_To_Last_Deal__c &lt;= 180), &apos;Actual Customer&apos;, &apos;Target Customer&apos;)</formula>
        <label>Sales Status</label>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Adjuster</fullName>
        <active>true</active>
        <description>All contacts that work in the Insurance Industry. Includes Company Adjusters, Independent Adjusters, Public Adjusters, Supervisors, Managers, Procurement etc.</description>
        <label>Adjuster</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Owner_Assignment_Map__c.object
<CustomObject>
    <fields>
        <fullName>Unassigned_State_Fallback_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Unassigned State Fallback Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Owner_Assignment_Maps</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Owner Assignment Map</label>
    <nameField>
        <label>Owner Assignment Map</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Owner Assignment Maps</pluralLabel>
    <recordTypes>
        <fullName>RM</fullName>
        <active>true</active>
        <description>Relationship Manager map.</description>
        <label>RM</label>
    </recordTypes>
    <recordTypes>
        <fullName>TSM</fullName>
        <active>true</active>
        <description>Territory Sales Manager map. There can only be one.</description>
        <label>TSM</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Owner_Territory__c.object
<CustomObject>
    <fields>
        <fullName>Owner_Assignment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Owner Assignment</label>
        <referenceTo>Owner_Assignment_Map__c</referenceTo>
        <relationshipName>Owner_Maps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>States__c</fullName>
        <label>States</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DC</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
                <value>
                    <fullName>MN</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
                <value>
                    <fullName>MS</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
                <value>
                    <fullName>NC</fullName>
                </value>
                <value>
                    <fullName>ND</fullName>
                </value>
                <value>
                    <fullName>NE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Territory_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Territory Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Owner_Maps</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Owner Territory</label>
    <nameField>
        <label>Owner Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Owner Territories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ContactOwnerUpdateBatch.cls
/*************************************************************************************************************
Created by: Apostletech team
Purpose: When any changes made to the Owner Map states, RM Owner and TSM Owner Reset Owner Assignment   field in Account object is updated then we need to run the batch class to update the contact owner assignment
Class calling from a scheduledBatchContactOwnerUpdate schedule class to update the owner.
*************************************************************************************************************/
global class ContactOwnerUpdateBatch implements Database.Batchable<sObject> {    
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        String query = 'SELECT Id, Name, accountId, account.Reset_Owner_Assignment__c, Sales_Status__c, OtherState FROM Contact where (account.Reset_Owner_Assignment__c = true OR ( accountId = null AND (Sales_Status__c = \'Actual Customer\' OR Sales_Status__c = \'Target Customer\'))) And Manual_Owner_Override__c = false And RecordType.Name = \'Adjuster\'';
        return Database.getQueryLocator(query);
    }
   
    global void execute(Database.BatchableContext BC, List<Contact> conList) {
         
         Set<id> accids = new Set<id>();
         
         for(Contact c : conList){
             if(c.accountid <> null){
                accids.add(c.accountId);
             }         
         }
         
         Map<Id,Account> acctMap = new Map<Id,Account>([select Id, Assigned_Map__c, Contact_Owner_Override__c from Account where Id in: accids]);
         set<id> accAssessmentIds = new set<id>();
         
         for(Account acc : acctMap.values()){
         
             acc.Reset_Owner_Assignment__c = false;
         
              if(acc.Assigned_Map__c != null)
                  accAssessmentIds.add(acc.Assigned_Map__c);
         }
        
        
        //Account Map Query
        List<Owner_Territory__c> ownerMapList = [select id, Owner_Assignment__c, States__c, Territory_Owner__c, Owner_Assignment__r.recordtype.Name, Owner_Assignment__r.Unassigned_State_Fallback_Owner__c from Owner_Territory__c where Owner_Assignment__c in: accAssessmentIds];
        Map<Id,List<Owner_Territory__c>> ownerMapListMap = new Map<Id,List<Owner_Territory__c>>();
        
        for(Owner_Territory__c oMap : ownerMapList){
            if(ownerMapListMap.keySet().contains(oMap.Owner_Assignment__c)){
                ownerMapListMap.get(oMap.Owner_Assignment__c).add(oMap);
            }
            else{
                ownerMapListMap.put(oMap.Owner_Assignment__c, new List<Owner_Territory__c>{oMap});
            }
        }
        
        List<Owner_Territory__c> defaultRMMapList = [Select Id, Owner_Assignment__c, States__c, Owner_Assignment__r.recordtype.Name, Owner_Assignment__r.Unassigned_State_Fallback_Owner__c, Territory_Owner__c from Owner_Territory__c  where Owner_Assignment__r.recordtype.Name ='Default RM' AND Territory_Owner__c != null];
        List<Owner_Territory__c> TSMMapList = [Select Id, Owner_Assignment__c, States__c, Owner_Assignment__r.recordtype.Name, Owner_Assignment__r.Unassigned_State_Fallback_Owner__c, Territory_Owner__c from Owner_Territory__c where Owner_Assignment__r.recordtype.Name ='TSM' AND Territory_Owner__c != null];
                
        for(contact c: conList){
            
            // Account Map assignment
                    if( (c.accountid == null && c.Sales_Status__c == 'Actual Customer') || (c.accountid <> null && acctMap.get(c.accountid) != null && (acctMap.get(c.accountid).Contact_Owner_Override__c == 'Always RM' || ((acctMap.get(c.accountid).Contact_Owner_Override__c == '' || acctMap.get(c.accountid).Contact_Owner_Override__c == null) && c.Sales_Status__c == 'Actual Customer'))) ){
                    
                            List<Owner_Territory__c> ownerMapDummyList = new List<Owner_Territory__c>();                    
                            
                            // When Contact has Account and that Account has value in Assigned_Map__c field
                            //************************************************** START ****************************************************************************
                            if(c.accountid <> null && acctMap.get(c.accountid) != null && ownerMapListMap.get(acctMap.get(c.accountid).Assigned_Map__c) != null){                        
                                ownerMapDummyList = ownerMapListMap.get(acctMap.get(c.accountid).Assigned_Map__c);
                            }
                            //************************************************** END ****************************************************************************
                    
                            // When contact doesn't has Account OR contact has Account but no value in Assigned_Map__c field 
                            //************************************************** START ****************************************************************************                   
                            if(c.accountid == null || (c.accountid != null && ownerMapListMap.get(acctMap.get(c.accountid).Assigned_Map__c) == null)){                    
                                ownerMapDummyList = defaultRMMapList;
                            }
                            //************************************************** END ****************************************************************************
                            
                            if(!ownerMapDummyList.isEmpty()){
                                
                                for(Owner_Territory__c oMap : ownerMapDummyList){
                                    
                                    if((c.OtherState == '' || c.OtherState == null) && oMap.Owner_Assignment__r.recordtype.Name =='Default RM'){
                                        c.ownerid = oMap.Territory_Owner__c;
                                        break;
                                    }
                                    
                                    if(c.OtherState != '' && c.OtherState != null && oMap.States__c != null && oMap.States__c != '' ){                            
                                         
                                          List<String> states = oMap.States__c.split(';');
                                          Set<String> statecodes = new Set<String>();
                                          statecodes.addAll(states);
                                          
                                          if(statecodes.contains(c.otherstate)){
                                                if(oMap.Territory_Owner__c <> null){
                                                     c.ownerid = oMap.Territory_Owner__c;
                                                     break;
                                                }
                                          }
                                          else{
                                              if(oMap.Owner_Assignment__r.Unassigned_State_Fallback_Owner__c <> null){
                                                  c.ownerid = oMap.Owner_Assignment__r.Unassigned_State_Fallback_Owner__c;
                                              }
                                          }
                                    }
                                }
                            }
                            
                    }
                    
                    // TSM Map Assignment
                    if( (c.accountid == null && c.Sales_Status__c == 'Target Customer') || (c.accountid <> null && acctMap.get(c.accountid) != null && (acctMap.get(c.accountid).Contact_Owner_Override__c == 'Always TSM' || ((acctMap.get(c.accountid).Contact_Owner_Override__c == '' || acctMap.get(c.accountid).Contact_Owner_Override__c == null) && c.Sales_Status__c == 'Target Customer'))) ){
                        
                            for(Owner_Territory__c oMap : defaultRMMapList){
                                    
                                if((c.OtherState == '' || c.OtherState == null) && oMap.Owner_Assignment__r.recordtype.name =='Default RM'){
                                    c.ownerid = oMap.Territory_Owner__c;
                                    System.debug('***hello456***');
                                    break;
                                }
                            }
                                for(Owner_Territory__c oMap : TSMMapList){  
                                if(c.OtherState != '' && c.OtherState != null && oMap.States__c != null && oMap.States__c != '' ){                            
                                     
                                      List<String> states = oMap.States__c.split(';');
                                      Set<String> statecodes = new Set<String>();
                                      statecodes.addAll(states);
                                      
                                      if(statecodes.contains(c.otherstate)){
                                            if(oMap.Territory_Owner__c <> null){
                                                 c.ownerid = oMap.Territory_Owner__c;
                                                 break;
                                            }
                                      }
                                      else{
                                           if(oMap.Owner_Assignment__r.Unassigned_State_Fallback_Owner__c <> null){
                                                  c.ownerid = oMap.Owner_Assignment__r.Unassigned_State_Fallback_Owner__c;
                                            }
                                      }
                                }
                            }
                    }        
                
        } // End of Main for loop 
         
        update conList;
        
        if(!acctMap.values().isEmpty()){
            Util.setAlreadyFired('Account');
            update acctMap.values();
        }
        
    }   
    
    global void finish(Database.BatchableContext BC) {
    } 
}