src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>National_Account_Code__c</fullName>
        <label>National Account Code</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AAA</fullName>
                </value>
                <value>
                    <fullName>ALL</fullName>
                </value>
                <value>
                    <fullName>ASSURANT</fullName>
                </value>
                <value>
                    <fullName>CFIN</fullName>
                </value>
                <value>
                    <fullName>FARM</fullName>
                </value>
                <value>
                    <fullName>FEMA</fullName>
                </value>
                <value>
                    <fullName>HAN</fullName>
                </value>
                <value>
                    <fullName>LIB</fullName>
                </value>
                <value>
                    <fullName>LUXPRO</fullName>
                </value>
                <value>
                    <fullName>MER</fullName>
                </value>
                <value>
                    <fullName>NJM</fullName>
                </value>
                <value>
                    <fullName>POLICY</fullName>
                </value>
                <value>
                    <fullName>QBE</fullName>
                </value>
                <value>
                    <fullName>SAFE</fullName>
                </value>
                <value>
                    <fullName>STATE</fullName>
                </value>
                <value>
                    <fullName>TRAV</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>National_Account_Name__c</fullName>
        <label>National Account Name</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>National_Account__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Allstate</fullName>
                </value>
                <value>
                    <fullName>The Hartford</fullName>
                </value>
                <value>
                    <fullName>State Farm</fullName>
                </value>
                <value>
                    <fullName>Zurich NA</fullName>
                </value>
                <value>
                    <fullName>Safeco</fullName>
                </value>
                <value>
                    <fullName>American Family</fullName>
                </value>
                <value>
                    <fullName>FEMA</fullName>
                </value>
                <value>
                    <fullName>Liberty Mutual</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>National_Account__c</fullName>
        <label>National Account</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Payment_Terms__c</fullName>
        <label>Payment Terms</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>20</fullName>
                </value>
                <value>
                    <fullName>30</fullName>
                </value>
                <value>
                    <fullName>45</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Active - potential of doing business
Inactive - not able to do business
No Longer with Company</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>No Longer with Company</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Agent</fullName>
                </value>
                <value>
                    <fullName>Catastrophe</fullName>
                </value>
                <value>
                    <fullName>Company</fullName>
                </value>
                <value>
                    <fullName>Contractor</fullName>
                </value>
                <value>
                    <fullName>FEMA</fullName>
                </value>
                <value>
                    <fullName>Independent</fullName>
                </value>
                <value>
                    <fullName>Landlord</fullName>
                </value>
                <value>
                    <fullName>Lawyer</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Policyholder</fullName>
                </value>
                <value>
                    <fullName>Procurement</fullName>
                </value>
                <value>
                    <fullName>Public</fullName>
                </value>
                <value>
                    <fullName>Restoration</fullName>
                </value>
                <value>
                    <fullName>Supervisor</fullName>
                </value>
                <value>
                    <fullName>TPA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Adjuster</fullName>
        <active>true</active>
        <description>All contacts that work in the Insurance Industry. Includes Company Adjusters, Independent Adjusters, Public Adjusters, Supervisors, Managers, Procurement etc.</description>
        <label>Adjuster</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ContactTermsTest.cls
@isTest
public class ContactTermsTest {
        
    static testMethod void myShareTest()
    {

        RecordType rt = [ select Id from RecordType where Name = 'Adjuster' ];
        
        /*
        Account a = new Account();
            
        a.name = 'State Farm Insurance';
        a.Type = 'Insurance Company';
        a.BillingCountry = 'US';
        a.BillingState = 'AZ';
        
        a.National_Account__c = 'Yes';
        a.National_Account_Name__c = 'State Farm';
    //  a.National_Account_Code__c = 'NATACT04';
        
        
        insert a;
        */
    //  Account new_a = [ select id from account where id = :a.Id ];
        
    //  System.debug('a.Id = ' + a.Id);
    //  System.debug('new_a.Id = ' + new_a.Id);
    
    

        Contact c = new Contact();
        
        c.RecordTypeId = rt.Id;
        
        c.FirstName = 'Darren';
        c.LastName = 'Kemp';
        
        c.Status__c = 'Active'; 
        
        c.Payment_Terms__c = '45';
        c.LeadSource = 'Other';
        c.MailingCountry = 'US';
        
        c.Type__c = 'Company';
        c.MailingState = 'AZ';
    //    c.Account = a;
    //  c.AccountId = a.Id;
        
        c.AccountID = '001S0000003HfcU';     
        
        try 
        {
            insert c;
            
            System.debug('Contact.AccountId = ' + c.AccountId);      
            System.assertEquals( '45', c.Payment_Terms__c); 
       
            Contact new_c = [ select id, Payment_Terms__c from contact where id = :c.Id ];
            System.assertEquals( '30', new_c.Payment_Terms__c ); 
                  
        } 
        catch (System.DmlException e)
        {
            System.debug('we caught a dml exception: ' + e.getDmlMessage(0));    
        }
       
    }
}