src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>National_Account__c</fullName>
        <label>National Account</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Payment_Terms__c</fullName>
        <label>Payment Terms</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>20</fullName>
                </value>
                <value>
                    <fullName>30</fullName>
                </value>
                <value>
                    <fullName>45</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Active - potential of doing business
Inactive - not able to do business
No Longer with Company</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>No Longer with Company</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestContactTermsTrigger.cls
@isTest
public class TestContactTermsTrigger 

{

    static testMethod void myShareTest()

    {

    

   /*Zishan Comment out this section Bad Code

        Contact c = new Contact();

        c.FirstName = 'Darren';

        c.LastName = 'Kemp';

        c.Payment_Terms__c = '45';

        c.AccountID = '0017000000Q4aAtAAJ';  */

/*Zishan Added in this code to make this class correct   */     

Account a = new Account

                    (
                      National_Account__c = 'Yes',
                      name='Allstate',

                      Active__c=True,

                      BillingState='CT',

                      BillingStreet='134 Laurel',

                      BillingCity='Mineola',

                      BillingPostalCode='11501',

                      BillingCountry='USA',

                      ShippingState = 'CT',

                      ShippingCountry = 'USA',

                      ShippingPostalCode = '11501',

                      ShippingCity = 'Mineola',

                      ShippingStreet = '134 Laurel'

                    );

        insert a;              


      

        Contact c = new Contact();


                    c.LastName='xxxxxx';

                    c.AccountId=a.id;

                    c.Status__c='Active';

                    c.MailingCountry='USA';

                    c.MailingState='CT';

                    c.MailingStreet='134 Laurel';

                    c.MailingCity='Mineola';

                    c.MailingPostalCode='11501';

                    c.Payment_Terms__c = '45';

        

           insert c;

           
            
            System.assertEquals(c.Payment_Terms__c, '45');       

 

    }



}