src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Adjustment__c.object
<CustomObject>
    <description>Adjust LL, Adjuster costs and fees related to placement rent &amp; property. (No Furniture Adjustments!)</description>
    <fields>
        <fullName>Adjustment_Description__c</fullName>
        <label>Adjustment Description</label>
        <length>55</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Adjustment_Effective_Date__c</fullName>
        <inlineHelpText>Enter the date the recurring billing adjustment is effective. This is required for monthly billing adjustments.</inlineHelpText>
        <label>Adjustment Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Billing_Adjustment__c</fullName>
        <inlineHelpText>Enter the amount the recurring billing should change.</inlineHelpText>
        <label>Billing Adjustment</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Fee_Frequency__c</fullName>
        <label>Fee Frequency</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Daily</fullName>
                </value>
                <value>
                    <fullName>One Time</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Hotel_Adjustment_Fee__c</fullName>
        <label>Hotel Adjustment Fee</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Hotel_Fee_Effective_Date__c</fullName>
        <label>Hotel Fee Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Hotel_Fee_Type__c</fullName>
        <label>Hotel Fee Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Parking Fee</fullName>
                </value>
                <value>
                    <fullName>Pet Fee</fullName>
                </value>
                <value>
                    <fullName>Other Fee</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Hotel_Rate_Adjustment__c</fullName>
        <inlineHelpText>Enter the new daily rate.</inlineHelpText>
        <label>Hotel Rate Adjustment</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Hotel_Room_Lookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Hotel Room Lookup</label>
        <referenceTo>Hotel_Room__c</referenceTo>
        <relationshipLabel>Adjustments</relationshipLabel>
        <relationshipName>Adjustments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Housing_Adjustment_Fee__c</fullName>
        <inlineHelpText>Enter the one time fee amount.</inlineHelpText>
        <label>Housing Adjustment Fee</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Housing_Credit_Proposed_Amount__c</fullName>
        <inlineHelpText>Enter the requested credit amount and submit for approval.</inlineHelpText>
        <label>Housing Credit Proposed Amount</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Housing_Fee_Effective_Date__c</fullName>
        <inlineHelpText>Enter the effedtive date for the housing fee.</inlineHelpText>
        <label>Housing Fee Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Housing_Fee_Type__c</fullName>
        <label>Housing Fee Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Application Fee</fullName>
                </value>
                <value>
                    <fullName>Broker Fee</fullName>
                </value>
                <value>
                    <fullName>Break Lease Fee</fullName>
                </value>
                <value>
                    <fullName>Late Fee</fullName>
                </value>
                <value>
                    <fullName>Cancellation Fee</fullName>
                </value>
                <value>
                    <fullName>Pick-Up Fee</fullName>
                </value>
                <value>
                    <fullName>Delivery Fee</fullName>
                </value>
                <value>
                    <fullName>Security Deposit</fullName>
                </value>
                <value>
                    <fullName>Credit</fullName>
                </value>
                <value>
                    <fullName>Other Fee</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Other_Description__c</fullName>
        <inlineHelpText>Enter the description when Other is chosen as the Fee Type.</inlineHelpText>
        <label>Other Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Other_Fee_Description__c</fullName>
        <label>Other Fee Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Placement_Lookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Placement Lookup</label>
        <referenceTo>Placement__c</referenceTo>
        <relationshipLabel>Adjustments</relationshipLabel>
        <relationshipName>Adjustments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rate_Adjustment_Effective_Date__c</fullName>
        <label>Rate Adjustment Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Rent_Adjustment_Effective_Date__c</fullName>
        <label>Rent Adjustment Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Rent_Adjustment__c</fullName>
        <inlineHelpText>Enter the amount the recurring rent is changing.</inlineHelpText>
        <label>Rent Adjustment</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Trailer_Mobile_Home__c</fullName>
        <label>Trailer-Mobile Home Fee</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Delivery Fee</fullName>
                </value>
                <value>
                    <fullName>Dozer Fee</fullName>
                </value>
                <value>
                    <fullName>Electric Hookup Fee</fullName>
                </value>
                <value>
                    <fullName>Set-Up Fee</fullName>
                </value>
                <value>
                    <fullName>Site Inspection Fee</fullName>
                </value>
                <value>
                    <fullName>Skirting Fee</fullName>
                </value>
                <value>
                    <fullName>Utility Pole Fee</fullName>
                </value>
                <value>
                    <fullName>Winterization Fee</fullName>
                </value>
                <value>
                    <fullName>Other Fee</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Adjustment</label>
    <nameField>
        <displayFormat>Adj-{00000}</displayFormat>
        <label>Adjustment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Adjustments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Hotel_Room__c.object
<CustomObject>
    <description>Holds the information related to a Hotel Booking.</description>
    <fields>
        <fullName>Other_Fee_Description__c</fullName>
        <label>Other Fee Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Placement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Placement</label>
        <referenceTo>Placement__c</referenceTo>
        <relationshipLabel>Hotel Rooms</relationshipLabel>
        <relationshipName>Hotel_Rooms</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Hotel Room</label>
    <nameField>
        <displayFormat>Room-{00000}</displayFormat>
        <label>Hotel Room</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hotel Rooms</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Damaged_Property_Address__c</fullName>
        <label>Damaged Property Address</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Damaged_Property_City__c</fullName>
        <label>Damaged Property City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Damaged_Property_State__c</fullName>
        <label>Damaged Property State/Province</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DC</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
                <value>
                    <fullName>MN</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
                <value>
                    <fullName>MS</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
                <value>
                    <fullName>NC</fullName>
                </value>
                <value>
                    <fullName>ND</fullName>
                </value>
                <value>
                    <fullName>NE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Damaged_Property_Type__c</fullName>
        <label>Damaged Property Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Apartment</fullName>
                </value>
                <value>
                    <fullName>Condo</fullName>
                </value>
                <value>
                    <fullName>House</fullName>
                </value>
                <value>
                    <fullName>Mobile Home</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Townhouse</fullName>
                </value>
                <value>
                    <fullName>Travel Trailer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Initial_Service_Request__c</fullName>
        <label>Initial Service Request</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Housing</fullName>
                </value>
                <value>
                    <fullName>Hotel</fullName>
                </value>
                <value>
                    <fullName>FRV</fullName>
                </value>
                <value>
                    <fullName>Furniture Only</fullName>
                </value>
                <value>
                    <fullName>Unfurnished</fullName>
                </value>
                <value>
                    <fullName>Trailer-Mobile Home</fullName>
                </value>
                <value>
                    <fullName>Commercial</fullName>
                </value>
                <value>
                    <fullName>Finders Fees</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type_of_Loss__c</fullName>
        <label>Type of Loss</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CAT</fullName>
                </value>
                <value>
                    <fullName>Fire</fullName>
                </value>
                <value>
                    <fullName>Mold</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Tornado</fullName>
                </value>
                <value>
                    <fullName>Water</fullName>
                </value>
                <value>
                    <fullName>Wind</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/AELinesItem.cls
public class AELinesItem {
    public Placement__c placement { get; private set;} 
    public Adjustment__c[] adjLineItems { get; private set; }
    string htl;

    private ApexPages.StandardController controller;
    
    void queryAELines(id id) { 
    placement = [Select p.id,  
                        (Select Name, RecordTypeId, Rent_Adjustment__c, 
                        Billing_Adjustment__c, Fee_Frequency__c, Hotel_Rate_Adjustment__c, 
                        Housing_Fee_Type__c, Hotel_Fee_Type__c, Trailer_Mobile_Home__c, 
                        Placement_Lookup__c, Other_Description__c, Housing_Fee_Effective_Date__c, 
                        Hotel_Fee_Effective_Date__c, Housing_Adjustment_Fee__c, 
                        Hotel_Adjustment_Fee__c, Hotel_Room_Lookup__c,Housing_Credit_Proposed_Amount__c, 
                        Other_Fee_Description__c, Adjustment_Effective_Date__c,Rate_Adjustment_Effective_Date__c,
                        Rent_Adjustment_Effective_Date__c, Adjustment_Description__c From Adjustments__r )
                        From Placement__c p
                where p.id = :id limit 1];  
            
            
    adjLineItems = placement.Adjustments__r; 
    for ( Adjustment__c ql : adjLineItems ) 
    { 
        htl = ql.Hotel_Room_Lookup__c;
    }

}
public pagereference CopyOperation() { 
       
        string reloadQuote = ApexPages.CurrentPage().getParameters().get('reloadQuote');
        
        return null;
    } 

    public AELinesItem() {
        placementid = ApexPages.CurrentPage().getParameters().get('id');
        init(); 
    }
    public AELinesItem(ApexPages.StandardController c) {
        controller = c;
        placementid = c.getRecord().id;
        init();
    } 
	public pagereference recalc() {
         
        for ( Adjustment__c hr : adjLineItems ) { 
        }

        return null;
    }
      id placementid;  
    
	void init() { 
        queryAELines(placementid);
        if(adjLineItems.size()==0){
           add();
        }   
	}
    
         
    PageReference placementPR() { return new pagereference('/'+placement.id); }
    public list<Adjustment__c> todelete = new list<Adjustment__c>();

        
    public PageReference save() { 
        try { 
            
            upsert adjLineItems;
            if ( todelete.size() > 0 ) {            
                delete todelete;    
            }
            queryAELines(placement.id);
        } 
        catch ( DmlException exc) { 
             ApexPages.addMessages(exc); 
             return null;
        }       
        
        return placementPR(); 
    }
        
    public PageReference add() { 
        // insert a new line
        //Adjustment__c h =  new Adjustment__c(Placement_Lookup__c = placement.id,
        //                                    Hotel_Room_Lookup__c = htl) ;
        Adjustment__c h =  new Adjustment__c(Placement_Lookup__c = placement.id) ;
        adjLineItems.add ( h );
        
        
        return null; 
    }
     
    public PageReference reset() { 
        queryAELines(placement.id);
        return null;
    } 
/* Test Method for this Controller Starts Here From Zishan R./Enterprise Tech Consultants Inc.*/    
    static testMethod void testAELinesItem() {
/*CREATE NEW ACCOUNT*/
    RecordType rta = [Select Id, Name from RecordType where sobjecttype='Account' 
    and Name like 'Hotel%' limit 1];

        Account a = new Account
                    (
                      RecordTypeId = rta.Id,
                      name='zishanabc',
                      Active__c=True,
                      BillingState='CT',
                      BillingStreet='134 Laurel',
                      BillingCity='Mineola',
                      BillingPostalCode='11501',
                      BillingCountry='USA',
                      ShippingState = 'CT',
                      ShippingCountry = 'USA',
                      ShippingPostalCode = '11501',
                      ShippingCity = 'Mineola',
                      ShippingStreet = '134 Laurel'
                    );
        insert a;

        // Insert Users
        Profile profile = [SELECT Id FROM Profile WHERE Name='Operations User']; 
        User user1 = new User
                (   
                    Alias = 'opsusr',
                    Email='operationsuser@testorg.com', 
                    EmailEncodingKey='UTF-8', 
                    LastName='Testing', 
                    LanguageLocaleKey='en_US',
                    LocaleSidKey='en_US', 
                    ProfileId = profile.Id, 
                    TimeZoneSidKey='America/Los_Angeles', 
                    UserName='operationsuser@crstemphousing.com');
        insert user1;     
       
        //Insert an Opportunity 
        Opportunity o = new Opportunity
                (
                    StageName = 'Submitted',
                    name='test11',
                    Initial_Service_Request__c='Hotel',   
                    CloseDate = Date.newInstance(2010,12,10),
                    Type_of_Loss__c = 'Mold',
                    Damaged_Property_Type__c = 'Apartment',
                    Damaged_Property_Address__c = '134 Laurel',
                    Damaged_Property_City__c = 'Mineola',
                    Damaged_Property_State__c = 'CT',
                    Damaged_Property_Zip__c = '11501',
                    Damaged_Property_Country__c = 'USA',
                    Regional_Manager__c = user1.Id,
                    Customer_Care_Specialist__c = user1.Id,
                    Hotel_Customer_Care_Specialist__c = user1.Id);
        insert o;


        RecordType rtpl = [
                    Select Id, Name from 
                    RecordType where sobjecttype='Placement__c' 
                    and Name Like 'Hotel Placement' limit 1
                    ];
        
        Placement__c p = new Placement__c(
                    RecordTypeId=rtpl.Id,
                    Name='ZishanPlacement',
                    opportunity__c=o.id, 
                    Status__c='Moved-In', 
                    Hotel_Account_Lookup__c=a.id);
        insert p;
        
         Hotel_Room__c hotelRoom = new Hotel_Room__c(
                    placement__c = p.Id, 
                    Room_Type__c = 'Standard Double',
                    Parking_Fee_Type__c = 'False',
                    Pet_Fee_Type__c = 'False',
                    Check_In__c = Date.newInstance(2009,09,09),
                    Checkout__c = Date.newInstance(2009,09,11));
        insert hotelRoom;
                     

        PageReference pageRefa = new PageReference('/apex/editAdjustments?id=' + p.id);
        Test.setCurrentPage(pageRefa);
        system.debug( 'placement id is '+p.id);
        
        ApexPages.currentPage().getParameters().put('id', p.id);
        
        AELinesItem s = new AELinesItem();
        ApexPages.currentPage().getParameters().put('reloadQuote','1');
        Adjustment__c aa = new Adjustment__c(
                        Adjustment_Effective_Date__c=Date.newInstance(2010,12,10),
                        Placement_Lookup__c=p.id, 
                        Hotel_Fee_Effective_Date__c=Date.newInstance(2010,12,10),
                        Hotel_Fee_Type__c='Parking Fee', 
                        Fee_Frequency__c='Daily', 
                        Other_Fee_Description__c='blah', 
                        Hotel_Rate_Adjustment__c=25.00,
                        Hotel_Room_Lookup__c=hotelRoom.Id, 
                        Rate_Adjustment_Effective_Date__c=Date.newInstance(2010,12,10));
        insert aa;           

        s.CopyOperation(); 
       
        s.save() ;

        
        s.adjLineItems = Database.query(
                        'Select Name, RecordTypeId, Rent_Adjustment__c, '+ 
                        'Billing_Adjustment__c, Fee_Frequency__c, Hotel_Rate_Adjustment__c, '+ 
                        'Housing_Fee_Type__c, Hotel_Fee_Type__c, Trailer_Mobile_Home__c, '+ 
                        'Placement_Lookup__c, Other_Description__c, Housing_Fee_Effective_Date__c, '+ 
                        'Hotel_Fee_Effective_Date__c, Housing_Adjustment_Fee__c, '+ 
                        'Hotel_Adjustment_Fee__c, Hotel_Room_Lookup__c,Housing_Credit_Proposed_Amount__c, '+ 
                        'Other_Fee_Description__c, Adjustment_Effective_Date__c, '+
                        'Rate_Adjustment_Effective_Date__c, '+
                        'Rent_Adjustment_Effective_Date__c, Adjustment_Description__c From Adjustment__c  '+
                        'where Placement_Lookup__c = \''+ p.Id+'\' ');
        s.recalc();    
            
        ApexPages.currentPage().getParameters().put('reloadQuote','1');

        ApexPages.currentPage().getParameters().put('reloadOpp','1');
        s.CopyOperation(); 
        
        ApexPages.currentPage().getParameters().put('delname', s.adjLineItems[0].name );
        s.add();
        s.save(); 
        s.reset();
       
        ApexPages.CurrentPage().getParameters().put('reloadOpp',null );
        ApexPages.CurrentPage().getParameters().put('reloadQuote',null );
        AELinesItem s3 = new AELinesItem();
        system.assertEquals( null, s3.CopyOperation() ); 

    }       


}