src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <description>The email address of the landlord.</description>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Customer_Care_Specialist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Care Specialist</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Policyholder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Policyholder</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Policyholder, Adjuster Policyholder Record Type</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Claims</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Placement__c.object
<CustomObject>
    <description>Holds information about a housing placement, when the Opportunity stage is set to Moved-In, and a policy holder moves into the temporarry housing.  Besides the detail about the duration of the placement, this object is related to Cases to track any issues related to the placement.</description>
    <fields>
        <fullName>Move_Out_Date__c</fullName>
        <label>Move Out Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Claim Lookup</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Placements</relationshipLabel>
        <relationshipName>Placements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Selected_Search__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Selected Search</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.ServiceRequest__c</field>
                <operation>equals</operation>
                <valueField>Searches__c.Service_Request__r.Id</valueField>
            </filterItems>
            <filterItems>
                <field>Searches__c.Selected__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Searches__c</referenceTo>
        <relationshipLabel>Placements</relationshipLabel>
        <relationshipName>Placements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ServiceRequest__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Request</label>
        <referenceTo>ServiceRequest__c</referenceTo>
        <relationshipLabel>Placements</relationshipLabel>
        <relationshipName>Placements1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Placement</label>
    <nameField>
        <label>Placement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Placements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Searches__c.object
<CustomObject>
    <description>Used track the property and hotel searches conducted as part of the Sevice Request</description>
    <fields>
        <fullName>Days_Notice_Required__c</fullName>
        <label>Days Notice Required</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Landlord__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Landlord</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Landlord</value>
            </filterItems>
            <filterItems>
                <field>Contact.Status__c</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Searches</relationshipLabel>
        <relationshipName>Searches</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NTV_Send_To__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>This is the contact to send the Notice to Vacate to.  Defaults to the Landlord but can be overridden</description>
        <label>NTV Send To</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Landlord, Agent, Broker</value>
            </filterItems>
            <filterItems>
                <field>Contact.Status__c</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Searches (NTV Send To)</relationshipLabel>
        <relationshipName>Searches1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Placement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Placement</label>
        <referenceTo>Placement__c</referenceTo>
        <relationshipName>Searches</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Request__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Service Request</label>
        <referenceTo>ServiceRequest__c</referenceTo>
        <relationshipName>Searches</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <inlineHelpText>Enter 2-character  capital state abbreviation.</inlineHelpText>
        <label>State/Province</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Temporary_Address__c</fullName>
        <formula>Street_Addr1__c&amp;IF( LEN(Street_Addr2__c) &gt; 0 , &quot; &quot;, &quot;&quot;) &amp; Street_Addr2__c &amp; &quot;,&quot; &amp;  City__c  &amp; &quot;, &quot; &amp; State__c  &amp; &quot; &quot; &amp;  Zip__c &amp; &quot;, &quot; &amp; Country__c</formula>
        <label>Temporary Address</label>
        <type>Text</type>
    </fields>
    <label>Search</label>
    <nameField>
        <displayFormat>SR-{000000}</displayFormat>
        <label>Search Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Searches</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/ServiceRequest__c.object
<CustomObject>
    <description>Holds the different services that a request can include, such as: Hotel Stays, Housing requests, Furniture requests, Fair Rental Value, etc.</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Claim</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Service Requests</relationshipLabel>
        <relationshipName>Service_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Selected_Search__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Selected Search</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Id</field>
                <operation>equals</operation>
                <valueField>Searches__c.Service_Request__c</valueField>
            </filterItems>
            <filterItems>
                <field>Searches__c.Selected__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Searches__c</referenceTo>
        <relationshipLabel>Service Requests (Selected Search)</relationshipLabel>
        <relationshipName>Service_Requests1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ServiceRequest__c</fullName>
        <formula>Id</formula>
        <label>ServiceRequest</label>
        <type>Text</type>
    </fields>
    <label>Service Request</label>
    <nameField>
        <displayFormat>SR#-{000000}</displayFormat>
        <label>Service Request</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/NTVDocumnetController.cls
Public class NTVDocumnetController{
    
    Public String toDay {get;set;}
    String servReqId;    
    Public Placement__c placementRecord {get;set;}
    Public ServiceRequest__c serviceReqRec {get;set;}
    
    Public String billingAddress {get;set;}    
    Public String placemnetTemporaryAddress {get;set;}
    Public String placementTemporaryState {get;set;}
    Public String moveOutDate {get;set;}
    
    Public NTVDocumnetController(){        
        
        DateTime dt = DateTime.newInstance(Date.toDay().year(), Date.toDay().month(), Date.toDay().day(), 0, 0, 0);
        toDay = dt.format('MMMMM') + ' ' + Date.toDay().day() +', '+ Date.toDay().year();

        servReqId = ApexPages.currentPage().getParameters().get('reqId');        
        placementRecord = new Placement__c();
        serviceReqRec = new ServiceRequest__c();
        billingAddress = '';
        placemnetTemporaryAddress = '';
        placementTemporaryState = '';
        moveOutDate = '';
        
        serviceReqRec = [Select Id, Opportunity__r.Name, Opportunity__r.Policyholder__r.Name, Opportunity__r.Customer_Care_Specialist__r.Name, Opportunity__r.Customer_Care_Specialist__r.Phone, Opportunity__r.Customer_Care_Specialist__r.Fax from ServiceRequest__c where Id =: servReqId];        
                
        List<Searches__c> searchList = [Select Id, Landlord__c, Temporary_Address__c, State__c from Searches__c where Service_Request__c =: servReqId AND Landlord__c != null];
        
        if(!searchList.isEmpty()){
            String tempAddrString = searchList[0].Temporary_Address__c;
            placemnetTemporaryAddress = searchList[0].Temporary_Address__c;
            if(tempAddrString != null && tempAddrString != '' && tempAddrString.contains(',')){
                
                tempAddrString = tempAddrString.subStringBeforeLast(',');
                
                String[] addArr = tempAddrString.split(',');
                placemnetTemporaryAddress = String.join(addArr, ', ');
                
            }            
            placementTemporaryState = searchList[0].State__c;
        }    
        
        
        List<Placement__c> placementList = [Select Id, Selected_Search__r.Days_Notice_Required__c, 
                                                       Selected_Search__r.NTV_Send_To__c,
                                                       Selected_Search__r.NTV_Send_To__r.Name,
                                                       Selected_Search__r.NTV_Send_To__r.Account.BillingStreet,
                                                       Selected_Search__r.NTV_Send_To__r.Account.BillingCity,
                                                       Selected_Search__r.NTV_Send_To__r.Account.BillingState,
                                                       Selected_Search__r.NTV_Send_To__r.Account.BillingCountry,
                                                       Selected_Search__r.NTV_Send_To__r.Account.BillingPostalCode,
                                                       Selected_Search__r.NTV_Send_To__r.Account.Name,
                                                       Selected_Search__r.NTV_Send_To__r.Account.Phone,
                                                       Selected_Search__r.NTV_Send_To__r.Account.Fax,
                                                       Selected_Search__r.NTV_Send_To__r.Account.Email__c,                                                       
                                                       Move_Out_Date__c
                                                        from Placement__c where ServiceRequest__c =: servReqId limit 1];
        
        if(!placementList.isEmpty())
            placementRecord = placementList[0]; 
            
        if(placementRecord.Move_Out_Date__c != null){            
            moveOutDate = placementRecord.Move_Out_Date__c.month() + '/' + placementRecord.Move_Out_Date__c.day() + '/' + placementRecord.Move_Out_Date__c.year();
        }  
            
        if(placementRecord.Selected_Search__r.NTV_Send_To__r.Account.BillingStreet != null && placementRecord.Selected_Search__r.NTV_Send_To__r.Account.BillingStreet != ''){
            billingAddress = placementRecord.Selected_Search__r.NTV_Send_To__r.Account.BillingStreet;
        }
        if(placementRecord.Selected_Search__r.NTV_Send_To__r.Account.BillingCity != null && placementRecord.Selected_Search__r.NTV_Send_To__r.Account.BillingCity != ''){
            billingAddress = billingAddress + ', ' + placementRecord.Selected_Search__r.NTV_Send_To__r.Account.BillingCity; 
        }
        if(placementRecord.Selected_Search__r.NTV_Send_To__r.Account.BillingState != null && placementRecord.Selected_Search__r.NTV_Send_To__r.Account.BillingState != ''){
            billingAddress = billingAddress + ', ' + placementRecord.Selected_Search__r.NTV_Send_To__r.Account.BillingState;
        }
        if(placementRecord.Selected_Search__r.NTV_Send_To__r.Account.BillingPostalCode != null && placementRecord.Selected_Search__r.NTV_Send_To__r.Account.BillingPostalCode != ''){
            billingAddress = billingAddress + ' ' + placementRecord.Selected_Search__r.NTV_Send_To__r.Account.BillingPostalCode;
        } 
        if(placementRecord.Selected_Search__r.NTV_Send_To__r.Account.BillingCountry != null && placementRecord.Selected_Search__r.NTV_Send_To__r.Account.BillingCountry != ''){
            billingAddress = billingAddress + ', ' + placementRecord.Selected_Search__r.NTV_Send_To__r.Account.BillingCountry;
        }                              
        
    }
}