src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Claim__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Link to Claim if available</description>
        <label>Claim</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>$Source.ContactId</field>
                <operation>equals</operation>
                <valueField>Opportunity.Adjuster__c</valueField>
            </filterItems>
            <filterItems>
                <field>$Source.ContactId</field>
                <operation>equals</operation>
                <valueField>Opportunity.Policyholder__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Claim__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Claim</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Claim__c</fullName>
        <label>Claim #</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Care_Specialist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Care Specialist</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Hotel_Customer_Care_Specialist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Hotel Customer Care Specialist</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Policyholder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Policyholder</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Policyholder, Adjuster Policyholder Record Type</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Claims</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Regional_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Relationship Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities4</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/claimSubmissionController.cls
/*
    class name : claimSubmissionController
    Created By : Bharat
    Description : Used to convert the case into opportunity with respect to some field mapping and tags the case to the opportunity
*/
global class claimSubmissionController
{
    webservice static string caseToClaim(Id caseId)
    { 
         Case case_info = [select id,contact.LastName,contactId,ownerid,Claim__c from case where id =: caseId];
         
         
         opportunity opp_info = new opportunity();
         opp_info.ownerId = userInfo.getUserId();
         opp_info.Policyholder__c = case_info.contactid;
         opp_info.Regional_Manager__c  = userinfo.getuserId();
         opp_info.Customer_Care_Specialist__c = userinfo.getuserId();
         opp_info.Hotel_Customer_Care_Specialist__c = userinfo.getuserId();
         opp_info.StageName = 'Submitted';
         opp_info.closedate = system.today();
         opp_info.Name = 'Temp';
         insert opp_info;
         
         case_info.Claim__c = opp_info.id;
         update case_info;
         return null;
    }
}