src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Lead_Source_Description__c</fullName>
        <label>Lead Source Description</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>LeadSource</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>ACE Claims</fullName>
                </value>
                <value>
                    <fullName>AICA Education</fullName>
                </value>
                <value>
                    <fullName>All-Industry Day</fullName>
                </value>
                <value>
                    <fullName>Association Meeting</fullName>
                </value>
                <value>
                    <fullName>CCC</fullName>
                </value>
                <value>
                    <fullName>CCNC</fullName>
                </value>
                <value>
                    <fullName>FAPIA</fullName>
                </value>
                <value>
                    <fullName>Golf Event</fullName>
                </value>
                <value>
                    <fullName>Kentucky Claims</fullName>
                </value>
                <value>
                    <fullName>NAIIA</fullName>
                </value>
                <value>
                    <fullName>NAPIA</fullName>
                </value>
                <value>
                    <fullName>NLA Trade Fair</fullName>
                </value>
                <value>
                    <fullName>OCAA Symposium</fullName>
                </value>
                <value>
                    <fullName>PLRB Claims</fullName>
                </value>
                <value>
                    <fullName>PLRB Regional</fullName>
                </value>
                <value>
                    <fullName>Social Event</fullName>
                </value>
                <value>
                    <fullName>Unit Meeting</fullName>
                </value>
                <value>
                    <fullName>Windstorm</fullName>
                </value>
                <value>
                    <fullName>Disaster Assistance Center</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Active - potential of doing business
Inactive - not able to do business
No Longer with Company</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>No Longer with Company</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Agent</fullName>
                </value>
                <value>
                    <fullName>Catastrophe</fullName>
                </value>
                <value>
                    <fullName>Company</fullName>
                </value>
                <value>
                    <fullName>Contractor</fullName>
                </value>
                <value>
                    <fullName>FEMA</fullName>
                </value>
                <value>
                    <fullName>Independent</fullName>
                </value>
                <value>
                    <fullName>Landlord</fullName>
                </value>
                <value>
                    <fullName>Lawyer</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Policyholder</fullName>
                </value>
                <value>
                    <fullName>Procurement</fullName>
                </value>
                <value>
                    <fullName>Public</fullName>
                </value>
                <value>
                    <fullName>Restoration</fullName>
                </value>
                <value>
                    <fullName>Supervisor</fullName>
                </value>
                <value>
                    <fullName>TPA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Policyholder</fullName>
        <active>true</active>
        <description>Contacts that are a Policyholder</description>
        <label>Policyholder</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Hotel_Room__c.object
<CustomObject>
    <description>Holds the information related to a Hotel Booking.</description>
    <fields>
        <fullName>Placement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Placement</label>
        <referenceTo>Placement__c</referenceTo>
        <relationshipLabel>Hotel Rooms</relationshipLabel>
        <relationshipName>Hotel_Rooms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Policyholder__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Policyholder</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Hotel Rooms</relationshipLabel>
        <relationshipName>Hotel_Rooms</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Hotel Room</label>
    <nameField>
        <displayFormat>Room-{00000}</displayFormat>
        <label>Hotel Room</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hotel Rooms</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Adjuster__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The adjuster must already be a contact in the system.</inlineHelpText>
        <label>Adjuster</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Adjuster</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Claims (Adjuster)</relationshipLabel>
        <relationshipName>Opportunities2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Initial_Service_Request__c</fullName>
        <label>Initial Service Request</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Housing</fullName>
                </value>
                <value>
                    <fullName>Hotel</fullName>
                </value>
                <value>
                    <fullName>FRV</fullName>
                </value>
                <value>
                    <fullName>Furniture Only</fullName>
                </value>
                <value>
                    <fullName>Unfurnished</fullName>
                </value>
                <value>
                    <fullName>Trailer-Mobile Home</fullName>
                </value>
                <value>
                    <fullName>Commercial</fullName>
                </value>
                <value>
                    <fullName>Finders Fees</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Policyholder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Policyholder</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Policyholder, Adjuster Policyholder Record Type</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Claims</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Claim</fullName>
        <active>true</active>
        <businessProcess>Standard Request</businessProcess>
        <label>Claim</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Placement__c.object
<CustomObject>
    <description>Holds information about a housing placement, when the Opportunity stage is set to Moved-In, and a policy holder moves into the temporarry housing.  Besides the detail about the duration of the placement, this object is related to Cases to track any issues related to the placement.</description>
    <fields>
        <fullName>Check_Out_Date__c</fullName>
        <description>The most recent hotel room check-out date for the placement</description>
        <label>Check-Out Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ServiceRequest__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Request</label>
        <referenceTo>ServiceRequest__c</referenceTo>
        <relationshipLabel>Placements</relationshipLabel>
        <relationshipName>Placements1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Checked-In</fullName>
                </value>
                <value>
                    <fullName>Checked-Out</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Moved-In</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Moved-Out</fullName>
                </value>
                <value>
                    <fullName>Pending Confirmation</fullName>
                </value>
                <value>
                    <fullName>Quote</fullName>
                </value>
                <value>
                    <fullName>Searching</fullName>
                </value>
                <value>
                    <fullName>Pending Check-In</fullName>
                </value>
                <value>
                    <fullName>Lost Opportunity</fullName>
                </value>
                <value>
                    <fullName>Viewing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Placement</label>
    <nameField>
        <label>Placement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Placements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Searches__c.object
<CustomObject>
    <description>Used track the property and hotel searches conducted as part of the Sevice Request</description>
    <fields>
        <fullName>Hotel__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Hotel Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Hotel Accounts</value>
            </filterItems>
            <filterItems>
                <field>Account.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Searches</relationshipLabel>
        <relationshipName>Searches</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Placement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Placement</label>
        <referenceTo>Placement__c</referenceTo>
        <relationshipName>Searches</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IF(  $RecordType.DeveloperName = &quot;Hotel&quot;, &quot;Check Capacity&quot;,IF(ISPICKVAL(Property__r.Status__c , &quot;Occupied&quot;) , &quot;Not Available&quot;, &quot;Available&quot;))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <label>Search</label>
    <nameField>
        <displayFormat>SR-{000000}</displayFormat>
        <label>Search Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Searches</pluralLabel>
    <recordTypes>
        <fullName>Hotel</fullName>
        <active>true</active>
        <description>For Hotel Requests</description>
        <label>Hotel</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/ServiceRequest__c.object
<CustomObject>
    <description>Holds the different services that a request can include, such as: Hotel Stays, Housing requests, Furniture requests, Fair Rental Value, etc.</description>
    <fields>
        <fullName>First_Property_Presented__c</fullName>
        <label>1st Property Presented</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Hotel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Hotel</label>
        <referenceTo>Hotel_Room__c</referenceTo>
        <relationshipName>Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ServiceRequest__c</fullName>
        <formula>Id</formula>
        <label>ServiceRequest</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Request</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Searching</fullName>
                </value>
                <value>
                    <fullName>Pending Confirmation</fullName>
                </value>
                <value>
                    <fullName>Moved-In/Closed</fullName>
                </value>
                <value>
                    <fullName>Finders Fee</fullName>
                </value>
                <value>
                    <fullName>Hold</fullName>
                </value>
                <value>
                    <fullName>Checked-In/Closed</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Lost Opportunity</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Service Request</label>
    <nameField>
        <displayFormat>SR#-{000000}</displayFormat>
        <label>Service Request</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Requests</pluralLabel>
    <recordTypes>
        <fullName>Hotel</fullName>
        <active>true</active>
        <description>For Hotel requests</description>
        <label>Hotel</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/HotelServiceRequestControllerExtTest.cls
@isTest
private class HotelServiceRequestControllerExtTest 
{    
    static Contact ph = createPolicyHolder();
    static Contact adj = createAdjuster();
    static Opportunity claim = createClaim();
    static Account hotelAccount = createHotelAccount('First Hotel');
    static Account hotelAccount2 = createHotelAccount('2nd Hotel');
    static ServiceRequest__c hsr = new ServiceRequest__c();
    static ApexPages.StandardController stdCon = new ApexPages.StandardController(hsr);
    static HotelServiceRequestControllerExtension hsrce = new HotelServiceRequestControllerExtension(stdCon);
  
    
    static testMethod void testControllerMiscProperties() 
    {
        hsrce.getIsProductionOrg();
        hsrce.setIsProductionOrg(false);
        hsrce.getIsBillingSpecialist();
        hsrce.setIsBillingSpecialist(false);
        hsrce.getIsAccountingManager();
        hsrce.setIsAccountingManager(false);
        hsrce.getRateCalendarURL();
        hsrce.setRateCalendarURL('');
        hsrce.getHasRelatedPlacement();
    }
 
    static testMethod void testControllerNewServiceRequest() 
    {
        PageReference pageRef = Page.HotelEntry; 
        Test.setCurrentPage(pageRef);
        
        hsr.RecordTypeId = RecordTypeHelper.hotelServiceRequestRT();
            
        test.starttest();
        
        // Update Service Request
        ApexPages.currentPage().getParameters().clear();
        ApexPages.currentPage().getParameters().put('firstPropertyPresented', '7/8/2010 2:55 PM');
        ApexPages.currentPage().getParameters().put('serviceRequestOpportunity', claim.Id); 
            
              
        hsrce.SaveServiceRequest();
        hsrce.getHasCompletedClaim(); 
     
     //   System.assertEquals('2010-07-08 14:55:00', String.valueOf(hsr.First_Property_Presented__c));
        
        ApexPages.currentPage().getParameters().put('firstPropertyPresented', '');
        ApexPages.currentPage().getParameters().put('serviceRequestOpportunity', claim.Id);  
        ApexPages.currentPage().getParameters().put('serviceRequestDWOReasonCode', 'other');  
        
        hsrce.SaveServiceRequest();
        hsrce.currentUserUpdateOnSRWorkedBy();
        
        hsrce.getHasCompletedClaim();
        hsrce.setHasCompletedClaim(true);
        
        hsrce.accountId = ph.accountId;        
        hsrce.setPlacement(new Placement__c());     
        hsrce.setClaim(new Opportunity());      
        hsrce.getErrorsPresent();       
        hsrce.setHasSelectedHotelSearch(true);      
        hsrce.setHasSelectedHotelSearch(true);      
        hsrce.setInstanceName('');      
        hsrce.getHash();        
                
        Map<String,String> paramsMap = new Map<String, String>();       
        paramsMap.put('serviceRequestOpportunity', claim.Id);       
                
        test.stoptest(); 
    }
    
    static testMethod void testHotelSearches1() 
    {
        test.starttest();
        // Save a new hotel search
        Searches__c hs = hsrce.newHotelSearch;
        hs.Hotel__c = hotelAccount.Id;
        hsrce.newHotelSearch = hs;
        
        ApexPages.currentPage().getParameters().clear();
        ApexPages.currentPage().getParameters().put('selectedHotelName', 'Hotel Search 1');
        ApexPages.currentPage().getParameters().put('firstPropertyPresented', '7/8/2010 2:55 PM');
        ApexPages.currentPage().getParameters().put('selectedDistance', '1.5');
        
        hsrce.saveNewHotelSearch();
               
        string paymentType = 'PayNet';
 
        // Now mark the 1st search as 'selected'
        selectHotelSearch(paymentType);
        
     //   hsrce.getNewCreditCard();
                       
        Double placementCount = hsrce.fetchPlacementCount();
        System.assertEquals(0, placementCount);
        
        // updateSelectedHotelInfo
        List<Searches__c> hotelSearches = hsrce.getHotelSearches();
        
        ApexPages.currentPage().getParameters().clear();
        ApexPages.currentPage().getParameters().put('accountId', hotelSearches[0].Hotel__c);
        hsrce.updateSelectedHotelInfo();
        
        ApexPages.currentPage().getParameters().clear();
        
        hsrce.updatePlacement();
        hsrce.updateVPayCreditCard();
        hsrce.updatePayNetCreditCard();
        hsrce.deleteCreditCard(); 
        hsrce.getHistory();        
        
        hsrce.updateSelectedHotelSearch();
        system.assertEquals(false, hsrce.getHasSelectedHotelSearch());
        
        hsrce.getHistory();
      
        test.stoptest(); 
    }
    
    static testMethod void testHotelSearches2() 
    {
        test.starttest();
       
        // That was so much fun, let's save another hotel search 
        Searches__c hs = hsrce.newHotelSearch;
        hs.Hotel__c = hotelAccount2.Id;
        hsrce.newHotelSearch = hs;
        
        ApexPages.currentPage().getParameters().clear();
        ApexPages.currentPage().getParameters().put('selectedHotelName', 'Hotel Search 2');
        ApexPages.currentPage().getParameters().put('firstPropertyPresented', '7/9/2010 3:55 PM');
        ApexPages.currentPage().getParameters().put('selectedDistance', '2.5');
    
        hsrce.saveNewHotelSearch();
        
        string paymentType = 'Mastercard';
 
        // Now mark the 1st search as 'selected'
        selectHotelSearch(paymentType);
        
   //     hsrce.getNewCreditCard();
                       
        Double placementCount = hsrce.fetchPlacementCount();
        System.assertEquals(0, placementCount);
        
        // updateSelectedHotelInfo
        List<Searches__c> hotelSearches = hsrce.getHotelSearches();
        
        ApexPages.currentPage().getParameters().clear();
        ApexPages.currentPage().getParameters().put('accountId', hotelSearches[0].Hotel__c);
        hsrce.updateSelectedHotelInfo();
        
            
        test.stoptest(); 
    }
  
    static testMethod void testBuildingHotelRooms()
    {   
        PageReference pageRef = Page.HotelEntry; 
        Test.setCurrentPage(pageRef);
      
        // Save a new hotel search
        Searches__c hs = hsrce.newHotelSearch;
        hs.Hotel__c = hotelAccount.Id;
        hsrce.newHotelSearch = hs;
        
        ApexPages.currentPage().getParameters().clear();
        ApexPages.currentPage().getParameters().put('selectedHotelName', 'Hotel Search 1');
        ApexPages.currentPage().getParameters().put('firstPropertyPresented', '7/8/2010 2:55 PM');
        
        hsrce.saveNewHotelSearch();
        
        // That was so much fun, let's save another hotel search
        hs = hsrce.newHotelSearch;
        hs.Hotel__c = hotelAccount2.Id;
        hsrce.newHotelSearch = hs;
        
        ApexPages.currentPage().getParameters().clear();
        ApexPages.currentPage().getParameters().put('selectedHotelName', 'Hotel Search 2');
    
        hsrce.saveNewHotelSearch();
        
        test.starttest();
        
        hsrce.clearHotelRoom();
        
        // Now mark the 1st search as 'selected'
        selectHotelSearch('Direct Bill');
        
        hsrce.getNewCreditCard();
        
        // updateSelectedHotelSearchInfo
        List<Searches__c> hotelSearches = hsrce.getHotelSearches();
        
        ApexPages.currentPage().getParameters().clear();
        ApexPages.currentPage().getParameters().put('accountId', hotelSearches[0].Hotel__c);
        hsrce.updateSelectedHotelInfo();
        
       
        
        boolean initalHasHotelRooms = hsrce.getHasHotelRooms();
        
        // start creating hotel rooms 
        buildEditHotelRoom(hsrce, null, 'Standard King', null, null,
                                                '', '', '', '',
                                                '7/20/2010', '7/30/2010', '140.00', '10.00',
                                                '', '', '','1','1','1');
        
        
        boolean hasHotelRooms = hsrce.getHasHotelRooms();
        system.assertEquals(true, hasHotelRooms);
        // fetch hotel room
        
        List<Hotel_Room__c> rooms = hsrce.getPlacement().Hotel_Rooms__r;
        Hotel_Room__c room = rooms[0];
        
        buildEditHotelRoom(hsrce, room.Id, 'Standard King', 'Confirmation #', null,
                                                'Daily', 'Daily', 'Daily', 'Other Fee Desc',
                                                '7/20/2010', '7/30/2010', '140.00', '10.00',
                                                '5.43', '10.10', '34.12','1','1','1');
        
        // edit hotel room
        ApexPages.currentPage().getParameters().clear();
        ApexPages.currentPage().getParameters().put('hotelRoomId', room.Id);
        hsrce.editHotelRoom();
        hsrce.updateHotelRoomBARRate();          
        
        hsrce.cloneHotelRoom();
        
        // add two more hotel rooms 
        buildEditHotelRoom(hsrce, null, 'Standard King', null, null,
                                                'Daily', 'Daily', 'Daily', 'Other Fee Desc',
                                                '7/20/2010', '7/30/2010', '140.00', '10.00',
                                                '5.43', '10.10', '34.12','1','1','1');
        
        buildEditHotelRoom(hsrce, null, 'Standard King', null, null,
                                                null, null, null, 'Other Fee Desc',
                                                '7/20/2010', '7/30/2010', '140.00', '10.00',
                                                '', '', '','0','0','0');    
                                                
        rooms = hsrce.getPlacement().Hotel_Rooms__r;
        room = rooms[0];
        
        hsrce.setHasHotelRooms(true);
        
        test.stoptest();
         
    }
    
    
    static testMethod void testMisc()
    {
        
        hsrce.getIsBillingCompleted();
        hsrce.setBillingCompleted();
        hsrce.getIsBillingCompleted();
        hsrce.setIsBillingCompleted(true);
        hsrce.undoBillingCompleted();
        hsrce.getHasUnbilledRooms();
        hsrce.setHasUnbilledRooms(false);
        hsrce.getHasPlacement();
        hsrce.setHasPlacement(true);
        hsrce.placement.Check_Out_Date__c = Date.toDay();
        hsrce.getIsPlacementCheckedOut();
        hsrce.setIsPlacementCheckedOut(true);
        hsrce.refreshHotelRooms();
        hsrce.undoBillingCompleted();
        hsrce.getHasUnbilledRooms();
        hsrce.setHasUnbilledRooms(false);
        hsrce.getIsManagerOrDirector();                     
        hsrce.setIsManagerOrDirector(true);                    
        hsrce.getIsOperationsDirector();        
        hsrce.setIsOperationsDirector(true);        
       
    }
     
    private static void buildEditHotelRoom(HotelServiceRequestControllerExtension ce,
                                                                                Id hotelRoomId, 
                                                                                string roomType, 
                                                                                string confirmation, 
                                                                                string cancellation, 
                                                                                string parkingFeeType,
                                                                                string petFeeType,
                                                                                string otherFeeType,
                                                                                string otherFeeDesc,
                                                                                string checkIn,
                                                                                string checkOut,
                                                                                string nightlyRate,
                                                                                string itemizedTax,
                                                                                string parkingFeeAmount,
                                                                                string petFeeAmount,
                                                                                string otherFeeAmount,
                                                                                string oneTimePetFeesTaxable,
                                                                                string oneTimeParkingFeesTaxable,
                                                                                string oneTimeOtherFeesTaxable
                                                                                )
    {
        ApexPages.currentPage().getParameters().clear();
        
        if (hotelRoomId != null)
        {
            ApexPages.currentPage().getParameters().put('hotelRoomId', hotelRoomId);
        }
        
        if (roomType != null)
        {
            ApexPages.currentPage().getParameters().put('roomType', roomType);
        }
    
        if (confirmation != null)
        {
            ApexPages.currentPage().getParameters().put('confirmation', confirmation);
        }
        
        if (cancellation != null)
        {
            ApexPages.currentPage().getParameters().put('cancellation', cancellation);
        }
        
        if (parkingFeeType != null)
        {
            ApexPages.currentPage().getParameters().put('parkingFeeType', parkingFeeType);
        }
        
        if (petFeeType != null)
        {
            ApexPages.currentPage().getParameters().put('petFeeType', petFeeType);
        }
        
        if (otherFeeType != null)
        {
            ApexPages.currentPage().getParameters().put('otherFeeType', otherFeeType);
        }
        
        if (otherFeeDesc != null)
        {
            ApexPages.currentPage().getParameters().put('otherFeeDesc', otherFeeDesc);
        }
        
        if (checkIn != null)
        {
            ApexPages.currentPage().getParameters().put('checkIn', checkIn);
        }
        
        if (checkOut != null)
        {
            ApexPages.currentPage().getParameters().put('checkOut', checkOut);
        }
        
        if (nightlyRate != null)
        {
            ApexPages.currentPage().getParameters().put('nightlyRate', nightlyRate);
        }
        
        if (itemizedTax != null)
        {
            ApexPages.currentPage().getParameters().put('itemizedTax', itemizedTax);
        }
        
        if (parkingFeeAmount != null)
        {
            ApexPages.currentPage().getParameters().put('parkingFeeAmount', parkingFeeAmount);
        }
        
        if (petFeeAmount != null)
        {
            ApexPages.currentPage().getParameters().put('petFeeAmount', petFeeAmount);
        }
        
        if (otherFeeAmount != null)
        {
            ApexPages.currentPage().getParameters().put('otherFeeAmount', otherFeeAmount);
        }
        
        if (oneTimePetFeesTaxable != null)
        {
            ApexPages.currentPage().getParameters().put('oneTimePetFeesTaxable', oneTimePetFeesTaxable);
        }
        
        if (oneTimeParkingFeesTaxable != null)
        {
            ApexPages.currentPage().getParameters().put('oneTimeParkingFeesTaxable', oneTimeParkingFeesTaxable);
        }
        
        if (oneTimeOtherFeesTaxable != null)
        {
            ApexPages.currentPage().getParameters().put('oneTimeOtherFeesTaxable', oneTimeOtherFeesTaxable);
        }
        
        ce.saveHotelRoom();
        
    }
  
    private static void selectHotelSearch(string paymentType)
    {
        List<Searches__c> hotelSearches = hsrce.getHotelSearches();
        
        system.assertEquals(false, hsrce.getHasSelectedHotelSearch());
        
        ApexPages.currentPage().getParameters().clear();
        ApexPages.currentPage().getParameters().put('hotelSearchId', hotelSearches[0].Id);
        ApexPages.currentPage().getParameters().put('placementPaymentType', paymentType);
                   
        hsrce.updateSelectedHotelSearch();
        
        system.assertEquals(true, hsrce.getHasSelectedHotelSearch());
        
        Searches__c selected_search = hsrce.getSelectedHotelSearch();
        system.assertEquals(selected_search.Id, hotelSearches[0].Id);
        hsrce.updateSearchDistanceToDamagedProp();      
        hsrce.clearHotelSearch();
    }
  
    private static Contact createPolicyHolder()
    {
        Contact c = new Contact
        (
            RecordTypeId = RecordTypeHelper.policyholderContactRT(),
            FirstName = 'PolicyHolder',
            LastName = 'Contact',
            Status__c='Active',
            MailingCountry='USA',
            MailingState = 'AZ',
            MailingStreet='134 Laurel',
            MailingCity='Phoenix',
            MailingPostalCode='85011',
            Type__c='TPA',
            LeadSource='Event',
            Lead_Source_Description__c='Golf Event',
            OtherCountry='USA',
            OtherState = 'AZ',
            OtherStreet='134 Laurel',
            OtherCity='Phoenix',
            OtherPostalCode='85011');   
    
        insert c;
    
        return c;   
    }
  
    private static Contact createAdjuster()
    {
        Contact c = new Contact 
        (
            RecordTypeId = RecordTypeHelper.adjusterContactRT(),
            FirstName = 'Adj',
            LastName = 'Contact',
            Status__c='Active',
            MailingCountry='USA',
            MailingState = 'AZ',
            MailingStreet='134 Laurel',
            MailingCity='Phoenix',
            MailingPostalCode='85011',
            Type__c='TPA',
            LeadSource='Event',
            Lead_Source_Description__c='Golf Event',
            OtherCountry='USA',
            OtherState = 'AZ',
            OtherStreet='134 Laurel',
            OtherCity='Phoenix',
            OtherPostalCode='85011');    
    
        insert c;
    
        return c;
    }
  
    private static Opportunity createClaim()
    {
        
        // Insert Users
        Profile p = [SELECT Id FROM Profile WHERE Name='Operations User']; 
        User user1 = new User
                (   
                    Alias = 'opsusr',
                    Email='operationsuser@testorg.com', 
                    EmailEncodingKey='UTF-8', 
                    LastName='Testing', 
                    LanguageLocaleKey='en_US',
                    LocaleSidKey='en_US', 
                    ProfileId = p.Id, 
                    TimeZoneSidKey='America/Los_Angeles', 
                    UserName='operationsuser@crstemphousing.com');
        insert user1; 

        Opportunity opp = new Opportunity
        (                            
            Policyholder__c = ph.Id,
            Adjuster__c = adj.Id,
            Name = 'abc123',
            Initial_Service_Request__c='Hotel',
            CloseDate = Date.today(),   
            StageName = 'Submitted',
            Type_of_Loss__c = 'Mold',
            Damaged_Property_Type__c = 'Apartment',
            Damaged_Property_Address__c = '123 Big Test Lane',
            Damaged_Property_City__c = 'Phoenix',
            Damaged_Property_State__c = 'AZ',
            Damaged_Property_Zip__c = '85011',
            Damaged_Property_Country__c = 'USA', 
            Regional_Manager__c = user1.Id,
            Customer_Care_Specialist__c = user1.Id,
            Hotel_Customer_Care_Specialist__c = user1.Id);
        insert opp;
    
        return opp;
    }
  
    private static Account createHotelAccount(string hotelName)
    {
        Account ha = new Account
        (
            RecordTypeId = RecordTypeHelper.hotelAccountRT(),
            Active__c = true,
            Name = hotelName,
            BillingState='CT',
            BillingStreet='134 Laurel',
            BillingCity='Mineola',
            BillingPostalCode='11501',
            BillingCountry='USA',
            ShippingState = 'CT',
            ShippingCountry = 'USA',
            ShippingPostalCode = '11501',
            ShippingCity = 'Mineola',
            ShippingStreet = '134 Laurel',
            Fax = '6022345675');
        
        insert ha;
    
        return ha;
    }
}