src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>smagicinteract__SMSOptOut__c</fullName>
        <defaultValue>false</defaultValue>
        <label>SMS Opt Out</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Adjuster</fullName>
        <active>true</active>
        <description>All contacts that work in the Insurance Industry. Includes Company Adjusters, Independent Adjusters, Public Adjusters, Supervisors, Managers, Procurement etc.</description>
        <label>Adjuster</label>
    </recordTypes>
    <recordTypes>
        <fullName>Policyholder</fullName>
        <active>true</active>
        <description>Contacts that are a Policyholder</description>
        <label>Policyholder</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Hotel_Room__c.object
<CustomObject>
    <description>Holds the information related to a Hotel Booking.</description>
    <fields>
        <fullName>CheckOut__c</fullName>
        <label>Check-Out Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Check_In__c</fullName>
        <label>Check-In Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Estimated_Check_Out_Date__c</fullName>
        <description>The current estimated check-out date</description>
        <label>Estimated Check-Out Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Placement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Placement</label>
        <referenceTo>Placement__c</referenceTo>
        <relationshipLabel>Hotel Rooms</relationshipLabel>
        <relationshipName>Hotel_Rooms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Policyholder__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Policyholder</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Hotel Rooms</relationshipLabel>
        <relationshipName>Hotel_Rooms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Previous_Estimated_Check_Out_Date__c</fullName>
        <label>Previous Estimated Check-Out Date</label>
        <type>Date</type>
    </fields>
    <label>Hotel Room</label>
    <nameField>
        <displayFormat>Room-{00000}</displayFormat>
        <label>Hotel Room</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hotel Rooms</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Adjuster__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The adjuster must already be a contact in the system.</inlineHelpText>
        <label>Adjuster</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Adjuster</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Claims (Adjuster)</relationshipLabel>
        <relationshipName>Opportunities2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Hotel_Customer_Care_Specialist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Hotel Customer Care Specialist</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Policyholder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Policyholder</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Policyholder, Adjuster Policyholder Record Type</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Claims</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Placement__c.object
<CustomObject>
    <description>Holds information about a housing placement, when the Opportunity stage is set to Moved-In, and a policy holder moves into the temporarry housing.  Besides the detail about the duration of the placement, this object is related to Cases to track any issues related to the placement.</description>
    <fields>
        <fullName>Estimated_Check_Out_Date__c</fullName>
        <defaultValue>TODAY() + 365</defaultValue>
        <label>Estimated Check-Out Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Claim Lookup</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Placements</relationshipLabel>
        <relationshipName>Placements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ServiceRequest__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Request</label>
        <referenceTo>ServiceRequest__c</referenceTo>
        <relationshipLabel>Placements</relationshipLabel>
        <relationshipName>Placements1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Placement</label>
    <nameField>
        <label>Placement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Placements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ServiceRequest__c.object
<CustomObject>
    <description>Holds the different services that a request can include, such as: Hotel Stays, Housing requests, Furniture requests, Fair Rental Value, etc.</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Claim</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Service Requests</relationshipLabel>
        <relationshipName>Service_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ServiceRequest__c</fullName>
        <formula>Id</formula>
        <label>ServiceRequest</label>
        <type>Text</type>
    </fields>
    <label>Service Request</label>
    <nameField>
        <displayFormat>SR#-{000000}</displayFormat>
        <label>Service Request</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Requests</pluralLabel>
    <recordTypes>
        <fullName>Hotel</fullName>
        <active>true</active>
        <description>For Hotel requests</description>
        <label>Hotel</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PreCheckoutTaskCreator.cls
global class PreCheckoutTaskCreator implements Database.Batchable<sObject>, Database.Stateful 
{

	DateTime currentDate = DateTime.newInstance(System.today(), Time.newInstance(12,0,0,0));
	DateTime min72hrDate = DateTime.newInstance(System.today(), Time.newInstance(12,0,0,0));
	DateTime max72hrDate = DateTime.newInstance(System.today(), Time.newInstance(12,0,0,0));
	DateTime min24hrDate = DateTime.newInstance(System.today(), Time.newInstance(12,0,0,0));
	DateTime max24hrDate = DateTime.newInstance(System.today(), Time.newInstance(12,0,0,0));
	DateTime minShortTermDate = DateTime.newInstance(System.today(), Time.newInstance(12,0,0,0));
	String query;


	global database.queryLocator start(Database.BatchableContext BC)
    {
     	// Calculate min and max business days out from current date
    	min72hrDate = min72hrDate.AddDays(3);
		max72hrDate = max72hrDate.AddDays(3);
		min24hrDate = min24hrDate.AddDays(1);
		max24hrDate = max24hrDate.AddDays(1);
		minShortTermDate = minShortTermDate.AddDays(-2);
	
		
		if (currentDate.format('u') == '1' || currentDate.format('u') == '2')
		{
			minShortTermDate = minShortTermDate.AddDays(-2);
		}
		else
		{
			if (currentDate.format('u') == '3')
			{
				max72hrDate = max72hrDate.AddDays(2);
			}
			else
			{
				if (currentDate.format('u') == '4' || currentDate.format('u') == '5')
				{
					min72hrDate = min72hrDate.AddDays(2);
					max72hrDate = max72hrDate.AddDays(2);

					if (currentDate.format('u') == '5')
					{
						max24hrDate = max24hrDate.AddDays(2);
					}
				}				
			}
		}

  		// Get all Hotel Rooms that need a checkout task created
  		query = 'select Id,Name, Estimated_Check_Out_Date__c,Placement__r.Opportunity__r.Policyholder__c,Placement__r.Opportunity__r.Adjuster__c,Placement__r.ServiceRequest__c,' +
		        'Placement__c,Placement__r.Opportunity__r.Hotel_Customer_Care_Specialist__c,Placement__r.Opportunity__r.Account.Parent.Name,' +
			    'Placement__r.Opportunity__r.Account.Name,Placement__r.Opportunity__r.Account.BillingCity,Placement__r.Opportunity__r.Policyholder__r.Smagicinteract__SMSOptOut__c,' + 
			    'Placement__r.Opportunity__r.Policyholder__r.MobilePhone from Hotel_Room__c ' +
			    'where (CheckOut__c = null and Estimated_Check_Out_Date__c >= ' + min72hrDate.format('YYYY-MM-dd') + ' and Estimated_Check_Out_Date__c <= ' + max72hrDate.format('YYYY-MM-dd') + ' and Check_In__c < ' + currentDate.format('YYYY-MM-dd') + ') or ' +
			    '(CheckOut__c = null and Estimated_Check_Out_Date__c >= ' + min24hrDate.format('YYYY-MM-dd') + ' and Estimated_Check_Out_Date__c <= ' + max24hrDate.format('YYYY-MM-dd') + ' and ((Check_In__c >= ' + minShortTermDate.format('YYYY-MM-dd') + 
			    ' ) or (Previous_Estimated_Check_Out_Date__c >= ' + minShortTermDate.format('YYYY-MM-dd') + '))) order by placement__r.serviceRequest__c';
  		
  		system.debug(query);
  		return Database.getQueryLocator(query); 

    }
		
	global void execute(Database.BatchableContext BC, list <Hotel_Room__c> scope) 
   	{
   		Set<String> hotelRoomNames = new Set<String>();
   		List<Task> tasks = new List<Task>();
   		DateTime activityDateWithTime = DateTime.newInstance(Date.Today().year(), Date.Today().month(), Date.Today().day(), 18, 0, 0); 
   		Id old72HourTaskSR;
   		Id old24HourTaskSR;
   		   		
		
		for(Hotel_Room__c hotelRoom : scope) 
		{
			if (hotelRoom.Estimated_Check_Out_Date__c >= min72hrDate.date() && hotelRoom.Estimated_Check_Out_Date__c <= max72hrDate.date())
    		{
    			
    			if (old72HourTaskSR != hotelRoom.Placement__r.ServiceRequest__c)
    			{
	    			old72HourTaskSR = hotelRoom.Placement__r.ServiceRequest__c;

		    		if (hotelRoom.Placement__r.Opportunity__r.Account.Parent.Name != 'Liberty Mutual Insurance Headquarters' && hotelRoom.Placement__r.Opportunity__r.Account.Parent.Name != 'Safeco Insurance Company Headquarters' && hotelRoom.Placement__r.Opportunity__r.Account.Name != 'Safeco Insurance Company Headquarters' && hotelRoom.Placement__r.Opportunity__r.Account.Parent.Name != 'American Family Insurance Headquarters' ||
		    			hotelRoom.Placement__r.Opportunity__r.Account.Parent.Name == 'American Family Insurance Headquarters' && hotelRoom.Placement__r.Opportunity__r.Account.BillingCity != 'Atlanta')
		    		{
		    			// Create 72 hour policyholder follow up task
			 	    	tasks.add(TaskBuilder.x72HourPHContact(hotelRoom.Placement__c,hotelRoom.Placement__r.ServiceRequest__c,hotelRoom.Placement__r.Opportunity__r.Policyholder__c,hotelRoom.Placement__r.Opportunity__r.Hotel_Customer_Care_Specialist__c));	
			 	    }
			 	    else
			 	    {
			 	    	// Create 72 hour adjuster follow up task
			    		tasks.add(TaskBuilder.x72HourADJContact(hotelRoom.Placement__c,hotelRoom.Placement__r.ServiceRequest__c,hotelRoom.Placement__r.Opportunity__r.Policyholder__c,hotelRoom.Placement__r.Opportunity__r.Hotel_Customer_Care_Specialist__c));	
			 	    }
		 		}
		 	}
		 	else
		 	{
	 			if (old24HourTaskSR != hotelRoom.Placement__r.ServiceRequest__c)
	 			{
	 				old24HourTaskSR = hotelRoom.Placement__r.ServiceRequest__c;

		 			// Create 24 hour follow up task
					tasks.add(TaskBuilder.x24HourContact(hotelRoom.Placement__c,hotelRoom.Placement__r.ServiceRequest__c,hotelRoom.Placement__r.Opportunity__r.Policyholder__c,hotelRoom.Placement__r.Opportunity__r.Hotel_Customer_Care_Specialist__c));	
	 	    	}
		 	}
			
    		hotelRoomNames.add(hotelRoom.Name);
    	}

    	insert tasks;
    	
    	system.debug(hotelRoomNames);  
	}
	
	global void finish(Database.BatchableContext BC) 
	{
		
	}
	
}