src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Adjuster</fullName>
        <active>true</active>
        <description>All contacts that work in the Insurance Industry. Includes Company Adjusters, Independent Adjusters, Public Adjusters, Supervisors, Managers, Procurement etc.</description>
        <label>Adjuster</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Placement__c.object
<CustomObject>
    <description>Holds information about a housing placement, when the Opportunity stage is set to Moved-In, and a policy holder moves into the temporarry housing.  Besides the detail about the duration of the placement, this object is related to Cases to track any issues related to the placement.</description>
    <fields>
        <fullName>ServiceRequest__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Request</label>
        <referenceTo>ServiceRequest__c</referenceTo>
        <relationshipLabel>Placements</relationshipLabel>
        <relationshipName>Placements1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Placement</label>
    <nameField>
        <label>Placement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Placements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ServiceRequest__c.object
<CustomObject>
    <description>Holds the different services that a request can include, such as: Hotel Stays, Housing requests, Furniture requests, Fair Rental Value, etc.</description>
    <fields>
        <fullName>CRS_Hotel_Confirmation_Created_Date__c</fullName>
        <label>CRS Hotel Confirmation Created Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Cost_Benefit_Analysis_Created_Date__c</fullName>
        <label>Cost Benefit Analysis Created Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Move_In_Confirmation_Created_Date__c</fullName>
        <label>Move In Confirmation Created Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ServiceRequest__c</fullName>
        <formula>Id</formula>
        <label>ServiceRequest</label>
        <type>Text</type>
    </fields>
    <label>Service Request</label>
    <nameField>
        <displayFormat>SR#-{000000}</displayFormat>
        <label>Service Request</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Requests</pluralLabel>
    <recordTypes>
        <fullName>Hotel</fullName>
        <active>true</active>
        <description>For Hotel requests</description>
        <label>Hotel</label>
    </recordTypes>
    <recordTypes>
        <fullName>Housing</fullName>
        <active>true</active>
        <description>For Housing requests</description>
        <label>Housing</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TaskTriggerHelper.cls
/*************************************************************************************
Created By: Apostletech team
Purpose: Helper class for Trigger on Task object,
1. To create "Temporary Housing Agreement Send Document Task", "Credit Card Authorization Send Document Task", "Adjuster Confirmation Send Document Task"
    task records when Book Hotel task completed   
*************************************************************************************/
Public class TaskTriggerHelper{
    
    // After event
    // To create Send Document tasks when Book Hotel task completed
    // ***************************************** Method Start ***********************************************************
    Public static void createSendDocumnetTasks(List<Task> taskList, Map<Id,Task> oldTaskMap, Boolean isInsert)
    {
        
        List<Task> sendDocTaskList = new List<Task>();
        
        for(Task t : taskList)
        {
            if(t.Status == 'Completed' && t.Subject == 'Book Hotel' && (isInsert || (!isInsert && t.Status != oldTaskMap.get(t.Id).Status)))
            {
                sendDocTaskList.add(TaskBuilder.ccAuth(t.Placement__c,t.Service_Request__c,t.WhoId,t.OwnerId));    
                sendDocTaskList.add(TaskBuilder.adjConfirmation(t.Placement__c,t.Service_Request__c,t.WhoId,t.OwnerId));    
            }
        }
         
         if(!sendDocTaskList.isEmpty()){
             insert sendDocTaskList;
         }
         
    }
    // ***************************************** Method End ***********************************************************
    
        
    // To stop Send document tasks duplicate creation
    private static boolean runSendDocuments = true;
    public static boolean runOnceSendDocuments(){
        if(runSendDocuments){
             runSendDocuments=false;
             return true;
        }else{
            return runSendDocuments;
        }
    }

    Public static void create72HourADJContactTask(List<Task> taskList, Map<Id,Task> oldTaskMap)
    {
        
        List<Task> x72HourADJContactTasks = new List<Task>();
       
        for(Task task : taskList)
        {
            if (task.RecordTypeId == RecordTypeHelper.x72HourPHContactTaskRT() && task.Status != oldTaskMap.get(task.Id).Status && task.Status == 'Completed')
            {
    
                x72HourADJContactTasks.add(TaskBuilder.x72HourADJContact(task.Placement__c,task.WhatId,task.WhoId,task.OwnerId));
            }
        }

        insert x72HourADJContactTasks;
    }    
     // We have copied this trigger from PopulateDocumentDates after insert
      Public Static void PopulateDocumentDates(list<Task> TaskRecords)
      {
          Date cutOffDate = Date.newInstance(2015,10,28);
        Set<ID> TaskID = new Set<ID>();
        for(Task task : TaskRecords){
            string whatIdVal = task.whatId;
            if(whatIdVal.startsWith('a0P'))
                TaskID.add(task.WhatId);
        }
        Map<Id,ServiceRequest__c> SrMap = New Map<Id,ServiceRequest__c>([select id,CRS_Hotel_Confirmation_Created_Date__c,Cost_Benefit_Analysis_Created_Date__c,Move_In_Confirmation_Created_Date__c,CreatedDate from serviceRequest__c where Id IN: TaskID]);
        for (Task task : TaskRecords)    
        {
            if (task.subject == 'HotelConfirmation Generated')
            {
                //ServiceRequest__c serviceRequest = [select CRS_Hotel_Confirmation_Created_Date__c,CreatedDate from serviceRequest__c where Id =: task.WhatId];
                //if (serviceRequest.CRS_Hotel_Confirmation_Created_Date__c == null && Date.newInstance(serviceRequest.CreatedDate.year(), serviceRequest.CreatedDate.month(), serviceRequest.CreatedDate.day()) >= cutOffDate)
                if (SrMap.get(task.whatid).CRS_Hotel_Confirmation_Created_Date__c == null && SrMap.get(task.whatid).CreatedDate >= cutOffDate)
                {
                    SrMap.get(task.whatid).CRS_Hotel_Confirmation_Created_Date__c = Datetime.now();
                    //update serviceRequest; 
                }
            }
            else if (task.subject == 'Liberty Mutual Cost Benefit Analysis')
            {
                //ServiceRequest__c serviceRequest = [select Cost_Benefit_Analysis_Created_Date__c,CreatedDate from serviceRequest__c where Id =: task.WhatId];
                //if (serviceRequest.Cost_Benefit_Analysis_Created_Date__c == null && Date.newInstance(serviceRequest.CreatedDate.year(), serviceRequest.CreatedDate.month(), serviceRequest.CreatedDate.day()) >= cutOffDate)
                if(SrMap.get(task.whatid).Cost_Benefit_Analysis_Created_Date__c == null && SrMap.get(task.whatid).CreatedDate >= cutOffDate)
                {
                    SrMap.get(task.whatid).Cost_Benefit_Analysis_Created_Date__c = Datetime.now();
                }
            }
            else if (task.subject == 'MoveInConfirmation Generated')
            {
                //ServiceRequest__c serviceRequest = [select Cost_Benefit_Analysis_Created_Date__c,CreatedDate from serviceRequest__c where Id =: task.WhatId];
                //if (serviceRequest.Cost_Benefit_Analysis_Created_Date__c == null && Date.newInstance(serviceRequest.CreatedDate.year(), serviceRequest.CreatedDate.month(), serviceRequest.CreatedDate.day()) >= cutOffDate)
                if(SrMap.get(task.whatid).Move_In_Confirmation_Created_Date__c == null && SrMap.get(task.whatid).CreatedDate >= cutOffDate)
                {
                    SrMap.get(task.whatid).Move_In_Confirmation_Created_Date__c = Datetime.now();
                }
            }
        }  
        if(SrMap.size()>0)
            update SrMap.values();
      }

     // To stop 72 hour adj contact tasks duplicate creation
    private static boolean runCreate72HourADJContactTask = true;
    public static boolean runOnceCreate72HourADJContactTask(){
        if(runCreate72HourADJContactTask){
             runCreate72HourADJContactTask=false;
             return true;
        }else{
            return runCreate72HourADJContactTask;
        }
    }   
}