src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Active - potential of doing business
Inactive - not able to do business
No Longer with Company</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>No Longer with Company</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Adjuster</fullName>
        <active>true</active>
        <description>All contacts that work in the Insurance Industry. Includes Company Adjusters, Independent Adjusters, Public Adjusters, Supervisors, Managers, Procurement etc.</description>
        <label>Adjuster</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Adjuster__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The adjuster must already be a contact in the system.</inlineHelpText>
        <label>Adjuster</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Adjuster</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Claims (Adjuster)</relationshipLabel>
        <relationshipName>Opportunities2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Hotel_Only__c</fullName>
        <label>Hotel Only</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>True</fullName>
                </value>
                <value>
                    <fullName>False</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Claim</fullName>
        <active>true</active>
        <businessProcess>Standard Request</businessProcess>
        <label>Claim</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ServiceRequest__c.object
<CustomObject>
    <description>Holds the different services that a request can include, such as: Hotel Stays, Housing requests, Furniture requests, Fair Rental Value, etc.</description>
    <fields>
        <fullName>Hotel_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Hotel Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Service Requests</relationshipLabel>
        <relationshipName>Service_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Claim</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Service Requests</relationshipLabel>
        <relationshipName>Service_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ServiceRequest__c</fullName>
        <formula>Id</formula>
        <label>ServiceRequest</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Request</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Searching</fullName>
                </value>
                <value>
                    <fullName>Pending Confirmation</fullName>
                </value>
                <value>
                    <fullName>Moved-In/Closed</fullName>
                </value>
                <value>
                    <fullName>Finders Fee</fullName>
                </value>
                <value>
                    <fullName>Hold</fullName>
                </value>
                <value>
                    <fullName>Checked-In/Closed</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Lost Opportunity</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Service Request</label>
    <nameField>
        <displayFormat>SR#-{000000}</displayFormat>
        <label>Service Request</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Requests</pluralLabel>
    <recordTypes>
        <fullName>Hotel</fullName>
        <active>true</active>
        <description>For Hotel requests</description>
        <label>Hotel</label>
    </recordTypes>
    <recordTypes>
        <fullName>Housing</fullName>
        <active>true</active>
        <description>For Housing requests</description>
        <label>Housing</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/HotelOnlyUpdater.cls
global class HotelOnlyUpdater implements Database.Batchable<sObject>
{

	Public String query { get; set;}  
			  
    global database.queryLocator start(Database.BatchableContext BC)
    {
  		return database.getQueryLocator(query); 
    }
    
    global void execute(Database.BatchableContext BC, list <ServiceRequest__c> scope) 
    {
    	Set<Id> housingClaimIds = new Set<Id>();
    	Set<Id> hotelClaimIds = new Set<Id>();
    	Set<Id> allClaimIds = new Set<Id>();
    	    	
    	// loop through all the service requests 
	    for(ServiceRequest__c serviceRequest : scope) 
	    {
	    	if (serviceRequest.RecordType.DeveloperName == 'Housing' && serviceRequest.Status__c <> 'Lost Opportunity')
	    	{
	    		housingClaimIds.add(serviceRequest.opportunity__c);
	    	}
	    	else
	    	{
	    		if (serviceRequest.RecordType.DeveloperName == 'Hotel' && serviceRequest.Status__c <> 'Lost Opportunity')
	    		{
	    			hotelClaimIds.add(serviceRequest.opportunity__c);
	    		}
	       	}
	    	allClaimIds.add(serviceRequest.Opportunity__c);
	    }
	    
	    List<Opportunity> claims = [select id, Hotel_Only__c, (select id from Service_Requests__r where status__c <> 'Lost Opportunity' and RecordType.DeveloperName in ('Housing','Hotel')) from opportunity where Account.Owner.IsActive = true and Adjuster__r.RecordType.DeveloperName = 'Adjuster' and Id in: allClaimIds];
	    List<Opportunity> changedClaims = new List<Opportunity>();
	    
	    for (Opportunity claim : claims)
	    {
	    	if (housingClaimIds.contains(claim.Id))
	    	{
	    		if (claim.Hotel_Only__c != 'False')
	    		{
	    			claim.Hotel_Only__c = 'False';
	    			changedClaims.add(claim);
	    		}
	       	}
	       	else
	       	{
	       		if (hotelClaimIds.contains(claim.Id))
	    		{
		       		if (claim.Hotel_Only__c != 'True')
		       		{
		       			claim.Hotel_Only__c = 'True';
		       			changedClaims.add(claim);
		       		}
		       	}
		       	else
		       	{
		       		if (claim.Hotel_Only__c != null && claim.Service_Requests__r.size() == 0)
			       	{
			       		system.debug('We got here');
			       		claim.Hotel_Only__c = null;
			       		changedClaims.add(claim);
			       	}
		       	}
	       	}
	    }
        update (changedClaims);
    }
    
    global void finish(Database.BatchableContext ctx)
    {

    }    
}