src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Assigned_To_Last_Deal__c</fullName>
        <label>Assigned To Last Deal</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Called_In_By_Last_Deal__c</fullName>
        <label>Called In By Last Deal</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Lead_Source_Description__c</fullName>
        <label>Lead Source Description</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>LeadSource</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>ACE Claims</fullName>
                </value>
                <value>
                    <fullName>AICA Education</fullName>
                </value>
                <value>
                    <fullName>All-Industry Day</fullName>
                </value>
                <value>
                    <fullName>Association Meeting</fullName>
                </value>
                <value>
                    <fullName>CCC</fullName>
                </value>
                <value>
                    <fullName>CCNC</fullName>
                </value>
                <value>
                    <fullName>FAPIA</fullName>
                </value>
                <value>
                    <fullName>Golf Event</fullName>
                </value>
                <value>
                    <fullName>Kentucky Claims</fullName>
                </value>
                <value>
                    <fullName>NAIIA</fullName>
                </value>
                <value>
                    <fullName>NAPIA</fullName>
                </value>
                <value>
                    <fullName>NLA Trade Fair</fullName>
                </value>
                <value>
                    <fullName>OCAA Symposium</fullName>
                </value>
                <value>
                    <fullName>PLRB Claims</fullName>
                </value>
                <value>
                    <fullName>PLRB Regional</fullName>
                </value>
                <value>
                    <fullName>Social Event</fullName>
                </value>
                <value>
                    <fullName>Unit Meeting</fullName>
                </value>
                <value>
                    <fullName>Windstorm</fullName>
                </value>
                <value>
                    <fullName>Disaster Assistance Center</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Active - potential of doing business
Inactive - not able to do business
No Longer with Company</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>No Longer with Company</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Agent</fullName>
                </value>
                <value>
                    <fullName>Catastrophe</fullName>
                </value>
                <value>
                    <fullName>Company</fullName>
                </value>
                <value>
                    <fullName>Contractor</fullName>
                </value>
                <value>
                    <fullName>FEMA</fullName>
                </value>
                <value>
                    <fullName>Independent</fullName>
                </value>
                <value>
                    <fullName>Landlord</fullName>
                </value>
                <value>
                    <fullName>Lawyer</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Policyholder</fullName>
                </value>
                <value>
                    <fullName>Procurement</fullName>
                </value>
                <value>
                    <fullName>Public</fullName>
                </value>
                <value>
                    <fullName>Restoration</fullName>
                </value>
                <value>
                    <fullName>Supervisor</fullName>
                </value>
                <value>
                    <fullName>TPA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Adjuster</fullName>
        <active>true</active>
        <description>All contacts that work in the Insurance Industry. Includes Company Adjusters, Independent Adjusters, Public Adjusters, Supervisors, Managers, Procurement etc.</description>
        <label>Adjuster</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/AdjusterFollowupTaskBatchScheduleTest.cls
@isTest
private class AdjusterFollowupTaskBatchScheduleTest{

    static testMethod void testAdjusterFollowupTask(){
    
         List<Contact> contList = new List<Contact>();
         
         
         contList .add(new Contact (
                        RecordTypeId = RecordTypeHelper.adjusterContactRT(),
                        FirstName = 'Adj1',
                        LastName = 'Contact1',
                        Status__c='Active',
                        MailingCountry='USA',
                        MailingState = 'AZ',
                        MailingStreet='134 Laurel',
                        MailingCity='Phoenix',
                        MailingPostalCode='85011',
                        Type__c='TPA',
                        LeadSource='Event',
                        Lead_Source_Description__c='Golf Event',
                        OtherCountry='USA',
                        OtherState = 'AZ',
                        OtherStreet='134 Laurel',
                        OtherCity='Phoenix',
                        OtherPostalCode='85011',
                        Called_In_By_Last_Deal__c = Date.toDay() - 29,
                        Assigned_To_Last_Deal__c = Date.toDay() - 29
                        )
                      );  
                      
          contList .add(new Contact (
                        RecordTypeId = RecordTypeHelper.adjusterContactRT(),
                        FirstName = 'Adj2',
                        LastName = 'Contact2',
                        Status__c='Active',
                        MailingCountry='USA',
                        MailingState = 'AZ',
                        MailingStreet='134 Laurel',
                        MailingCity='Phoenix',
                        MailingPostalCode='85011',
                        Type__c='TPA',
                        LeadSource='Event',
                        Lead_Source_Description__c='Golf Event',
                        OtherCountry='USA',
                        OtherState = 'AZ',
                        OtherStreet='134 Laurel',
                        OtherCity='Phoenix',
                        OtherPostalCode='85011',
                        Called_In_By_Last_Deal__c = Date.toDay() - 59,
                        Assigned_To_Last_Deal__c = Date.toDay() - 59
                        )
                      );                
        
            
          contList .add(new Contact (
                        RecordTypeId = RecordTypeHelper.adjusterContactRT(),
                        FirstName = 'Adj3',
                        LastName = 'Contact3',
                        Status__c='Active',
                        MailingCountry='USA',
                        MailingState = 'AZ',
                        MailingStreet='134 Laurel',
                        MailingCity='Phoenix',
                        MailingPostalCode='85011',
                        Type__c='TPA',
                        LeadSource='Event',
                        Lead_Source_Description__c='Golf Event',
                        OtherCountry='USA',
                        OtherState = 'AZ',
                        OtherStreet='134 Laurel',
                        OtherCity='Phoenix',
                        OtherPostalCode='85011',
                        Called_In_By_Last_Deal__c = Date.toDay() - 89,
                        Assigned_To_Last_Deal__c = Date.toDay() - 89
                        )
                      ); 
          
          contList .add(new Contact (
                        RecordTypeId = RecordTypeHelper.adjusterContactRT(),
                        FirstName = 'Adj3',
                        LastName = 'Contact3',
                        Status__c='Active',
                        MailingCountry='USA',
                        MailingState = 'AZ',
                        MailingStreet='134 Laurel',
                        MailingCity='Phoenix',
                        MailingPostalCode='85011',
                        Type__c='TPA',
                        LeadSource='Event',
                        Lead_Source_Description__c='Golf Event',
                        OtherCountry='USA',
                        OtherState = 'AZ',
                        OtherStreet='134 Laurel',
                        OtherCity='Phoenix',
                        OtherPostalCode='85011',
                        Called_In_By_Last_Deal__c = Date.toDay() - 181,
                        Assigned_To_Last_Deal__c = Date.toDay() - 181
                        )
                      ); 
                      
          insert  contList;
          
          AdjusterFollowupTaskBatchSchedule sh1 = new AdjusterFollowupTaskBatchSchedule();
          String sch = '0 0 23 * * ?'; system.schedule('Test adjuster tasks', sch, sh1); 
          
          Database.executeBatch(new AdjusterFollowupTaskBatch());
                  
    } 
    
}