src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Claims_Document_Fax__c</fullName>
        <label>Claims Document Fax</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Lead_Source_Description__c</fullName>
        <label>Lead Source Description</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>LeadSource</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>ACE Claims</fullName>
                </value>
                <value>
                    <fullName>AICA Education</fullName>
                </value>
                <value>
                    <fullName>All-Industry Day</fullName>
                </value>
                <value>
                    <fullName>Association Meeting</fullName>
                </value>
                <value>
                    <fullName>CCC</fullName>
                </value>
                <value>
                    <fullName>CCNC</fullName>
                </value>
                <value>
                    <fullName>FAPIA</fullName>
                </value>
                <value>
                    <fullName>Golf Event</fullName>
                </value>
                <value>
                    <fullName>Kentucky Claims</fullName>
                </value>
                <value>
                    <fullName>NAIIA</fullName>
                </value>
                <value>
                    <fullName>NAPIA</fullName>
                </value>
                <value>
                    <fullName>NLA Trade Fair</fullName>
                </value>
                <value>
                    <fullName>OCAA Symposium</fullName>
                </value>
                <value>
                    <fullName>PLRB Claims</fullName>
                </value>
                <value>
                    <fullName>PLRB Regional</fullName>
                </value>
                <value>
                    <fullName>Social Event</fullName>
                </value>
                <value>
                    <fullName>Unit Meeting</fullName>
                </value>
                <value>
                    <fullName>Windstorm</fullName>
                </value>
                <value>
                    <fullName>Disaster Assistance Center</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Active - potential of doing business
Inactive - not able to do business
No Longer with Company</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>No Longer with Company</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Agent</fullName>
                </value>
                <value>
                    <fullName>Catastrophe</fullName>
                </value>
                <value>
                    <fullName>Company</fullName>
                </value>
                <value>
                    <fullName>Contractor</fullName>
                </value>
                <value>
                    <fullName>FEMA</fullName>
                </value>
                <value>
                    <fullName>Independent</fullName>
                </value>
                <value>
                    <fullName>Landlord</fullName>
                </value>
                <value>
                    <fullName>Lawyer</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Policyholder</fullName>
                </value>
                <value>
                    <fullName>Procurement</fullName>
                </value>
                <value>
                    <fullName>Public</fullName>
                </value>
                <value>
                    <fullName>Restoration</fullName>
                </value>
                <value>
                    <fullName>Supervisor</fullName>
                </value>
                <value>
                    <fullName>TPA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Policyholder</fullName>
        <active>true</active>
        <description>Contacts that are a Policyholder</description>
        <label>Policyholder</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Adjuster__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The adjuster must already be a contact in the system.</inlineHelpText>
        <label>Adjuster</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Adjuster</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Claims (Adjuster)</relationshipLabel>
        <relationshipName>Opportunities2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Damaged_Property_Address__c</fullName>
        <label>Damaged Property Address</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Damaged_Property_City__c</fullName>
        <label>Damaged Property City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Damaged_Property_Type__c</fullName>
        <label>Damaged Property Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Apartment</fullName>
                </value>
                <value>
                    <fullName>Condo</fullName>
                </value>
                <value>
                    <fullName>House</fullName>
                </value>
                <value>
                    <fullName>Mobile Home</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Townhouse</fullName>
                </value>
                <value>
                    <fullName>Travel Trailer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Initial_Service_Request__c</fullName>
        <label>Initial Service Request</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Housing</fullName>
                </value>
                <value>
                    <fullName>Hotel</fullName>
                </value>
                <value>
                    <fullName>FRV</fullName>
                </value>
                <value>
                    <fullName>Furniture Only</fullName>
                </value>
                <value>
                    <fullName>Unfurnished</fullName>
                </value>
                <value>
                    <fullName>Trailer-Mobile Home</fullName>
                </value>
                <value>
                    <fullName>Commercial</fullName>
                </value>
                <value>
                    <fullName>Finders Fees</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Policyholder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Policyholder</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Policyholder, Adjuster Policyholder Record Type</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Claims</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type_of_Loss__c</fullName>
        <label>Type of Loss</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CAT</fullName>
                </value>
                <value>
                    <fullName>Fire</fullName>
                </value>
                <value>
                    <fullName>Mold</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Tornado</fullName>
                </value>
                <value>
                    <fullName>Water</fullName>
                </value>
                <value>
                    <fullName>Wind</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ServiceRequest__c.object
<CustomObject>
    <description>Holds the different services that a request can include, such as: Hotel Stays, Housing requests, Furniture requests, Fair Rental Value, etc.</description>
    <fields>
        <fullName>Damaged_Property_Address__c</fullName>
        <formula>Opportunity__r.Damaged_Property_Address__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Damaged Property Address</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Damaged_Property_City__c</fullName>
        <formula>Opportunity__r.Damaged_Property_City__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Damaged Property City</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Damaged_Property_Type__c</fullName>
        <formula>CASE( Opportunity__r.Damaged_Property_Type__c, &quot;House&quot; , &quot;House&quot; , &quot;Mobile Home&quot; , &quot;Mobile Home&quot; , &quot;Travel Trailer&quot; , &quot;Travel Trailer&quot; , &quot;Condo&quot; , &quot;Condo&quot; , &quot;Apartment&quot; , &quot;Apartment&quot; , &quot;Townhouse&quot; , &quot;Townhouse&quot; , &quot;Other&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Damaged Property Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Request</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Searching</fullName>
                </value>
                <value>
                    <fullName>Pending Confirmation</fullName>
                </value>
                <value>
                    <fullName>Moved-In/Closed</fullName>
                </value>
                <value>
                    <fullName>Finders Fee</fullName>
                </value>
                <value>
                    <fullName>Hold</fullName>
                </value>
                <value>
                    <fullName>Checked-In/Closed</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Lost Opportunity</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type_of_Loss__c</fullName>
        <formula>CASE (Opportunity__r.Type_of_Loss__c, &apos;Mold&apos;, &apos;Mold&apos;, &apos;Fire&apos;, &apos;Fire&apos;, &apos;Tornado&apos;, &apos;Tornado&apos;, &apos;Water&apos;, &apos;Water&apos;,&apos;Wind&apos;, &apos;Wind&apos;, &apos;CAT&apos; , &apos;CAT&apos; , &apos;Other&apos;)</formula>
        <label>Type of Loss</label>
        <type>Text</type>
    </fields>
    <label>Service Request</label>
    <nameField>
        <displayFormat>SR#-{000000}</displayFormat>
        <label>Service Request</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Requests</pluralLabel>
    <recordTypes>
        <fullName>Hotel</fullName>
        <active>true</active>
        <description>For Hotel requests</description>
        <label>Hotel</label>
    </recordTypes>
    <recordTypes>
        <fullName>Housing</fullName>
        <active>true</active>
        <description>For Housing requests</description>
        <label>Housing</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/THADocumentPreviewController_TC.cls
@isTest
private class THADocumentPreviewController_TC{
    static testMethod void THADocumnetPreviewTest(){
        
               
        Contact c = new Contact
        (
            RecordTypeId = RecordTypeHelper.policyholderContactRT(),
            FirstName = 'PolicyHolder',
            LastName = 'Contact',
            Status__c='Active',
            MailingCountry='USA',
            MailingState = 'AZ',
            MailingStreet='134 Laurel',
            MailingCity='Phoenix',
            MailingPostalCode='85011',
            Type__c='TPA',
            LeadSource='Event',
            Lead_Source_Description__c='Golf Event',
            OtherCountry='USA',
            OtherState = 'AZ',
            OtherStreet='134 Laurel',
            OtherCity='Phoenix',
            OtherPostalCode='85011',
            Fax = '12121212',
            Claims_Document_Fax__c = '123456789');   
    
        insert c;
        
        
        Contact adj = new Contact 
        (
            RecordTypeId = RecordTypeHelper.adjusterContactRT(),
            FirstName = 'Adj',
            LastName = 'Contact',
            Status__c='Active',
            MailingCountry='USA',
            MailingState = 'AZ',
            MailingStreet='134 Laurel',
            MailingCity='Phoenix',
            MailingPostalCode='85011',
            Type__c='TPA',
            LeadSource='Event',
            Lead_Source_Description__c='Golf Event',
            OtherCountry='USA',
            OtherState = 'AZ',
            OtherStreet='134 Laurel',
            OtherCity='Phoenix',
            OtherPostalCode='85011');    
    
        insert adj;
        
        Opportunity opp = new Opportunity
        (            
            Policyholder__c = c.Id,
            Adjuster__c = adj.Id,
            Name = 'abc123',
            Initial_Service_Request__c='Hotel',
            CloseDate = Date.today(),   
            StageName = 'Submitted',
            Type_of_Loss__c = 'Mold',
            Damaged_Property_Type__c = 'Apartment',
            Damaged_Property_Address__c = '123 Big Test Lane',
            Damaged_Property_City__c = 'Phoenix',
            Damaged_Property_State__c = 'AZ',
            Damaged_Property_Zip__c = '85011',
            Damaged_Property_Country__c = 'USA',
            Regional_Manager__c = userinfo.getuserid(),
            Customer_Care_Specialist__c = userinfo.getuserid(),
            Hotel_Customer_Care_Specialist__c = userinfo.getuserid());  
        insert opp;
        
        ServiceRequest__c sr=new ServiceRequest__c( 
            Opportunity__c=opp.Id,            
            Status__c= 'Request',
            Hold__c=false,
            Initial_Contact_Date__c=System.Today(),
            Initial_SR_being_worked_by__c=userinfo.getuserid(),
            Task_Attempts__c='Attempt-2',                    
            HotelSearch_BookHotel__c=true,
            CreatedDate=System.Today(),
            RecordTypeId = Schema.SObjectType.ServiceRequest__c.getRecordTypeInfosByName().get('Hotel').getRecordTypeId());    
        insert sr;
          Task newTask = new Task(subject='Send Temporary Housing Agreement(THA)', whatId = opp.id);
        insert newTask;
             
        ApexPages.currentPage().getParameters().put('reqId',opp.id);
        //ApexPages.currentPage().getParameters().put('reqId', sr.id);
        ApexPages.currentPage().getParameters().put('taskId',newTask.id);
        ApexPages.currentPage().getParameters().put('lang', 'English');
        THADocumentPreviewController clsRef = new THADocumentPreviewController();
         clsRef.oppId = '0064D000003AVQ8';
         clsRef.faxNumber = '00063725178';
        ApexPages.currentPage().getParameters().put('claimId',opp.id);
        CRSAggrementFormController CQ = new CRSAggrementFormController();
        //CQ.oppId = '0064D000003AVQ8';
        clsRef.sendFax();
        clsRef.cancel();
    }
}