src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Adjuster</fullName>
        <active>true</active>
        <description>All contacts that work in the Insurance Industry. Includes Company Adjusters, Independent Adjusters, Public Adjusters, Supervisors, Managers, Procurement etc.</description>
        <label>Adjuster</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Customer_Care_Specialist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Care Specialist</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Damaged_Property_Address__c</fullName>
        <label>Damaged Property Address</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Damaged_Property_City__c</fullName>
        <label>Damaged Property City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Damaged_Property_Country__c</fullName>
        <label>Damaged Property Country</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Damaged_Property_State__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>USA</fullName>
                </value>
                <value>
                    <fullName>CAN</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Damaged_Property_State__c</fullName>
        <label>Damaged Property State/Province</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DC</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
                <value>
                    <fullName>MN</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
                <value>
                    <fullName>MS</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
                <value>
                    <fullName>NC</fullName>
                </value>
                <value>
                    <fullName>ND</fullName>
                </value>
                <value>
                    <fullName>NE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Damaged_Property_Type__c</fullName>
        <label>Damaged Property Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Apartment</fullName>
                </value>
                <value>
                    <fullName>Condo</fullName>
                </value>
                <value>
                    <fullName>House</fullName>
                </value>
                <value>
                    <fullName>Mobile Home</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Townhouse</fullName>
                </value>
                <value>
                    <fullName>Travel Trailer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Damaged_Property_Zip__c</fullName>
        <label>Damaged Property Zip/Postal Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Hotel_Customer_Care_Specialist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Hotel Customer Care Specialist</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Initial_Service_Request__c</fullName>
        <label>Initial Service Request</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Housing</fullName>
                </value>
                <value>
                    <fullName>Hotel</fullName>
                </value>
                <value>
                    <fullName>FRV</fullName>
                </value>
                <value>
                    <fullName>Furniture Only</fullName>
                </value>
                <value>
                    <fullName>Unfurnished</fullName>
                </value>
                <value>
                    <fullName>Trailer-Mobile Home</fullName>
                </value>
                <value>
                    <fullName>Commercial</fullName>
                </value>
                <value>
                    <fullName>Finders Fees</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Policy_Type__c</fullName>
        <label>Policy Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Commercial</fullName>
                </value>
                <value>
                    <fullName>Condo</fullName>
                </value>
                <value>
                    <fullName>Homeowner</fullName>
                </value>
                <value>
                    <fullName>Renters</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Regional_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Relationship Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type_of_Loss__c</fullName>
        <label>Type of Loss</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CAT</fullName>
                </value>
                <value>
                    <fullName>Fire</fullName>
                </value>
                <value>
                    <fullName>Mold</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Tornado</fullName>
                </value>
                <value>
                    <fullName>Water</fullName>
                </value>
                <value>
                    <fullName>Wind</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/TriggerControlSetting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Name hold the trigger Name which we need to control without activating or de-activating the trigger from Object UI.</description>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsAfter__c</fullName>
        <defaultValue>true</defaultValue>
        <label>IsAfter</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsBefore__c</fullName>
        <defaultValue>true</defaultValue>
        <label>IsBefore</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsDelete__c</fullName>
        <defaultValue>true</defaultValue>
        <label>IsDelete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsInsert__c</fullName>
        <defaultValue>true</defaultValue>
        <label>IsInsert</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsUpdate__c</fullName>
        <defaultValue>true</defaultValue>
        <label>IsUpdate</label>
        <type>Checkbox</type>
    </fields>
    <label>Trigger Control Setting</label>
</CustomObject>

src/classes/EntityFactory.cls
public with sharing class EntityFactory {
    
    Public static void createTriggerControlCustomSetting(String trigName){
        insert new TriggerControlSetting__c(Name=trigName,isActive__c=true,isBefore__c=true,isAfter__c=true,isInsert__c=true, isUpdate__c=true,isDelete__c=true); 
    }
    
    public static Opportunity createHousingClaim(string name) {
        return new Opportunity(Damaged_Property_Zip__c = '12345', 
                               Damaged_Property_Type__c = 'House',
                               Damaged_Property_State__c = 'AZ', 
                               Damaged_Property_Country__c = 'USA', 
                               Damaged_Property_City__c = 'Phoenixt',
                               Damaged_Property_Address__c = '100 Test St.', 
                               Policy_Type__c = 'Homeowner',
                               Type_of_Loss__c = 'Fire', 
                               StageName = 'Submitted', 
                               Initial_Service_Request__c = 'Housing', 
                               CloseDate = Date.today(),
                               Regional_Manager__c = userinfo.getuserid(),
                               Customer_Care_Specialist__c = userinfo.getuserid(),
                               Hotel_Customer_Care_Specialist__c = userinfo.getuserid());
    }

    public static Opportunity createHotelClaim(string name) {
        return new Opportunity(Damaged_Property_Zip__c = '12345', 
                               Damaged_Property_Type__c = 'House',
                               Damaged_Property_State__c = 'AZ', 
                               Damaged_Property_Country__c = 'USA',
                               Damaged_Property_City__c = 'Phoenixt',
                               Damaged_Property_Address__c = '100 Test St.', 
                               Policy_Type__c = 'Homeowner',
                               Type_of_Loss__c = 'Fire', 
                               StageName = 'Submitted', 
                               Initial_Service_Request__c = 'Hotel', 
                               CloseDate = Date.today(),
                               Regional_Manager__c = userinfo.getuserid(),
                               Customer_Care_Specialist__c = userinfo.getuserid(),
                               Hotel_Customer_Care_Specialist__c = userinfo.getuserid());
    }

    public static Opportunity createFRVClaim(string name) {
        return new Opportunity(Damaged_Property_Zip__c = '12345', 
                               Damaged_Property_Type__c = 'House',
                               Damaged_Property_State__c = 'AZ', 
                               Damaged_Property_Country__c = 'USA', 
                               Damaged_Property_City__c = 'Phoenixt',
                               Damaged_Property_Address__c = '100 Test St.', 
                               Policy_Type__c = 'Homeowner',
                               Type_of_Loss__c = 'Fire', 
                               StageName = 'Submitted', 
                               Initial_Service_Request__c = 'FRV', 
                               CloseDate = Date.today(),
                               Regional_Manager__c = userinfo.getuserid(),
                               Customer_Care_Specialist__c = userinfo.getuserid(),
                               Hotel_Customer_Care_Specialist__c = userinfo.getuserid());
    }

    public static Opportunity createFindersFeesClaim(string name) {
        return new Opportunity(Damaged_Property_Zip__c = '12345', 
                               Damaged_Property_Type__c = 'House',
                               Damaged_Property_State__c = 'AZ', 
                               Damaged_Property_Country__c = 'USA', 
                               Damaged_Property_City__c = 'Phoenixt',
                               Damaged_Property_Address__c = '100 Test St.', 
                               Policy_Type__c = 'Homeowner',
                               Type_of_Loss__c = 'Fire', 
                               StageName = 'Submitted', 
                               Initial_Service_Request__c = 'Finders Fees', 
                               CloseDate = Date.today(),
                               Regional_Manager__c = userinfo.getuserid(),
                               Customer_Care_Specialist__c = userinfo.getuserid(),
                               Hotel_Customer_Care_Specialist__c = userinfo.getuserid());
    }
    
    public static Account insertInsuranceCompany(string name) {
        Account account = new Account(Name = name, RecordTypeId = RecordTypeHelper.insuranceCompanyAccountRT(), Type = 'Insurance Company');
        insert account;
        return account;
    }
    
    public static Contact insertAdjuster(string firstName, string lastName, Account insuranceCompany) {
        Contact adjuster = new Contact(FirstName = firstName, LastName = lastName, RecordTypeId = RecordTypeHelper.adjusterContactRT(), AccountId = insuranceCompany.Id);
        insert adjuster;
        return adjuster;
    }
    
    public static Contact createPolicyholder(string policyholderFirstName, string policyholderLastName) {
        return new Contact(FirstName = policyholderFirstName, LastName = policyholderLastName, RecordTypeId = RecordTypeHelper.policyholderContactRT()); 
    }
    
    public static Lead createLead(string leadFirstName, string leadLastName, string leadCompanyName) {
        return new Lead(FirstName = leadFirstName, LastName = leadLastName, Company = leadCompanyName, LeadSource = 'Event' ); 
    }
}