src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Other_Source__c</fullName>
        <label>Other Source</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Refered_By__c</fullName>
        <label>Refered By</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Active - potential of doing business
Inactive - not able to do business
No Longer with Company</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>No Longer with Company</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Policyholder</fullName>
        <active>true</active>
        <description>Contacts that are a Policyholder</description>
        <label>Policyholder</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Other_Source__c</fullName>
        <label>Other Source</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Refered_By__c</fullName>
        <label>Refered By</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Adjuster__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The adjuster must already be a contact in the system.</inlineHelpText>
        <label>Adjuster</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Adjuster</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Claims (Adjuster)</relationshipLabel>
        <relationshipName>Opportunities2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Area_Specialist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Residence Specialist</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Care_Specialist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Care Specialist</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Hotel_Customer_Care_Specialist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Hotel Customer Care Specialist</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Housing_Coordinator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Residence Coordinator</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Initial_Service_Request__c</fullName>
        <label>Initial Service Request</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Housing</fullName>
                </value>
                <value>
                    <fullName>Hotel</fullName>
                </value>
                <value>
                    <fullName>FRV</fullName>
                </value>
                <value>
                    <fullName>Furniture Only</fullName>
                </value>
                <value>
                    <fullName>Unfurnished</fullName>
                </value>
                <value>
                    <fullName>Trailer-Mobile Home</fullName>
                </value>
                <value>
                    <fullName>Commercial</fullName>
                </value>
                <value>
                    <fullName>Finders Fees</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Policyholder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Policyholder</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Policyholder, Adjuster Policyholder Record Type</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Claims</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Regional_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Relationship Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities4</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Claim</fullName>
        <active>true</active>
        <businessProcess>Standard Request</businessProcess>
        <label>Claim</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Placement__c.object
<CustomObject>
    <description>Holds information about a housing placement, when the Opportunity stage is set to Moved-In, and a policy holder moves into the temporarry housing.  Besides the detail about the duration of the placement, this object is related to Cases to track any issues related to the placement.</description>
    <fields>
        <fullName>Area_Specialist_Email__c</fullName>
        <label>Residence Specialist Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Customer_Care_Specialist_Email__c</fullName>
        <label>Customer Care Specialist Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Hotel_Customer_Care_Specialist_Email__c</fullName>
        <label>Hotel Customer Care Specialist Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Housing_Coordinator_Email__c</fullName>
        <label>Residence Coordinator Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Claim Lookup</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Placements</relationshipLabel>
        <relationshipName>Placements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Regional_Manager_Email__c</fullName>
        <label>Relationship Manager Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Sequence_Number__c</fullName>
        <label>Sequence Number</label>
        <precision>7</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ServiceRequest__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Request</label>
        <referenceTo>ServiceRequest__c</referenceTo>
        <relationshipLabel>Placements</relationshipLabel>
        <relationshipName>Placements1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Checked-In</fullName>
                </value>
                <value>
                    <fullName>Checked-Out</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Moved-In</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Moved-Out</fullName>
                </value>
                <value>
                    <fullName>Pending Confirmation</fullName>
                </value>
                <value>
                    <fullName>Quote</fullName>
                </value>
                <value>
                    <fullName>Searching</fullName>
                </value>
                <value>
                    <fullName>Pending Check-In</fullName>
                </value>
                <value>
                    <fullName>Lost Opportunity</fullName>
                </value>
                <value>
                    <fullName>Viewing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Placement</label>
    <nameField>
        <label>Placement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Placements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ServiceRequest__c.object
<CustomObject>
    <description>Holds the different services that a request can include, such as: Hotel Stays, Housing requests, Furniture requests, Fair Rental Value, etc.</description>
    <fields>
        <fullName>Area_Specialist_Email__c</fullName>
        <label>Property Specialist Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Area_Specialist__c</fullName>
        <formula>Opportunity__r.Area_Specialist__r.FirstName &amp; &quot; &quot; &amp; Opportunity__r.Area_Specialist__r.LastName</formula>
        <label>Residence Specialist</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Care_Specialist_Email__c</fullName>
        <label>Customer Care Specialist Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Hotel_Customer_Care_Specialist_Email__c</fullName>
        <label>Hotel Customer Care Specialist Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Housing_Coordinator_Email__c</fullName>
        <label>Housing Coordinator Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Housing_Coordinator__c</fullName>
        <formula>Opportunity__r.Housing_Coordinator__r.FirstName &amp; &quot; &quot; &amp;  Opportunity__r.Housing_Coordinator__r.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Housing Coordinator</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Claim</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Service Requests</relationshipLabel>
        <relationshipName>Service_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Regional_Manager_Email__c</fullName>
        <label>Relationship Manager Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>ServiceRequest__c</fullName>
        <formula>Id</formula>
        <label>ServiceRequest</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Request</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Searching</fullName>
                </value>
                <value>
                    <fullName>Pending Confirmation</fullName>
                </value>
                <value>
                    <fullName>Moved-In/Closed</fullName>
                </value>
                <value>
                    <fullName>Finders Fee</fullName>
                </value>
                <value>
                    <fullName>Hold</fullName>
                </value>
                <value>
                    <fullName>Checked-In/Closed</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Lost Opportunity</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Service Request</label>
    <nameField>
        <displayFormat>SR#-{000000}</displayFormat>
        <label>Service Request</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Requests</pluralLabel>
    <recordTypes>
        <fullName>Hotel</fullName>
        <active>true</active>
        <description>For Hotel requests</description>
        <label>Hotel</label>
    </recordTypes>
    <recordTypes>
        <fullName>Housing</fullName>
        <active>true</active>
        <description>For Housing requests</description>
        <label>Housing</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/NewClaimWizard.cls
public with sharing class NewClaimWizard {
    private List<OpportunityContactRole> roles = new OpportunityContactRole []{new OpportunityContactRole(),new OpportunityContactRole(),new OpportunityContactRole(),new OpportunityContactRole()};
        
    public Lead lead { get; set;}
    public Contact policyholderContact { get; set; }
    public Opportunity claim { get; set; }
    
    
            
    public NewClaimWizard(ApexPages.StandardController controller) {
        
        claim = (Opportunity)controller.getRecord();
        
        
        claim.Name = 'Temp'; // overridden by trigger
        claim.StageName = 'Submitted';             
        policyHolderContact = new Contact(); 
        policyholderContact.RecordTypeId = RecordTypeHelper.policyholderContactRT();
        lead = new Lead();
        lead.LastName = '-*--*-';
        lead.Company = '-*--*-';
    }
    
    
    public List<OpportunityContactRole> getContactRoles() 
    {
        return roles;
    }
    
    public PageReference step1() {
        return Page.NewClaimWizard1;
    }
    
    public PageReference step2() {
        
        boolean valid = true;
        if (policyholderContact.FirstName.length()>2 && policyholderContact.LastName.length()>2 && policyholderContact.FirstName.touppercase().equals(policyholderContact.FirstName) && policyholderContact.LastName.touppercase().equals(policyholderContact.LastName))
        {
           ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR, 'Please enter the proper capitalization. Policyholder First and Last names cannot be all capital letters.');
           ApexPages.addmessage(myMsg); 
           valid = false;
        }
        if (valid)
        {
            return Page.NewClaimWizard2;
        }
        else 
        {
            return null;      
        }
    }
    
    public PageReference step3() {
        return Page.NewClaimWizard3;
    }
    
    public PageReference finish() {
        if (save()) {
            return new ApexPages.Standardcontroller(claim).view();
        } else { 
            return null;
        }
    }
    
    public PageReference toggleLeadSourceFields()
    {
        if (lead.LeadSource != 'Direct Referral')
        {
            lead.Refered_By__c = '';
        }
        if (lead.LeadSource != 'Other')
        {
            lead.Other_Source__c = '';
        }
        return null;
    }
    
    public PageReference initialServiceRequest() {
        if (save()) {
            Opportunity savedClaim = [select Name from Opportunity where Id = :claim.Id]; // get auto-generated name
            ServiceRequest__c serviceRequest = new ServiceRequest__c();
            serviceRequest.Opportunity__c = claim.Id;
            if (claim.Initial_Service_Request__c == 'Housing')
            {
                serviceRequest.RecordTypeId = RecordTypeHelper.housingServiceRequestRT();
                serviceRequest.Status__c = 'Active';
                insert(serviceRequest);
            
                Double seqNumber;
                try
                {
                    seqNumber = [select Sequence_Number__c From Placement__c where Opportunity__c =:serviceRequest.Opportunity__c and RecordTypeId =:RecordTypeHelper.housingPlacementRT() order by Sequence_Number__c desc limit 1].Sequence_Number__c;
                    seqNumber ++;
                }
                catch (exception e)
                {
                    seqNumber = 1;
                }
            
                Placement__c relatedPlacement = new Placement__c();
                relatedPlacement.RecordTypeId = RecordTypeHelper.housingPlacementRT();
                relatedPlacement.ServiceRequest__c = serviceRequest.Id;
                relatedPlacement.Opportunity__c = serviceRequest.Opportunity__c;
                Opportunity claim = [select name, Policyholder__r.Name,Initial_Service_Request__c,Customer_Care_Specialist__r.Email,Regional_Manager__r.Email,Area_Specialist__r.Email,Housing_Coordinator__r.Email,Hotel_Customer_Care_Specialist__r.Email from Opportunity where Id =:serviceRequest.Opportunity__c]; 
                relatedPlacement.Name = claim.Name + ' - ' + claim.Policyholder__r.Name + ' #' + seqNumber.intValue();
                relatedPlacement.Sequence_Number__c = seqNumber;
                relatedPlacement.Customer_Care_Specialist_Email__c = claim.Customer_Care_Specialist__r.Email;
                relatedPlacement.Regional_Manager_Email__c = claim.Regional_Manager__r.Email;
                relatedPlacement.Area_Specialist_Email__c = claim.Area_Specialist__r.Email;
                relatedPlacement.Housing_Coordinator_Email__c = claim.Housing_Coordinator__r.Email;
                relatedPlacement.Hotel_Customer_Care_Specialist_Email__c = claim.Hotel_Customer_Care_Specialist__r.Email;

                upsert relatedPlacement;
            
                PageReference housingPage = Page.HousingEntry;
                housingPage.getParameters().put('id', serviceRequest.Id);
                housingPage.setRedirect(true);
                return housingPage;
            }
            else
            {
                if (claim.Initial_Service_Request__c == 'Hotel')
                {
                    serviceRequest.RecordTypeId = RecordTypeHelper.hotelServiceRequestRT();
                    serviceRequest.Status__c = 'Request';
                    insert(serviceRequest);
                    
                    PageReference hotelPage = Page.HotelEntry;
                    hotelPage.getParameters().put('id', serviceRequest.Id);
                    hotelPage.setRedirect(true);
                    return hotelPage;
                }
                else 
                {
                    if (claim.Initial_Service_Request__c == 'Finders Fees')
                    {
                        PageReference findersFeesPage = new PageReference('/a0P/e'); // new service request
                        findersFeesPage.getParameters().put('nooverride', '1');     
                        findersFeesPage.getParameters().put('RecordType', RecordTypeHelper.findersFeesServiceRequestRT());      
                        findersFeesPage.getParameters().put('CF00N70000002RNTb', savedClaim.Name);  
                        findersFeesPage.getParameters().put('retURL', '%2F' + new ApexPages.Standardcontroller(claim).view().getUrl()); 
                        findersFeesPage.setRedirect(true);
                
                        return findersFeesPage; 
                    }
                    else
                    {
                        PageReference frvPage = new PageReference('/a0P/e'); // new service request
                        frvpage.getParameters().put('nooverride', '1');     
                        frvpage.getParameters().put('RecordType', RecordTypeHelper.frvServiceRequestRT());      
                        frvpage.getParameters().put('CF00N70000002RNTb', savedClaim.Name);  
                        frvpage.getParameters().put('retURL', '%2F' + new ApexPages.Standardcontroller(claim).view().getUrl()); 
                        frvpage.setRedirect(true);
                
                        return frvPage; 
                    }           
                }
            }       
        } 
        else 
        {
            return null;
        }
    }
    
    public boolean save() {
        Savepoint beforeSave = Database.setSavepoint();
            
        try {
            insert policyholderContact;
            
            if (!Test.isRunningTest())
            {
                claim.Policyholder__c = policyholderContact.Id;
            }
            insert claim;
                        
            
            if (lead.LastName != '-*--*-' && claim.Adjuster__c == null)
            {
                lead.Opportunity__c = claim.Id;
                insert lead;
            }
            
            List<OpportunityContactRole> rolesToSave = new List<OpportunityContactRole>();
            for (OpportunityContactRole contactRole : roles)
            {
                if (contactRole.ContactId != null)
                {
                    contactRole.OpportunityId = claim.Id; 
                    rolesToSave.add(contactRole);      
                }
            }               
            insert rolesToSave;
            
            return true;        
        } catch (Exception ex) {
            Database.rollback(beforeSave);
            
            // clear ids for save after validation corrections
            claim = claim.clone(false, true); 
            policyholderContact = policyholderContact.clone(false, true);
            lead = lead.clone(false, true);
                        
            string message = 'Error saving new claim: ' + ex.getMessage();
    
            // don't append if we already have a validation error
            if (ApexPages.getMessages().size() == 0) {
                ApexPages.addMessage(new Apexpages.Message(ApexPages.Severity.ERROR, message));
            }
            
            return false;
        }
    }
}