src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Active - potential of doing business
Inactive - not able to do business
No Longer with Company</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>No Longer with Company</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Hotel_Room__c.object
<CustomObject>
    <description>Holds the information related to a Hotel Booking.</description>
    <fields>
        <fullName>Cancellation_del__c</fullName>
        <label>Cancellation #</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CheckOut__c</fullName>
        <label>Check-Out Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Check_In__c</fullName>
        <label>Check-In Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Placement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Placement</label>
        <referenceTo>Placement__c</referenceTo>
        <relationshipLabel>Hotel Rooms</relationshipLabel>
        <relationshipName>Hotel_Rooms</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Hotel Room</label>
    <nameField>
        <displayFormat>Room-{00000}</displayFormat>
        <label>Hotel Room</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hotel Rooms</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Placement__c.object
<CustomObject>
    <description>Holds information about a housing placement, when the Opportunity stage is set to Moved-In, and a policy holder moves into the temporarry housing.  Besides the detail about the duration of the placement, this object is related to Cases to track any issues related to the placement.</description>
    <fields>
        <fullName>Approved_Through_Date__c</fullName>
        <label>Approved Through Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MHS_Booking__c</fullName>
        <description>Was the hotel booked via MHS</description>
        <inlineHelpText>Was the hotel booked via MHS?</inlineHelpText>
        <label>MHS Booking</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                    <default>true</default>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Checked-In</fullName>
                </value>
                <value>
                    <fullName>Checked-Out</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Moved-In</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Moved-Out</fullName>
                </value>
                <value>
                    <fullName>Pending Confirmation</fullName>
                </value>
                <value>
                    <fullName>Quote</fullName>
                </value>
                <value>
                    <fullName>Searching</fullName>
                </value>
                <value>
                    <fullName>Pending Check-In</fullName>
                </value>
                <value>
                    <fullName>Lost Opportunity</fullName>
                </value>
                <value>
                    <fullName>Viewing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Placement</label>
    <nameField>
        <label>Placement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Placements</pluralLabel>
    <recordTypes>
        <fullName>Hotel_Placement</fullName>
        <active>true</active>
        <description>Place PH into Hotel</description>
        <label>Hotel Placement</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/History_test.cls
@isTest
private class History_test {
	static testmethod void testNotes(){
		Id recordTypeId = [SELECT Id FROM RecordType WHERE sObjectType='Placement__c' AND DeveloperName='Hotel_Placement'].Id;
		Placement__c thisPlacement = new Placement__c();
		thisPlacement.RecordTypeId = recordTypeId;
        thisPlacement.Name = 'OBTestPlacement';
        thisPlacement.Status__c = 'Moved-In'; 
        thisPlacement.approved_through_date__c = date.newInstance(2011, 11, 18);
        thisPlacement.MHS_Booking__c = 'No';
		
		insert thisPlacement;
		
		History incidentHistory = new History(thisPlacement);
		incidentHistory.buildEntries();
		System.assertEquals(0,incidentHistory.events.size());
		
		Note newNote1 = new Note(parentId = thisPlacement.id, title = 'a new note');
		insert newNote1;
		incidentHistory.buildEntries();
		System.assertEquals(1,incidentHistory.events.size());
		
		Note newNote2 = new Note(parentId = thisPlacement.id, title = 'a second new note');
		insert newNote2;
		incidentHistory.buildEntries();
		System.assertEquals(2,incidentHistory.events.size());
		
		
		// This is to get full code coverage on the Util class
		Hotel_Room__c [] hotelRooms = [SELECT Check_In__c,CheckOut__c,Cancellation_del__c,Placement__c FROM Hotel_Room__c limit 10];
		Set<Id> test = Util.getIds(hotelRooms);
		
	}
	
	static testmethod void testActivities(){
		Id recordTypeId = [SELECT Id FROM RecordType WHERE sObjectType='Placement__c' AND DeveloperName='Hotel_Placement'].Id;
		Placement__c thisPlacement = new Placement__c();
		thisPlacement.RecordTypeId = recordTypeId;
        thisPlacement.Name = 'OBTestPlacement';
        thisPlacement.Status__c = 'Moved-In'; 
        thisPlacement.approved_through_date__c = date.newInstance(2011, 11, 18);
        thisPlacement.MHS_Booking__c = 'No';
		insert thisPlacement;
		
		History incidentHistory = new History(thisPlacement);
		incidentHistory.buildEntries();
		System.assertEquals(0,incidentHistory.events.size());
		
		Task newTask = new Task(whatId = thisPlacement.id, subject='a new Task');
		insert newTask;
		
		Event newEvent1 = new Event(whatId = thisPlacement.id,  subject='a new event', DurationInMinutes = 30, ActivityDateTime = Datetime.now());
		insert newEvent1;
		
		Event newEvent2 = new Event(whatId = thisPlacement.id,  subject='a second new event', DurationInMinutes = 30, ActivityDateTime = Datetime.now());
		insert newEvent2;
		
		incidentHistory.buildEntries();
		System.assertEquals(3,incidentHistory.events.size());  
		
	}
	
	static testmethod void testHistory(){
		//This method contains no assertions because we cannot assert that customers have field history tracking set a specific way.
	/*	Contact newContact = new Contact(LastName = 'Bob');
		
		insert newContact; */
				
		Id recordTypeId = [SELECT Id FROM RecordType WHERE sObjectType='Placement__c' AND DeveloperName='Hotel_Placement'].Id;
			Placement__c thisPlacement = new Placement__c();
		   	thisPlacement.RecordTypeId = recordTypeId;
            thisPlacement.Name = 'OBTestPlacement';
            thisPlacement.Status__c = 'Checked-In'; 
            thisPlacement.approved_through_date__c = date.newInstance(2011, 11, 18);
           	thisPlacement.MHS_Booking__c = 'No';
        insert thisPlacement;
        
		History incidentHistory = new History(thisPlacement);
		incidentHistory.buildEntries();
		System.assertEquals(0,incidentHistory.events.size());
		
		thisPlacement.MHS_Booking__c = 'Yes';
		update thisPlacement;
		
		thisPlacement.Status__c = 'Checked-Out'; 
		update thisPlacement;
		
		Placement__history thisHistory = new Placement__history(parentId = thisPlacement.id, field = 'created');
		insert thisHistory;
		
		History.FieldHistory thisUpdate = new History.FieldHistory(null, 'oldVal', 'newVal', DateTime.now(), 'itil_b__subject__c');
		incidentHistory.injectedResults.add(thisUpdate);
		
		incidentHistory.buildEntries(); 
		System.debug('\nIncident History: '+incidentHistory.events);
		
	}
	
	static testmethod void testGeneric(){
	/*	Contact newContact = new Contact(LastName = 'Bob');
		insert newContact;  */
			Id recordTypeId = [SELECT Id FROM RecordType WHERE sObjectType='Placement__c' AND DeveloperName='Hotel_Placement'].Id;
			Placement__c thisPlacement = new Placement__c();
		   	thisPlacement.RecordTypeId = recordTypeId;
            thisPlacement.Name = 'OBTestPlacement';
            thisPlacement.Status__c = 'Moved-In'; 
            thisPlacement.approved_through_date__c = date.newInstance(2011, 11, 18);
           	thisPlacement.MHS_Booking__c = 'No';
           
		
		insert thisPlacement;
		
		History incidentHistory = new History(thisPlacement);
		incidentHistory.buildEntries();
		System.assertEquals(0,incidentHistory.events.size());
		
	/*	itil_b__Worklog__c newWorklog = new itil_b__Worklog__c(Placement__c = thisPlacement.id, name = 'a new worklog');
		insert newWorklog;
		
		incidentHistory.buildEntries();
		System.assertEquals(1,incidentHistory.events.size());  */
	}
}