src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Active_Placements__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If this contact is an adjuster or landlord and is on any active placements this field will be checked</description>
        <label>Active Placements</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Active - potential of doing business
Inactive - not able to do business
No Longer with Company</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>No Longer with Company</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Adjuster</fullName>
        <active>true</active>
        <description>All contacts that work in the Insurance Industry. Includes Company Adjusters, Independent Adjusters, Public Adjusters, Supervisors, Managers, Procurement etc.</description>
        <label>Adjuster</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Costs__c.object
<CustomObject>
    <fields>
        <fullName>Billable_Party__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Billable Party</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.Status__c</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Costs (Billable Party)</relationshipLabel>
        <relationshipName>Costs1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Searches__c</fullName>
        <label>Search</label>
        <referenceTo>Searches__c</referenceTo>
        <relationshipLabel>Costs</relationshipLabel>
        <relationshipName>Costs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Costs</label>
    <nameField>
        <displayFormat>Cost-{0000000}</displayFormat>
        <label>Cost Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Costs</pluralLabel>
    <recordTypes>
        <fullName>Cost</fullName>
        <active>true</active>
        <label>Cost</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Adjuster__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The adjuster must already be a contact in the system.</inlineHelpText>
        <label>Adjuster</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Adjuster</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Claims (Adjuster)</relationshipLabel>
        <relationshipName>Opportunities2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Area_Specialist_Assigned__c</fullName>
        <label>Residence Specialist Assigned</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Area_Specialist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Residence Specialist</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Care_Specialist_Assigned__c</fullName>
        <label>Customer Care Specialist Assigned</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Customer_Care_Specialist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Care Specialist</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Hotel_Customer_Care_Specialist_Assigned__c</fullName>
        <label>Hotel Customer Care Specialist Assigned</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Hotel_Customer_Care_Specialist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Hotel Customer Care Specialist</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Housing_Coordinator_Assigned__c</fullName>
        <label>Residence Coordinator Assigned</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Housing_Coordinator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Residence Coordinator</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Initial_Service_Request__c</fullName>
        <label>Initial Service Request</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Housing</fullName>
                </value>
                <value>
                    <fullName>Hotel</fullName>
                </value>
                <value>
                    <fullName>FRV</fullName>
                </value>
                <value>
                    <fullName>Furniture Only</fullName>
                </value>
                <value>
                    <fullName>Unfurnished</fullName>
                </value>
                <value>
                    <fullName>Trailer-Mobile Home</fullName>
                </value>
                <value>
                    <fullName>Commercial</fullName>
                </value>
                <value>
                    <fullName>Finders Fees</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Policyholder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Policyholder</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Policyholder, Adjuster Policyholder Record Type</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Claims</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Regional_Manager_Assigned__c</fullName>
        <label>Relationship Manager Assigned</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Regional_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Relationship Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities4</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Claim</fullName>
        <active>true</active>
        <businessProcess>Standard Request</businessProcess>
        <label>Claim</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Placement__c.object
<CustomObject>
    <description>Holds information about a housing placement, when the Opportunity stage is set to Moved-In, and a policy holder moves into the temporarry housing.  Besides the detail about the duration of the placement, this object is related to Cases to track any issues related to the placement.</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Claim Lookup</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Placements</relationshipLabel>
        <relationshipName>Placements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Checked-In</fullName>
                </value>
                <value>
                    <fullName>Checked-Out</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Moved-In</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Moved-Out</fullName>
                </value>
                <value>
                    <fullName>Pending Confirmation</fullName>
                </value>
                <value>
                    <fullName>Quote</fullName>
                </value>
                <value>
                    <fullName>Searching</fullName>
                </value>
                <value>
                    <fullName>Pending Check-In</fullName>
                </value>
                <value>
                    <fullName>Lost Opportunity</fullName>
                </value>
                <value>
                    <fullName>Viewing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Placement</label>
    <nameField>
        <label>Placement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Placements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Searches__c.object
<CustomObject>
    <description>Used track the property and hotel searches conducted as part of the Sevice Request</description>
    <fields>
        <fullName>Hotel__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Hotel Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Hotel Accounts</value>
            </filterItems>
            <filterItems>
                <field>Account.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Searches</relationshipLabel>
        <relationshipName>Searches</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Landlord__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Landlord</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Landlord</value>
            </filterItems>
            <filterItems>
                <field>Contact.Status__c</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Searches</relationshipLabel>
        <relationshipName>Searches</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Placement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Placement</label>
        <referenceTo>Placement__c</referenceTo>
        <relationshipName>Searches</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Request__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Service Request</label>
        <referenceTo>ServiceRequest__c</referenceTo>
        <relationshipName>Searches</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IF(  $RecordType.DeveloperName = &quot;Hotel&quot;, &quot;Check Capacity&quot;,IF(ISPICKVAL(Property__r.Status__c , &quot;Occupied&quot;) , &quot;Not Available&quot;, &quot;Available&quot;))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <label>Search</label>
    <nameField>
        <displayFormat>SR-{000000}</displayFormat>
        <label>Search Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Searches</pluralLabel>
    <recordTypes>
        <fullName>Hotel</fullName>
        <active>true</active>
        <description>For Hotel Requests</description>
        <label>Hotel</label>
    </recordTypes>
    <recordTypes>
        <fullName>Housing</fullName>
        <active>true</active>
        <description>For Housing Requests</description>
        <label>Housing</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/ServiceRequest__c.object
<CustomObject>
    <description>Holds the different services that a request can include, such as: Hotel Stays, Housing requests, Furniture requests, Fair Rental Value, etc.</description>
    <fields>
        <fullName>Area_Specialist__c</fullName>
        <formula>Opportunity__r.Area_Specialist__r.FirstName &amp; &quot; &quot; &amp; Opportunity__r.Area_Specialist__r.LastName</formula>
        <label>Residence Specialist</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Housing_Coordinator_Assigned__c</fullName>
        <formula>Opportunity__r.Housing_Coordinator_Assigned__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Residence Coordinator Assigned</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Housing_Coordinator__c</fullName>
        <formula>Opportunity__r.Housing_Coordinator__r.FirstName &amp; &quot; &quot; &amp;  Opportunity__r.Housing_Coordinator__r.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Housing Coordinator</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Claim</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Service Requests</relationshipLabel>
        <relationshipName>Service_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Request</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Searching</fullName>
                </value>
                <value>
                    <fullName>Pending Confirmation</fullName>
                </value>
                <value>
                    <fullName>Moved-In/Closed</fullName>
                </value>
                <value>
                    <fullName>Finders Fee</fullName>
                </value>
                <value>
                    <fullName>Hold</fullName>
                </value>
                <value>
                    <fullName>Checked-In/Closed</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Lost Opportunity</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Service Request</label>
    <nameField>
        <displayFormat>SR#-{000000}</displayFormat>
        <label>Service Request</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Requests</pluralLabel>
    <recordTypes>
        <fullName>Hotel</fullName>
        <active>true</active>
        <description>For Hotel requests</description>
        <label>Hotel</label>
    </recordTypes>
    <recordTypes>
        <fullName>Housing</fullName>
        <active>true</active>
        <description>For Housing requests</description>
        <label>Housing</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ClaimTriggerHandler.cls
public class ClaimTriggerHandler {
    
    
    public static void setOwnerAsRelationshipManager(List<Opportunity> claims, Map<id,opportunity> oldOppMap){
        for(Opportunity claim : claims)
        {                                         
            claim.OwnerId = claim.Regional_Manager__c;
            
            if(trigger.isInsert)
            {
                if (claim.Regional_Manager__c != null)
                    claim.Regional_Manager_Assigned__c = DateTime.now();
                if(claim.Customer_Care_Specialist__c != null)
                    claim.Customer_Care_Specialist_Assigned__c = DateTime.now();
                if(claim.Area_Specialist__c != null) 
                    claim.Area_Specialist_Assigned__c = DateTime.now();
                if(claim.Housing_Coordinator__c != null)
                    claim.Housing_Coordinator_Assigned__c = DateTime.now();
                if(claim.Hotel_Customer_Care_Specialist__c != null)
                    claim.Hotel_Customer_Care_Specialist_Assigned__c = DateTime.now();
            }
            if(trigger.isUpdate)
            {
                opportunity oldOpp = oldOppMap.get(claim.id);
                if(claim.Regional_Manager__c != oldOpp.Regional_Manager__c && claim.Regional_Manager__c != null)
                    claim.Regional_Manager_Assigned__c = DateTime.now();
                if(claim.Customer_Care_Specialist__c != oldOpp.Customer_Care_Specialist__c && claim.Customer_Care_Specialist__c != null)
                    claim.Customer_Care_Specialist_Assigned__c = DateTime.now();
                if(claim.Area_Specialist__c != oldOpp.Area_Specialist__c && claim.Area_Specialist__c != null) 
                    claim.Area_Specialist_Assigned__c = DateTime.now();
                if(claim.Housing_Coordinator__c != oldOpp.Housing_Coordinator__c && claim.Housing_Coordinator__c != null)
                    claim.Housing_Coordinator_Assigned__c = DateTime.now();
                if(claim.Hotel_Customer_Care_Specialist__c != oldOpp.Hotel_Customer_Care_Specialist__c && claim.Hotel_Customer_Care_Specialist__c != null)
                    claim.Hotel_Customer_Care_Specialist_Assigned__c = DateTime.now();
            }
            
        }    
        
    }
    
    // this Method has been moved from CRSAccountNameTrigger 
    
    Public Static void CRSAccountNameTrigger(List<Opportunity> claims)
    {
        List<Opportunity> opportunities = new List<Opportunity>();
        List<Id> adjusterIdList = new List<Id>();
        Map<Id, Id> adjusterAccIdMap = new Map<Id, Id>();
        
        /*
    Iterate the list of new Opportunity records to be saved or updated
    and store their unique Ids in a list
    */
        for (Opportunity opp:claims) {     
            if (opp.Adjuster__c != null) {                               
                adjusterIdList.add(opp.Adjuster__c);      
                opportunities.add(opp);       
            }       
        }
        
        /*
    Get the unique Ids and Account Ids of Adjuster records corresponding to the list of
    new Opportunity records to be saved or updated
    */       
        Contact[] contactAccIdList = [select Id, AccountId from Contact where id in :adjusterIdList];
        
        for (Integer i=0;i<contactAccIdList.size();i++) {      
            adjusterAccIdMap.put(contactAccIdList[i].Id, contactAccIdList[i].AccountId);
        }
        
        /*
Assign the value of Opportunity AccountId with the Account Id of its Adjuster record
*/      
        for (Opportunity opp:claims) {        
            opp.AccountId = adjusterAccIdMap.get(opp.Adjuster__c);
        }
    }
    
    // This method is being called from THATaskCreationOrUpdate it will excute in insert call 
    Public Static Void THATaskCreation(List<Opportunity> claims){
        List<Task> TaskRecords = new List<Task>();
        for(Opportunity O : claims){
            if((O.Initial_Service_Request__c == 'Hotel' || O.Initial_Service_Request__c == 'Housing')  && O.Hotel_Customer_Care_Specialist__c != null){
                
                Task tRec = new Task();
                Integer currentHour = System.now().hour();
                if(currentHour < 17){                                                
                    tRec.Due_Time__c = DateTime.newInstance(Date.toDay().year(), Date.toDay().month(), Date.toDay().day(), 17, 0, 0);                                   
                }
                else{
                    Date nextDayDate = Date.toDay().addDays(1);
                    DateTime dueDateTime = DateTime.newInstance(nextDayDate.year(), nextDayDate.month(), nextDayDate.day(), 17, 0, 0);
                    tRec.Due_Time__c = dueDateTime;
                }                      
                
                tRec.ActivityDate = Date.valueOf(tRec.Due_Time__c); 
                tRec.OwnerId = O.Hotel_Customer_Care_Specialist__c;                        
                tRec.Priority = 'Normal';                      
                tRec.WhatID = O.Id;
                tRec.Status = 'Not Started';
                tRec.Subject = 'Send Temporary Housing Agreement(THA)';                               
                tRec.Type = 'Hold Follow Up';
                trec.WhoId = O.Policyholder__c;                                      
                TaskRecords.add(trec);
            }
        }
        
        if(!TaskRecords.isEmpty()){
            insert TaskRecords;
        }
        
    }
    
    // This method is being called from THATaskCreationOrUpdate it will excute in updatecall 
    
    Public Static void THATaskUpdate(List<Opportunity> claims, Map<Id,Opportunity> oldOppMap){
        
        List<Task> taskExistList = new List<Task>();
        Set<Id> oppIds = new Set<Id>();
        
        Set<Id> claimIds = new Set<Id>(); //This is called from UpdateCostsOnAdjusterChange trigger 
        Map<Id, Id> claimId_OldAdjusterId = new Map<Id, Id>(); //This is called from UpdateCostsOnAdjusterChange trigger
        Map<Id, Id> claimId_NewAdjusterId = new Map<Id, Id>(); //This is called from UpdateCostsOnAdjusterChange trigger 
    
        for(Opportunity O : claims){
            Opportunity oppOld = oldOppMap.get(O.Id);
            
            if(O.Initial_Service_Request__c == 'Hotel' && O.Hotel_Customer_Care_Specialist__c != null){
                
                if(O.Hotel_Customer_Care_Specialist__c != oppOld.Hotel_Customer_Care_Specialist__c){
                    oppIds.add(O.Id);        
                }
            }
            
            // This is called from UpdateCostsOnAdjusterChange trigger -- Start
            if (oppOld.Adjuster__c != o.Adjuster__c)
            {                
                claimIds.add(o.Id);
                claimId_OldAdjusterId.put(o.Id,oppOld.Adjuster__c);
                claimId_NewAdjusterId.put(o.Id,o.Adjuster__c);
            }
        }
        
        
        List<costs__c> costList = [select Id,Searches__r.Service_Request__r.Opportunity__c, Billable_Party__c from costs__c where 
                                    Searches__r.Service_Request__r.Opportunity__c in : claimIds and 
                                    Searches__r.Placement__r.Status__c in ('Searching','Viewing','Pending Confirmation')];
        Boolean updateCost = false;
        for (costs__c cost : costList)
        {
            if (cost.Billable_Party__c == claimId_OldAdjusterId.get(cost.Searches__r.Service_Request__r.Opportunity__c))
            {
                cost.Billable_Party__c = claimId_NewAdjusterId.get(cost.Searches__r.Service_Request__r.Opportunity__c);
                updateCost = true;
            }
        }
        
        if(updateCost)
            update costList;
            //This is called from UpdateCostsOnAdjusterChange trigger -- END
            
        if(!oppIds.isEmpty()){
            
            taskExistList = [Select Id, ownerId, whatId from Task where whatId in: oppIds AND Subject = 'Send Temporary Housing Agreement(THA)' ];
            
            for(Opportunity O : claims){
                if(O.Initial_Service_Request__c == 'Hotel' && O.Hotel_Customer_Care_Specialist__c != null){
                    
                    Opportunity oppOld = oldOppMap.get(O.Id);
                    
                    if(O.Hotel_Customer_Care_Specialist__c != oppOld.Hotel_Customer_Care_Specialist__c){                           
                        
                        boolean isTaskFound = false;
                        for(Task T : taskExistList){
                            if(T.whatId == O.Id){
                                T.ownerId = O.Hotel_Customer_Care_Specialist__c;
                                isTaskFound = true;
                                break;
                            }
                        }
                        
                        if(isTaskFound == false){
                            
                            Task tRec = new Task();
                            Integer currentHour = System.now().hour();
                            
                            if(currentHour < 17){                                                
                                tRec.Due_Time__c = DateTime.newInstance(Date.toDay().year(), Date.toDay().month(), Date.toDay().day(), 17, 0, 0);                                   
                            }
                            else{
                                Date nextDayDate = Date.toDay().addDays(1);
                                DateTime dueDateTime = DateTime.newInstance(nextDayDate.year(), nextDayDate.month(), nextDayDate.day(), 17, 0, 0);
                                tRec.Due_Time__c = dueDateTime;
                            }                      
                            
                            tRec.ActivityDate = Date.valueOf(tRec.Due_Time__c); 
                            tRec.OwnerId = O.Hotel_Customer_Care_Specialist__c;                        
                            tRec.Priority = 'Normal';                      
                            tRec.WhatID = O.Id;
                            tRec.Status = 'Not Started';
                            tRec.Subject = 'Send Temporary Housing Agreement(THA)';                               
                            tRec.Type = 'Hold Follow Up';
                            trec.WhoId = O.Policyholder__c;                                      
                            taskExistList.add(trec);
                        }
                        
                    }
                }
            }
            
            if(!taskExistList.isEmpty()){
                upsert taskExistList;
            }
            
        }
        
    }
    
 // Moved form UpdateActivePlacementsOnAdjusterChange after update 
    Public Static void UpdateActivePlacementsOnAdjusterChange(List<Opportunity> claims, Map<Id,Opportunity> oldOppMap)
    {
      Set<Id> adjusterIds = new Set<Id>();
      Map<Id, Boolean> adjusterId_ActivePlacement = new Map<Id, Boolean>();
      Set<String> closedStatus = new Set<String>{'Moved-Out','Lost Opportunity','Closed','Cancelled'};
      
      for (Opportunity claim : claims)    
        {
            Opportunity OldOpp = oldOppMap.get(claim.id);
              if (OldOpp.Adjuster__c != claim.Adjuster__c)
              {
               adjusterId_ActivePlacement.put(OldOpp.Adjuster__c,false);
               adjusterIds.add(claim.Adjuster__c);  
               adjusterId_ActivePlacement.put(claim.Adjuster__c,false); 
              }
        
         } 
     placement__c [] activePlacements = [select Opportunity__r.Adjuster__c from Placement__c where RecordTypeId =: RecordTypeHelper.housingPlacementRT() and Opportunity__r.Adjuster__c in : adjusterIds and Opportunity__r.Adjuster__c != NULL and Status__c not in : closedStatus];

        for(Placement__c activePlacement : activePlacements)
        {   
            adjusterId_ActivePlacement.put(activePlacement.Opportunity__r.Adjuster__c,true);
        }
    Contact [] contacts = [select Id, Active_Placements__c from Contact where Status__c = 'Active' and Id in : adjusterIds];
    
       for(Contact contact : contacts)
       {
          contact.Active_Placements__c = adjusterId_ActivePlacement.get(contact.Id);
       }
    update contacts;  
    }
    
  //To reassign service request open activities to new user selected on "Hotel Customer Care Specialist" and no value on Initial_SR_being_worked_by__c field in Service Request
    Public Static void ReassignServiceRequestAutoTasks(list<Opportunity> claims, Map<Id,Opportunity> oldOppMap)
    {
        Set<Id> oppIds = new Set<Id>();
      
      for(Opportunity opp : claims){
          if(opp.Initial_Service_Request__c == 'Hotel' && opp.Hotel_Customer_Care_Specialist__c != oldOppMap.get(opp.Id).Hotel_Customer_Care_Specialist__c && opp.Hotel_Customer_Care_Specialist__c != null){
              oppIds.add(opp.Id);
          }
      }   
      
      if(!oppIds.isEmpty()){
          Map<Id,ServiceRequest__c> serviceReqMap = new Map<Id,ServiceRequest__c>([Select Id,  Opportunity__r.Hotel_Customer_Care_Specialist__c from ServiceRequest__c where Opportunity__c in: oppIds AND RecordType.Name = 'Hotel' AND Initial_SR_being_worked_by__c = null]);
     
          if(serviceReqMap.values().size() > 0){
                
                List<Task> taskRecordsList = [Select Id, whatId, OwnerId from Task where whatId in: serviceReqMap.keySet() AND Status != 'Completed' AND (Subject = 'Hotel Options' OR Subject = 'Book Hotel' OR Subject = 'Hotel Needed-Hold Follow Up Call to PH' OR Subject = 'Send Temporary Housing Agreement(THA)' OR Subject = 'Send Credit Card Authorization (CCA)' OR Subject = 'Send Adjuster Confirmation' OR Subject LIKE '%Call Attempt%' OR Subject = 'Confirm Receipt of CCA') ];
        
                for(Task t : taskRecordsList){                    
                     if(serviceReqMap.get(t.whatId) != null && serviceReqMap.get(t.whatId).Opportunity__r.Hotel_Customer_Care_Specialist__c != null)   
                        t.OwnerId = serviceReqMap.get(t.whatId).Opportunity__r.Hotel_Customer_Care_Specialist__c;                    
                } 
                
                if(!taskRecordsList.isEmpty()){
                    update taskRecordsList;
                }
          }
     }
  }
  
  /* Chatter Follow and Unfollow for CRS TEAM Section in Opportunity*/
  public static void claimFollow(list<opportunity> opprecords,Map<Id,opportunity> oldMap){
   Set<Id> oppId = new Set<Id>();
   Set<Id> UnFollowersClaimId = new Set<Id>();
   Set<Id> UnfollowersSubscriberId = new Set<Id>();
   list<EntitySubscription> FollowentitySubrecords = new list<EntitySubscription>();
   list<EntitySubscription> UnfollowentitySubrecords = new list<EntitySubscription>();
   
    Set<String> deleteRecordUserMatchSet = new Set<String>();
    Map<String,String> oppOldUserCustomerCareSpecialistMap = new Map<String,String>();
    Map<String,String> oppOldUserAreaSpecialistMap = new Map<String,String>();
    Map<String,String> oppOldUserRegionalManagerMap = new Map<String,String>();
    Map<String,String> oppOldUserHotelCustomerCareSpecialistMap = new Map<String,String>();
    Map<String,String> oppOldUserHousingCoordinatorMap =  new Map<String,String>();
   
    for(opportunity opp: opprecords){
                      
            if(Trigger.isInsert){
                
                if(opp.id <> null && opp.Customer_Care_Specialist__c <> null){
                     FollowentitySubrecords.add(new EntitySubscription(ParentId = opp.id, SubscriberId = opp.Customer_Care_Specialist__c));
                }
                
                if(opp.id <> null  && opp.Area_Specialist__c <> null){
                     FollowentitySubrecords.add(new EntitySubscription(ParentId = opp.id, SubscriberId = opp.Area_Specialist__c));
                }
                
                if(opp.id <> null  && opp.Regional_Manager__c <> null){
                     FollowentitySubrecords.add(new EntitySubscription(ParentId = opp.id, SubscriberId = opp.Regional_Manager__c ));
                }
                
                if(opp.id <> null && opp.Hotel_Customer_Care_Specialist__c <> null){
                     FollowentitySubrecords.add(new EntitySubscription(ParentId = opp.id, SubscriberId = opp.Hotel_Customer_Care_Specialist__c ));
                }
                
                if(opp.id <> null && opp.Housing_Coordinator__c <> null){
                     FollowentitySubrecords.add(new EntitySubscription(ParentId = opp.id, SubscriberId = opp.Housing_Coordinator__c ));
                }
            }
            
            if(Trigger.isUpdate && ((opp.Customer_Care_Specialist__c != oldMap.get(opp.Id).Customer_Care_Specialist__c ) || (opp.Hotel_Customer_Care_Specialist__c != oldMap.get(opp.Id).Hotel_Customer_Care_Specialist__c) || (opp.Area_Specialist__c != oldMap.get(opp.Id).Area_Specialist__c) || (opp.Regional_Manager__c != oldMap.get(opp.Id).Regional_Manager__c) || (opp.Housing_Coordinator__c != oldMap.get(opp.Id).Housing_Coordinator__c))){
                
                oppId.add(opp.id);
                
                // Customer care specialist    
                if(oldMap.get(opp.Id).Customer_Care_Specialist__c != null){
                    UnfollowersSubscriberId.add(oldMap.get(opp.Id).Customer_Care_Specialist__c);
                    unFollowersClaimId.add(opp.id);
                    deleteRecordUserMatchSet.add(opp.id+''+oldMap.get(opp.Id).Customer_Care_Specialist__c);    
                    oppOldUserCustomerCareSpecialistMap.put(opp.Id, oldMap.get(opp.Id).Customer_Care_Specialist__c);                        
                }  
                if(opp.Customer_Care_Specialist__c != null){
                     FollowentitySubrecords.add(new EntitySubscription(ParentId = opp.id, SubscriberId = opp.Customer_Care_Specialist__c));
                }
                
                // Area Specialist    
                if(oldMap.get(opp.Id).Area_Specialist__c != null){
                    UnfollowersSubscriberId.add(oldMap.get(opp.Id).Area_Specialist__c);
                    unFollowersClaimId.add(opp.id);
                    deleteRecordUserMatchSet.add(opp.id+''+oldMap.get(opp.Id).Area_Specialist__c);
                    oppOldUserAreaSpecialistMap.put(opp.Id, oldMap.get(opp.Id).Area_Specialist__c);                          
                }
                if(opp.Area_Specialist__c != null){
                    FollowentitySubrecords.add(new EntitySubscription(ParentId = opp.id, SubscriberId = opp.Area_Specialist__c));
                } 
                
                // Regional Manager    
                if(oldMap.get(opp.Id).Regional_Manager__c != null){
                    UnfollowersSubscriberId.add(oldMap.get(opp.Id).Regional_Manager__c);
                    unFollowersClaimId.add(opp.id); 
                    deleteRecordUserMatchSet.add(opp.id+''+oldMap.get(opp.Id).Regional_Manager__c); 
                    oppOldUserRegionalManagerMap.put(opp.Id, oldMap.get(opp.Id).Regional_Manager__c);                          
                }
                if(opp.Regional_Manager__c != null){
                    FollowentitySubrecords.add(new EntitySubscription(ParentId = opp.id, SubscriberId = opp.Regional_Manager__c));
                }                
                
                // Hotel Customer Care Specialist    
                if(oldMap.get(opp.Id).Hotel_Customer_Care_Specialist__c != null){
                    UnfollowersSubscriberId.add(oldMap.get(opp.Id).Hotel_Customer_Care_Specialist__c);
                    unFollowersClaimId.add(opp.id); 
                    deleteRecordUserMatchSet.add(opp.id+''+oldMap.get(opp.Id).Hotel_Customer_Care_Specialist__c);
                    oppOldUserHotelCustomerCareSpecialistMap.put(opp.Id, oldMap.get(opp.Id).Hotel_Customer_Care_Specialist__c);
                }
                if(opp.Hotel_Customer_Care_Specialist__c != null){
                    FollowentitySubrecords.add(new EntitySubscription(ParentId = opp.id, SubscriberId = opp.Hotel_Customer_Care_Specialist__c));                        
                }
                
                // Housing Coordinator    
                if(oldMap.get(opp.Id).Housing_Coordinator__c != null){
                    UnfollowersSubscriberId.add(oldMap.get(opp.Id).Housing_Coordinator__c);
                    unFollowersClaimId.add(opp.id); 
                    deleteRecordUserMatchSet.add(opp.id+''+oldMap.get(opp.Id).Housing_Coordinator__c);
                    oppOldUserHousingCoordinatorMap.put(opp.Id, oldMap.get(opp.Id).Housing_Coordinator__c);
                } 
                if(opp.Housing_Coordinator__c != null){
                    FollowentitySubrecords.add(new EntitySubscription(ParentId = opp.id, SubscriberId = opp.Housing_Coordinator__c));
                } 
                    
            }
                                                                    
    }
    
    
    if(Trigger.isUpdate){    
        // Changing the followers in SR level
        list<ServiceRequest__c> SRRecords = [select id,opportunity__r.Initial_Service_Request__c,opportunity__r.Hotel_Customer_Care_Specialist__c,opportunity__c from ServiceRequest__c where opportunity__c in: oppId AND opportunity__r.Initial_Service_Request__c ='Hotel'];
        list<Placement__c>  PcRecords = [select id,opportunity__c,ServiceRequest__c,opportunity__r.Initial_Service_Request__c,opportunity__r.Hotel_Customer_Care_Specialist__c,opportunity__r.Area_Specialist__c,opportunity__r.Regional_Manager__c,opportunity__r.Customer_Care_Specialist__c,Status__c from Placement__c where opportunity__c in: oppId AND opportunity__r.Initial_Service_Request__c ='Housing'];
        
        // Changing the follower in Hotel Level
        for(ServiceRequest__c SR: SRRecords ){
            if(SR.opportunity__r.Initial_Service_Request__c == 'Hotel' && SR.opportunity__r.Hotel_Customer_Care_Specialist__c <> null){
                
                if(oppOldUserHotelCustomerCareSpecialistMap.keySet().contains(SR.opportunity__c)){   
                    unFollowersClaimId.add(SR.id);
                    deleteRecordUserMatchSet.add(SR.id+''+oppOldUserHotelCustomerCareSpecialistMap.get(SR.opportunity__c));  
                }
                FollowentitySubrecords.add(new EntitySubscription(ParentId = SR.id, SubscriberId = SR.opportunity__r.Hotel_Customer_Care_Specialist__c));
            }
            
        }
        
        // Changing the followers in Housing Level
        for(Placement__c pc: PcRecords ){
            if(pc.opportunity__r.Initial_Service_Request__c == 'Housing' && pc.opportunity__r.Regional_Manager__c <> null && pc.Status__c  != 'Moved-In'){
                if(oppOldUserRegionalManagerMap.keySet().contains(pc.opportunity__c)){      
                    unFollowersClaimId.add(PC.ServiceRequest__c);
                    deleteRecordUserMatchSet.add(PC.ServiceRequest__c+''+oppOldUserRegionalManagerMap.get(pc.opportunity__c));
                }
                    
                FollowentitySubrecords.add(new EntitySubscription(ParentId = PC.ServiceRequest__c, SubscriberId = PC.opportunity__r.Regional_Manager__c ));
            }
            if(pc.opportunity__r.Initial_Service_Request__c == 'Housing' && pc.opportunity__r.Area_Specialist__c <> null && pc.Status__c  != 'Moved-In'){
                if(oppOldUserAreaSpecialistMap.keySet().contains(pc.opportunity__c)){      
                    unFollowersClaimId.add(PC.ServiceRequest__c);
                    deleteRecordUserMatchSet.add(PC.ServiceRequest__c+''+oppOldUserAreaSpecialistMap.get(pc.opportunity__c));
                }
                
                FollowentitySubrecords.add(new EntitySubscription(ParentId = PC.ServiceRequest__c, SubscriberId = PC.opportunity__r.Area_Specialist__c ));
            }
            if(pc.opportunity__r.Initial_Service_Request__c == 'Housing' && pc.opportunity__r.Customer_Care_Specialist__c<> null && pc.Status__c  == 'Moved-In'){
                if(oppOldUserCustomerCareSpecialistMap.keySet().contains(pc.opportunity__c)){      
                    unFollowersClaimId.add(PC.ServiceRequest__c);
                    deleteRecordUserMatchSet.add(PC.ServiceRequest__c+''+oppOldUserCustomerCareSpecialistMap.get(pc.opportunity__c));
                }
                
                FollowentitySubrecords.add(new EntitySubscription(ParentId = PC.ServiceRequest__c, SubscriberId = PC.opportunity__r.Customer_Care_Specialist__c));
            }
            
        }
             
    }
       
       for(EntitySubscription eSub : [select id, parentId, SubscriberId from EntitySubscription where parentId in:unFollowersClaimId AND SubscriberId in:UnfollowersSubscriberId]){
           
           String concatStr = eSub.parentId + '' + eSub.SubscriberId;
           if(deleteRecordUserMatchSet.contains(concatStr))
              UnfollowentitySubrecords.add(eSub); 
           
       }
       
       if(!UnfollowentitySubrecords.IsEmpty())
            Database.Delete(UnfollowentitySubrecords,false);
        
       
            
        if(!FollowentitySubrecords.IsEmpty()) 
            Database.Insert(FollowentitySubrecords,false);
        
   }
  // We calling from Claim_CopyAddressToPolicyholderAccountAndContact After insert and After update
   /* public static void Claim_CopyAddressToPolicyholderAccountAndContact(list<Opportunity> claims, Map<Id,Opportunity> oldOppMap)
    {
        set<Id> contactIds = new set<Id>();
        map<Id, Id> accountIdsByContactId = new map<Id, Id>();
        map<Id, Account> accountsByContactId = new map<Id, Account>();
        
        for (Opportunity o : claims)
        {
        if (Trigger.isInsert || (Trigger.isUpdate && oldOppMap.get(o.Id).Policyholder__c == null))
            contactIds.add(o.Policyholder__c);
        }
             map<Id, Contact> contactsById = new map<Id, Contact>([select Id, AccountId from Contact where Id in :contactIds]);
        for (Contact c : contactsById.values()) {
            accountIdsByContactId.put(c.Id, c.AccountId);
        }
            map<Id, Account> accountsById = new map<Id, Account>([select Id from Account where Id in :accountIdsByContactId.values()]);
        for (Opportunity o : claims) {
        Contact c = contactsById.get(o.Policyholder__c);
        if (c != null) {
            c.MailingPostalCode = o.Damaged_Property_Zip__c;
            c.MailingState = o.Damaged_Property_State__c;
            c.MailingCountry = o.Damaged_Property_Country__c;
            c.MailingCity = o.Damaged_Property_City__c;
            c.MailingStreet = o.Damaged_Property_Address__c;
            
            Account a = accountsById.get(accountIdsByContactId.get(c.Id));
            if (a != null) {
                a.BillingPostalCode = o.Damaged_Property_Zip__c;
                a.BillingState = o.Damaged_Property_State__c;
                a.BillingCountry = o.Damaged_Property_Country__c;
                a.BillingCity = o.Damaged_Property_City__c;
                a.BillingStreet = o.Damaged_Property_Address__c;
            }   
        }
    } 
    update accountsById.values();
    update contactsById.values();   
  }*/
}