src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Active - potential of doing business
Inactive - not able to do business
No Longer with Company</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>No Longer with Company</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_FRV_Claims__c</fullName>
        <inlineHelpText>Total called in FRV claims</inlineHelpText>
        <label>Total FRV Claims</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Finders_Fees_Claims__c</fullName>
        <inlineHelpText>Total called in Finder Fees claims</inlineHelpText>
        <label>Total Finder&apos;s Fees Claims</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Hotel_Claims__c</fullName>
        <description>Total called in hotel claims</description>
        <inlineHelpText>Total called in hotel claims</inlineHelpText>
        <label>Total Hotel Claims</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Housing_Claims__c</fullName>
        <description>Total called in housing claims</description>
        <inlineHelpText>Total called in housing claims</inlineHelpText>
        <label>Total Housing Claims</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <recordTypes>
        <fullName>Adjuster</fullName>
        <active>true</active>
        <description>All contacts that work in the Insurance Industry. Includes Company Adjusters, Independent Adjusters, Public Adjusters, Supervisors, Managers, Procurement etc.</description>
        <label>Adjuster</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Adjuster_Changed_Date__c</fullName>
        <label>Adjuster Changed Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Adjuster__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The adjuster must already be a contact in the system.</inlineHelpText>
        <label>Adjuster</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Adjuster</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Claims (Adjuster)</relationshipLabel>
        <relationshipName>Opportunities2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Called_In_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Called In By</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities (Called In By)</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Care_Specialist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Care Specialist</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Damaged_Property_Address__c</fullName>
        <label>Damaged Property Address</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Damaged_Property_City__c</fullName>
        <label>Damaged Property City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Damaged_Property_Country__c</fullName>
        <label>Damaged Property Country</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Damaged_Property_State__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>USA</fullName>
                </value>
                <value>
                    <fullName>CAN</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Damaged_Property_State__c</fullName>
        <label>Damaged Property State/Province</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DC</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
                <value>
                    <fullName>MN</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
                <value>
                    <fullName>MS</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
                <value>
                    <fullName>NC</fullName>
                </value>
                <value>
                    <fullName>ND</fullName>
                </value>
                <value>
                    <fullName>NE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Damaged_Property_Type__c</fullName>
        <label>Damaged Property Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Apartment</fullName>
                </value>
                <value>
                    <fullName>Condo</fullName>
                </value>
                <value>
                    <fullName>House</fullName>
                </value>
                <value>
                    <fullName>Mobile Home</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Townhouse</fullName>
                </value>
                <value>
                    <fullName>Travel Trailer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Damaged_Property_Zip__c</fullName>
        <label>Damaged Property Zip/Postal Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Hotel_Customer_Care_Specialist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Hotel Customer Care Specialist</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Initial_Service_Request__c</fullName>
        <label>Initial Service Request</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Housing</fullName>
                </value>
                <value>
                    <fullName>Hotel</fullName>
                </value>
                <value>
                    <fullName>FRV</fullName>
                </value>
                <value>
                    <fullName>Furniture Only</fullName>
                </value>
                <value>
                    <fullName>Unfurnished</fullName>
                </value>
                <value>
                    <fullName>Trailer-Mobile Home</fullName>
                </value>
                <value>
                    <fullName>Commercial</fullName>
                </value>
                <value>
                    <fullName>Finders Fees</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Policy_Type__c</fullName>
        <label>Policy Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Commercial</fullName>
                </value>
                <value>
                    <fullName>Condo</fullName>
                </value>
                <value>
                    <fullName>Homeowner</fullName>
                </value>
                <value>
                    <fullName>Renters</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Regional_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Relationship Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type_of_Loss__c</fullName>
        <label>Type of Loss</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CAT</fullName>
                </value>
                <value>
                    <fullName>Fire</fullName>
                </value>
                <value>
                    <fullName>Mold</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Tornado</fullName>
                </value>
                <value>
                    <fullName>Water</fullName>
                </value>
                <value>
                    <fullName>Wind</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/AdjusterClaimsTest.cls
@isTest
private class AdjusterClaimsTest 
{
    
    static testMethod void testSchedulers() 
    {
       SchedulableContext sc;
       AdjusterClaimsScheduler acs =  new AdjusterClaimsScheduler();
       acs.execute(sc);
       AdjusterClaimsClearScheduler accs =  new AdjusterClaimsClearScheduler();
       accs.execute(sc);
    }


    static testMethod void testAdjusterClaimsBatch() 
    {
        Contact contact1 = new Contact(
                    RecordTypeId = RecordTypeHelper.adjusterContactRT(),
                    FirstName='Test',
                    LastName = 'Adjuster',
                    Status__c='Active',
                    MailingCountry ='USA',
                    MailingState = 'CT',
                    MailingStreet = '134 Laurel',
                    MailingCity = 'Mineola',
                    MailingPostalCode = '11501');
        insert contact1; 

        Contact contact2 = new Contact(
                    RecordTypeId = RecordTypeHelper.adjusterContactRT(),
                    FirstName='Test',
                    LastName = 'Adjuster',
                    Status__c='Active',
                    MailingCountry ='USA',
                    MailingState = 'CT',
                    MailingStreet = '134 Laurel',
                    MailingCity = 'Mineola',
                    MailingPostalCode = '11501');
        insert contact2; 

        Contact contact3 = new Contact(
                    RecordTypeId = RecordTypeHelper.adjusterContactRT(),
                    FirstName='Test',
                    LastName = 'Adjuster',
                    Status__c='Active',
                    MailingCountry ='USA',
                    MailingState = 'CT',
                    MailingStreet = '134 Laurel',
                    MailingCity = 'Mineola',
                    MailingPostalCode = '11501');
        insert contact3; 
        
        Contact contact4 = new Contact(
                    RecordTypeId = RecordTypeHelper.adjusterContactRT(),
                    FirstName='Test',
                    LastName = 'Adjuster',
                    Status__c='Active',
                    MailingCountry ='USA',
                    MailingState = 'CT',
                    MailingStreet = '134 Laurel',
                    MailingCity = 'Mineola',
                    MailingPostalCode = '11501');
        insert contact4; 

        // Insert Users
        Profile p = [SELECT Id FROM Profile WHERE Name='Operations User']; 
        User user1 = new User
                (   
                    Alias = 'opsusr',
                    Email='operationsuser@testorg.com', 
                    EmailEncodingKey='UTF-8', 
                    LastName='Testing', 
                    LanguageLocaleKey='en_US',
                    LocaleSidKey='en_US', 
                    ProfileId = p.Id, 
                    TimeZoneSidKey='America/Los_Angeles', 
                    UserName='operationsuser@crstemphousing.com');
        insert user1; 
  
        List <Opportunity> opportunities = new List<Opportunity>(); 
        String isr = 'Hotel';
        Id contactId = contact1.Id;      
        
        for(integer i = 0; i<40; i++)
        {
            if(i==10)
            {
                isr = 'Housing';
                contactId = contact2.Id;
            }
            if(i==20)
            {
                isr = 'FRV';
                 contactId = contact3.Id;
            }
            if(i==30)
            {
                isr = 'Finders Fees';
                 contactId = contact4.Id;
            }
        
            Opportunity opportunity = new Opportunity(
                    Name='testAccount',
                    Adjuster__c = contactId,
                    Called_In_By__c = contactId,
                    Initial_Service_Request__c=isr,
                    StageName = 'Submitted',
                    CloseDate = Date.newInstance(2010,12,10),
                    Type_of_Loss__c = 'Mold',
                    Damaged_Property_Type__c = 'Apartment',
                    Damaged_Property_Address__c = '134 Laurel',
                    Damaged_Property_City__c = 'Mineola',
                    Damaged_Property_State__c = 'CT',
                    Damaged_Property_Zip__c = '11501',
                    Damaged_Property_Country__c = 'USA',
                    Policy_Type__c = 'Homeowner',
                    Regional_Manager__c = user1.Id,
                    Customer_Care_Specialist__c = user1.Id,
                    Hotel_Customer_Care_Specialist__c = user1.Id);
            opportunities.add(opportunity);
        }
        insert opportunities;

        Id oppId;

        for(integer i = 0; i<4; i++)
        { 

            if(i==0)
            {
                oppId = opportunities[0].Id;
                contactId = contact1.Id;
            }
            if(i==1)
            {
                oppId = opportunities[11].Id;
                contactId = contact2.Id;
            }
            if(i==2)
            {
                oppId = opportunities[21].Id;
                contactId = contact3.Id;
            }
            if(i==3)
            {
                oppId = opportunities[31].Id;
                contactId = contact4.Id;
            }

        }
              
        Test.StartTest();
        AdjusterClaims ac = new AdjusterClaims();
        ac.query = 'SELECT Id,Name,Initial_Service_Request__c,Adjuster__c,CreatedDate,Adjuster_Changed_Date__c,Called_In_By__c FROM Opportunity';
        ID batchprocessid = Database.executeBatch(ac);
        Test.StopTest();

        
        AdjusterClaimsClear acc = new AdjusterClaimsClear();
        acc.query = 'select Id from Contact where Total_Hotel_Claims__c <> null or Total_Housing_Claims__c <> null or Total_FRV_Claims__c <> null or Total_Finders_Fees_Claims__c <> null';
        batchprocessid = Database.executeBatch(acc);
        
  
    }
}