src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Total_FRV_Claims__c</fullName>
        <inlineHelpText>Total called in FRV claims</inlineHelpText>
        <label>Total FRV Claims</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Finders_Fees_Claims__c</fullName>
        <inlineHelpText>Total called in Finder Fees claims</inlineHelpText>
        <label>Total Finder&apos;s Fees Claims</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Hotel_Claims__c</fullName>
        <description>Total called in hotel claims</description>
        <inlineHelpText>Total called in hotel claims</inlineHelpText>
        <label>Total Hotel Claims</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Housing_Claims__c</fullName>
        <description>Total called in housing claims</description>
        <inlineHelpText>Total called in housing claims</inlineHelpText>
        <label>Total Housing Claims</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/AdjusterClaimsClear.cls
global class AdjusterClaimsClear implements Database.Batchable<sObject>
{
	Public String query { get; set;}  

	global database.queryLocator start(Database.BatchableContext BC)
    {
  		return database.getQueryLocator(query);   		
    }

    global void execute(Database.BatchableContext BC, list <Contact> scope) 
    {

    	for(Contact contact : scope) 
    	{
    		contact.Total_Finders_Fees_Claims__c = null;
			contact.Total_FRV_Claims__c = null;
			contact.Total_Hotel_Claims__c = null;
			contact.Total_Housing_Claims__c = null;
    	}
    	update scope;
    }

    global void finish(Database.BatchableContext ctx)
    {

    }

}