src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Claims_Document_Email__c</fullName>
        <label>Claims Document Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Claims_Document_Fax__c</fullName>
        <label>Claims Document Fax</label>
        <type>Phone</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Claims_Document_Email__c</fullName>
        <description>We are you this filed in Echo Sign Agreement Mapping</description>
        <formula>Policyholder__r.Claims_Document_Email__c</formula>
        <label>Claims Document Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Policyholder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Policyholder</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Policyholder, Adjuster Policyholder Record Type</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Claims</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Placement__c.object
<CustomObject>
    <description>Holds information about a housing placement, when the Opportunity stage is set to Moved-In, and a policy holder moves into the temporarry housing.  Besides the detail about the duration of the placement, this object is related to Cases to track any issues related to the placement.</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Claim Lookup</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Placements</relationshipLabel>
        <relationshipName>Placements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ServiceRequest__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Request</label>
        <referenceTo>ServiceRequest__c</referenceTo>
        <relationshipLabel>Placements</relationshipLabel>
        <relationshipName>Placements1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Placement</label>
    <nameField>
        <label>Placement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Placements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Searches__c.object
<CustomObject>
    <description>Used track the property and hotel searches conducted as part of the Sevice Request</description>
    <fields>
        <fullName>Hotel__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Hotel Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Hotel Accounts</value>
            </filterItems>
            <filterItems>
                <field>Account.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Searches</relationshipLabel>
        <relationshipName>Searches</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Placement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Placement</label>
        <referenceTo>Placement__c</referenceTo>
        <relationshipName>Searches</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Selected__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Selected</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Service_Request__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Service Request</label>
        <referenceTo>ServiceRequest__c</referenceTo>
        <relationshipName>Searches</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Search</label>
    <nameField>
        <displayFormat>SR-{000000}</displayFormat>
        <label>Search Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Searches</pluralLabel>
    <recordTypes>
        <fullName>Hotel</fullName>
        <active>true</active>
        <description>For Hotel Requests</description>
        <label>Hotel</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/ServiceRequest__c.object
<CustomObject>
    <description>Holds the different services that a request can include, such as: Hotel Stays, Housing requests, Furniture requests, Fair Rental Value, etc.</description>
    <fields>
        <fullName>Claims_Document_Email__c</fullName>
        <formula>Opportunity__r.Policyholder__r.Claims_Document_Email__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Claims Document Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Hotel_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Hotel Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Service Requests</relationshipLabel>
        <relationshipName>Service_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Hotel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Hotel</label>
        <referenceTo>Hotel_Room__c</referenceTo>
        <relationshipName>Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Claim</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Service Requests</relationshipLabel>
        <relationshipName>Service_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ServiceRequest__c</fullName>
        <formula>Id</formula>
        <label>ServiceRequest</label>
        <type>Text</type>
    </fields>
    <label>Service Request</label>
    <nameField>
        <displayFormat>SR#-{000000}</displayFormat>
        <label>Service Request</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Requests</pluralLabel>
    <recordTypes>
        <fullName>Hotel</fullName>
        <active>true</active>
        <description>For Hotel requests</description>
        <label>Hotel</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CCAuthFormPreviewPageController.cls
/*************************************************************************************************************
Created by: Apostletech team
Purpose: To preview CC Auth Form in pdf format(Data comes from external app) and option to send email or fax.
Class calling from a link on "Send Credit Card Authorization (CCA)" Task record
VF Page: CCAuthFormPreviewPage
*************************************************************************************************************/
public class CCAuthFormPreviewPageController
{
      public string toAddress {get;set;}
      public string subject {get;set;}
      public string emailBody{get;set;}
      public string displayIATA {get;set;}
      public string placementId {get;set;}
      Public string faxNumber {get;set;}
      
      String lastName;
      String servReqId;
      String taskId;
      Public String OwnerId; 
      
      Public CCAuthFormPreviewPageController(){
          
          lastName = '';
          servReqId = ApexPages.currentPage().getParameters().get('reqId');
          taskId = ApexPages.currentPage().getParameters().get('taskId');
          
          ServiceRequest__c serviceRequestRec = [Select Id, Opportunity__r.Policyholder__r.LastName, Claims_Document_Email__c, Hotel_Account__c from ServiceRequest__c where Id =: servReqId];
          system.debug('****************'+serviceRequestRec.id);          
          
          Set<Id> hotelAcctIds = new Set<Id>();
          for(Searches__c S : [Select Id, Hotel__c,Selected__c from Searches__c where Service_Request__c =: serviceRequestRec.id AND Hotel__c != null and Selected__c = true]){
              hotelAcctIds.add(S.Hotel__c);
          }
          
          if(!hotelAcctIds.isEmpty()){    
              List<Contact> contList = [Select Id, Claims_Document_Email__c, Claims_Document_Fax__c, LastName from Contact where accountId in: hotelAcctIds AND RecordType.Name = 'Hotel Contact' AND Name = 'Front Desk'];
              if(!contList.isEmpty()){
                  toAddress = contList[0].Claims_Document_Email__c;                  
                  faxNumber = contList[0].Claims_Document_Fax__c;
              }    
          }
          
          if(serviceRequestRec.Opportunity__r.Policyholder__r.LastName != null)    
              lastName = serviceRequestRec.Opportunity__r.Policyholder__r.LastName;
                       
          subject = 'CRS Credit Card Authorization - '+lastName;
          displayIATA = 'true';
          
          //placementId = 'a0Le0000003f0xUEAQ'; // Dummy id for testing
          
          List<Placement__c> placementList = [Select Id from Placement__c where ServiceRequest__c =: servReqId AND RecordType.Name = 'Hotel Placement' limit 1];
          if(!placementList.isEmpty()){
              placementId = placementList[0].Id;
          }
          
      }
      
      public pageReference sendEmail()
      { 
            
            pageReference pr = page.CCAuthForm;
            pr.getParameters().put('placementId',placementId);
            pr.getParameters().put('IATAFlag', displayIATA);
            Blob b;
            if (Test.IsRunningTest())
            {
                b = Blob.valueOf('UNIT.TEST');
            }
            else
            {
                b = pr.getContent();
            }
            
            
            
            //system.debug('*****attachment body*********'+pr.getContent());
            Messaging.EmailFileAttachment efa = new Messaging.EmailFileAttachment();
            efa.setContentType('application/pdf');
            efa.setFileName('CCA Auth Form.pdf');
            efa.setBody(b);
            
            string[] toaddresslist = New String[]{ toAddress}; 
            Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
            email.setToAddresses(toaddresslist);
            email.setSubject(subject);
            //email.setPlaintextbody(emailBody);
            String emailBodyString  = '<html><body>'+ emailBody + '</body></html>';
            email.setHtmlBody(emailBodyString);
            email.setFileAttachments(new Messaging.EmailFileAttachment[] {efa});
            
            Messaging.sendEmail(New Messaging.SingleEmailMessage[] {email});
            
            
            // To complete "Send Credit Card Authorization (CCA)" task on service request
            List<Task> taskList = [Select Id, Status, ownerid, Description, Sent_File_Link_URL__c from Task where Id =: taskId AND whatId =: servReqId AND Subject = 'Send Credit Card Authorization (CCA)'];
            for(Task t : taskList){
                t.Status = 'Completed';
                OwnerId = taskList[0].ownerid;       
               }
            /* Adding attachement and updating the document link for task */
            String baseUrl = System.URL.getSalesforceBaseUrl().toExternalForm();
            list<Attachment> DelAttachmentlist = [select id,name,ParentId from Attachment where ParentId=:taskId AND name = 'Credit Card Authorization (CCA)'];
            delete DelAttachmentlist;
            
            Attachment attRec = new Attachment();
            attRec.parentid = taskId;
            attRec.Name = 'Credit Card Authorization (CCA)';
            attRec.Body = b;
            attRec.OwnerId = OwnerId;
            attRec.contentType = 'application/pdf'; 
            insert attRec;
            
            system.debug(OwnerId+'&&&&&&&&&');
            if(!taskList.isEmpty()){
                taskList[0].Sent_File_Link_URL__c = baseUrl +'/servlet/servlet.FileDownload?file='+ attRec.Id;
                update taskList;
                 
            }
            
            
            PageReference pg = new PageReference('/'+servReqId);
            pg.setRedirect(true);            
            return pg;
      }
      
      Public PageReference sendFax(){
            
            pageReference pr = page.CCAuthForm;
            pr.getParameters().put('placementId',placementId);
            pr.getParameters().put('IATAFlag', displayIATA);
            Blob b;
            if (Test.IsRunningTest())
            {
                b = Blob.valueOf('UNIT.TEST');
            }
            else
            {
                b = pr.getContent();
            }
            
            Attachment attRec = new Attachment();
            attRec.parentid = taskId;
            attRec.Name = 'Credit Card Authorization (CCA)';
            attRec.Body = b; 
            attRec.contentType = 'application/pdf'; 
            
            String recepientFax = faxNumber.replaceAll('[^0-9]', '');          
            
            String sendFaxResultID = FaxApiCall.sendFax(attRec, recepientFax, subject);
            
            if(sendFaxResultID != null && sendFaxResultID != ''){
                
                // To complete "Send Credit Card Authorization (CCA)" task on service request
                List<Task> taskList = [Select Id, Status, ownerid, Description, Sent_File_Link_URL__c, Fax_Result_ID__c, Fax_Sent_User_ID__c from Task where Id =: taskId AND whatId =: servReqId AND Subject = 'Send Credit Card Authorization (CCA)'];
                for(Task t : taskList){
                    t.Status = 'Completed';
                    t.Fax_Result_ID__c = sendFaxResultID;
                    t.Fax_Sent_User_ID__c = Userinfo.getUserId();
                    OwnerId = taskList[0].ownerid;
                }
                /* Adding attachement and updating the document link for task */
                String baseUrl = System.URL.getSalesforceBaseUrl().toExternalForm();
                list<Attachment> DelAttachmentlist = [select id,name,ParentId from Attachment where ParentId=:taskId AND name = 'Credit Card Authorization (CCA)'];
                delete DelAttachmentlist;
                Attachment attRec1 = new Attachment();
                attRec1.parentid = taskId;
                attRec1.Name = 'Credit Card Authorization (CCA)';
                attRec1.Body = b;
                attRec1.OwnerId = OwnerId;
                attRec1.contentType = 'application/pdf'; 
                insert attRec1;
                if(!taskList.isEmpty()){
                    taskList[0].Sent_File_Link_URL__c = baseUrl +'/servlet/servlet.FileDownload?file='+ attRec1.Id;
                    update taskList;
                    
                    /* Scheduling after 1 minute */
                    //*********************************************************************************************     
                    
                    Datetime destTime = Datetime.now().addMinutes(1);
                               
                    String year =  String.valueOf(destTime.year());   
                    String month =  String.valueOf(destTime.month());
                    String day =  String.valueOf(destTime.day());        
                    String hour = String.valueOf(destTime.hour());
                    String min = String.valueOf(destTime.minute()); 
                    String ss = String.valueOf(destTime.second());
                    
                    String randomNumb = ''+ Math.random();
                    
                    //parse to cron expression
                    String nextFireTime = ss + ' ' + min + ' ' + hour + ' '+ day + ' ' +month+ ' ? '+year;
                    
                    FaxStatusValidateScheduler sNTVpre = new FaxStatusValidateScheduler(taskList[0].Id);                    
                    System.schedule('Fax Status Validator - '+taskList[0].Id+''+ randomNumb, nextFireTime, sNTVpre);
                    //********************************************************************************************* 
                }
                        
                PageReference pg = new PageReference('/'+servReqId);
                pg.setRedirect(true);            
                return pg;
            }
            else{                
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING,'Unable to send fax'));
                return null;
            }            
      }
      
      Public PageReference changeCommissionType(){
      
          return null;
      }
      
      public pagereference cancel()
      {
          return new PageReference('/'+servReqId);    
      }
    
}