src/objects/Extension__c.object
<CustomObject>
    <description>Extend a placement</description>
    <fields>
        <fullName>Extend_To_Date__c</fullName>
        <inlineHelpText>Enter the new approved through date if an approval is not required.</inlineHelpText>
        <label>Extend To Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Extension_Created_By__c</fullName>
        <label>Extension Created By</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Placement__c</fullName>
        <label>Placement</label>
        <referenceTo>Placement__c</referenceTo>
        <relationshipLabel>Extensions</relationshipLabel>
        <relationshipName>Extensions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Extension</label>
    <nameField>
        <displayFormat>Ext-{00000}</displayFormat>
        <label>Extension Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Extensions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Placement__c.object
<CustomObject>
    <description>Holds information about a housing placement, when the Opportunity stage is set to Moved-In, and a policy holder moves into the temporarry housing.  Besides the detail about the duration of the placement, this object is related to Cases to track any issues related to the placement.</description>
    <fields>
        <fullName>Approved_Through_Date__c</fullName>
        <label>Approved Through Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CRS_Add_On__c</fullName>
        <description>Total Furniture Deposit Billed. Set at Move-Out by Mulligan</description>
        <label>CRS Add On</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Create_NTV_Task__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field will be checked after an early move out extension if the user checks NTV required in mulligan.</description>
        <label>Create NTV Task</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FHA_Billing__c</fullName>
        <description>The FHA amount used for billing in Houston.</description>
        <label>FHA Billing</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Markup__c</fullName>
        <description>The CRS profit amount.</description>
        <label>Markup</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Monthly_Billing__c</fullName>
        <label>Monthly Billing</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Property_Rent__c</fullName>
        <description>The monthly or daily rent amount for the property.</description>
        <label>Property Rent</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Security_Deposit__c</fullName>
        <description>Security Deposit Data from Houston</description>
        <label>Security Deposit</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Checked-In</fullName>
                </value>
                <value>
                    <fullName>Checked-Out</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Moved-In</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Moved-Out</fullName>
                </value>
                <value>
                    <fullName>Pending Confirmation</fullName>
                </value>
                <value>
                    <fullName>Quote</fullName>
                </value>
                <value>
                    <fullName>Searching</fullName>
                </value>
                <value>
                    <fullName>Pending Check-In</fullName>
                </value>
                <value>
                    <fullName>Lost Opportunity</fullName>
                </value>
                <value>
                    <fullName>Viewing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Placement</label>
    <nameField>
        <label>Placement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Placements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/RESTCreateExtension.cls
@RestResource(urlMapping='/Placement/CreateExtension/*')
global with sharing class RESTCreateExtension 
{
    @HttpPost
    global static void insertExtension(String placementId, String userId, String approvedThroughDate, Boolean createNTVTask) 
    { 
         try
        {
            Placement__c placement = [select Approved_Through_Date__c,Status__c from Placement__c where Id =: placementId];
            placement.Approved_Through_Date__c = date.valueOf(approvedThroughDate);
            if (placement.Status__c == 'Moved-Out' && placement.Approved_Through_Date__c >= system.Today())
            {   
                // If the placement is moved out and extended into the future it goes back to moved in status
                placement.Status__c = 'Moved-In';
                placement.Monthly_Billing__c = null;
                placement.Property_Rent__c = null;
                placement.FHA_Billing__c = null;
                placement.Markup__c = null;
                placement.CRS_Add_On__c = null;
                placement.Security_Deposit__c = null;
            }
            else
            {   
                placement.Create_NTV_Task__c = createNTVTask;
                if (placement.Status__c == 'Moved-In' && placement.Approved_Through_Date__c < system.Today())
                {   
                    // If the placement is moved in and extended into the past it goes to moved out status
                    placement.Status__c = 'Moved-Out';
                }
            }
            update placement;
        }
        catch (Exception e)
        {
             Util.sendErrorEmail('Unable to update the Approved Through Date on Placement','ERROR: ' + e + ' returned updating placement Id ' + placementId);       
        }
        
        try
        {
            Extension__c extension = new Extension__c(); 
            extension.Placement__c = placementId;
            extension.Extend_To_Date__c = date.valueOf(approvedThroughDate);
            
            User user = new User();
            try
            {
                user = [select FirstName,LastName from User where id =: userId];
            }
            catch (Exception e)
            {
                user.FirstName = 'Unknown';
                user.LastName = 'User';
            }
        
            extension.Extension_Created_By__c = (user.FirstName + ' ' + user.LastName);
            
            insert extension;       
            
        }
        catch (Exception e)
        {
             Util.sendErrorEmail('Unable to create Extension for Placement','ERROR: ' + e + ' returned creating extension for placement Id ' + placementId);        
        }
        
        
    }   
}