src/objects/Hotel_Room__c.object
<CustomObject>
    <description>Holds the information related to a Hotel Booking.</description>
    <fields>
        <fullName>Booking_Status__c</fullName>
        <label>Booking Status</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IATA_Collected__c</fullName>
        <defaultValue>0</defaultValue>
        <label>IATA Collected</label>
        <precision>9</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Payment_Status__c</fullName>
        <label>Payment Status</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <label>Hotel Room</label>
    <nameField>
        <displayFormat>Room-{00000}</displayFormat>
        <label>Hotel Room</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hotel Rooms</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/RestUpdateHotelRoomIATA.cls
@RestResource(urlMapping='/HotelRoom/UpdateHotolRoomIATA/*')
global with sharing class RestUpdateHotelRoomIATA  
{
    @HttpPatch
    global static String updateHotelRoomIATA(string hotelRoomId, Double collected,String bookingStatus,String paymentStatus)   
    { 
        try
        {
              Hotel_Room__c hotelRoom = [SELECT Id,IATA_Collected__c,Booking_Status__c,Payment_Status__c from Hotel_Room__c WHERE Id =: hotelRoomId]; 
              hotelRoom.IATA_Collected__c = collected;
              hotelRoom.Booking_Status__c = bookingStatus;
              hotelRoom.Payment_Status__c = paymentStatus;              
              update hotelRoom;
              return 'IATA updated for hotel room id ' + hotelRoomId;
        }
        catch (Exception e)
        {
           Util.sendErrorEmail('IATA Update error','ERROR: ' + e + ' returned updating the IATA information for hotel room id' + hotelRoomId);       
           return 'IATA update failed for hotel room id ' + hotelRoomId;
        }
    }
}