src/objects/Hotel_Room__c.object
<CustomObject>
    <description>Holds the information related to a Hotel Booking.</description>
    <fields>
        <fullName>Check_In__c</fullName>
        <label>Check-In Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Confirmation__c</fullName>
        <label>Confirmation #</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Estimated_Check_Out_Date__c</fullName>
        <description>The current estimated check-out date</description>
        <label>Estimated Check-Out Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Hotel_Nightly_Rate__c</fullName>
        <description>The night rate not including tax.</description>
        <inlineHelpText>The hotel nightly rate not including tax.</inlineHelpText>
        <label>Hotel Nightly Rate</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Itemized_Tax__c</fullName>
        <inlineHelpText>Enter the hotel&apos;s tax rate percent.</inlineHelpText>
        <label>Itemized Tax Percentage</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Kitchen_Features__c</fullName>
        <label>Kitchen Features</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Full Kitchen</fullName>
                </value>
                <value>
                    <fullName>Kitchenette</fullName>
                </value>
                <value>
                    <fullName>Microwave/Refrigerator</fullName>
                </value>
                <value>
                    <fullName>Microwave Only</fullName>
                </value>
                <value>
                    <fullName>No Cooking Facilities</fullName>
                </value>
                <value>
                    <fullName>Refrigerator Only</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Room_Type__c</fullName>
        <label>Room Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>One Bedroom Suite</fullName>
                </value>
                <value>
                    <fullName>Pet Boarding</fullName>
                </value>
                <value>
                    <fullName>Standard Double</fullName>
                </value>
                <value>
                    <fullName>Standard King</fullName>
                </value>
                <value>
                    <fullName>Standard Queen</fullName>
                </value>
                <value>
                    <fullName>Studio Suite</fullName>
                </value>
                <value>
                    <fullName>Three Bedroom Suite</fullName>
                </value>
                <value>
                    <fullName>Two Bedroom Suite</fullName>
                </value>
                <value>
                    <fullName>Vacation Rental</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Hotel Room</label>
    <nameField>
        <displayFormat>Room-{00000}</displayFormat>
        <label>Hotel Room</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hotel Rooms</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/RESTUpdateHotelRoomTest.cls
@isTest
private class RESTUpdateHotelRoomTest {

    static testMethod void myUnitTest() {
        
        Hotel_Room__c hr = new Hotel_Room__c();
        hr.Room_Type__c = 'Standard Double';
        hr.Kitchen_Features__c = 'Kitchenette';
        hr.Confirmation__c = '123';
        hr.Check_In__c = Date.newInstance(2011,7,1);
        hr.Estimated_Check_Out_Date__c = Date.newInstance(2011,7,11);
        hr.Hotel_Nightly_Rate__c = 100.00;
        hr.Itemized_Tax__c = 10;
        
        insert hr;
        
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        if (UserInfo.getOrganizationId() == '00D70000000JTmAEAW')
        {
            // production endpoint
            req.requestURI = 'https://login.salesforce.com/services/apexrest/HotelRoom/UpdateHotelRoom/' + hr.Id;
        }
        else
        {
            // test endpoint
            req.requestURI = 'https://test.salesforce.com/services/apexrest/HotelRoom/UpdateHotelRoom/' + hr.Id;
        }
        req.httpMethod = 'PATCH';
        
       
        string expectedresult = hr.Id + ' Updated';
                
        RestContext.request = req;
		RestContext.response = res;
		
		string petFeeType = 'Daily';
		string parkingFeeType = 'Daily';
		string otherFeeType = 'Daily';
		string otherFeeDescription = 'Exta bed'; 
		double avgCostRate = 100.00;
		double avgPriceRate = 120.00;
		double crsRoomRatePrice = 140.00;
		double hotelNightlyRate = 130.00;
		double avgRoomRateWithoutTaxandFees = 100.00;
		double itemizedTax = 12;
		double totalUnbilled = 2000.00;
		double petFeeAmount = 10.00;
		double parkingFeeAmount = 10.00;
		double otherFeeAmount = 10.00;
    	boolean oneTimePetFeesTaxable = true;
    	boolean oneTimeParkingFeesTaxable = false; 
    	boolean oneTimeOtherFeesTaxable = true;
    	string userId = [select id from User where alias = 'extapi'].id; 
    	
		String results = RESTUpdateHotelRoom.updateHotelRoom(req,avgCostRate,avgPriceRate,crsRoomRatePrice,hotelNightlyRate,avgRoomRateWithoutTaxandFees,
															 itemizedTax,totalUnbilled,petFeeType,petFeeAmount,oneTimePetFeesTaxable,parkingFeeType,parkingFeeAmount,
															 oneTimeParkingFeesTaxable,otherFeeType,otherFeeAmount,oneTimeOtherFeesTaxable,otherFeeDescription,userId);
		System.assertEquals(expectedresult,results);
		
		
		//setup request with bad data to cover exceptions 

		petFeeType = '';
		parkingFeeType = '';
		otherFeeType = '';
		userId = '123';
		
		results = RESTUpdateHotelRoom.updateHotelRoom(req,avgCostRate,avgPriceRate,crsRoomRatePrice,hotelNightlyRate,avgRoomRateWithoutTaxandFees,
			                                          itemizedTax,totalUnbilled,petFeeType,petFeeAmount,oneTimePetFeesTaxable,parkingFeeType,parkingFeeAmount,
			                                          oneTimeParkingFeesTaxable,otherFeeType,otherFeeAmount,oneTimeOtherFeesTaxable,otherFeeDescription,userId);
		System.assertEquals(expectedresult,results);
	
	}
}