src/objects/Hotel_Room__c.object
<CustomObject>
    <description>Holds the information related to a Hotel Booking.</description>
    <fields>
        <fullName>Cancellation_del__c</fullName>
        <label>Cancellation #</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CheckOut__c</fullName>
        <label>Check-Out Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Check_In__c</fullName>
        <label>Check-In Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Confirmation__c</fullName>
        <label>Confirmation #</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Estimated_Check_Out_Date__c</fullName>
        <description>The current estimated check-out date</description>
        <label>Estimated Check-Out Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Placement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Placement</label>
        <referenceTo>Placement__c</referenceTo>
        <relationshipLabel>Hotel Rooms</relationshipLabel>
        <relationshipName>Hotel_Rooms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Room_Type__c</fullName>
        <label>Room Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>One Bedroom Suite</fullName>
                </value>
                <value>
                    <fullName>Pet Boarding</fullName>
                </value>
                <value>
                    <fullName>Standard Double</fullName>
                </value>
                <value>
                    <fullName>Standard King</fullName>
                </value>
                <value>
                    <fullName>Standard Queen</fullName>
                </value>
                <value>
                    <fullName>Studio Suite</fullName>
                </value>
                <value>
                    <fullName>Three Bedroom Suite</fullName>
                </value>
                <value>
                    <fullName>Two Bedroom Suite</fullName>
                </value>
                <value>
                    <fullName>Vacation Rental</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Hotel Room</label>
    <nameField>
        <displayFormat>Room-{00000}</displayFormat>
        <label>Hotel Room</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hotel Rooms</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Placement__c.object
<CustomObject>
    <description>Holds information about a housing placement, when the Opportunity stage is set to Moved-In, and a policy holder moves into the temporarry housing.  Besides the detail about the duration of the placement, this object is related to Cases to track any issues related to the placement.</description>
    <fields>
        <fullName>Credit_Card_Number__c</fullName>
        <label>Credit Card Number</label>
        <length>16</length>
        <maskChar>X</maskChar>
        <maskType>creditCard</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>Credit_Card_Type__c</fullName>
        <label>Credit Card Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Visa</fullName>
                </value>
                <value>
                    <fullName>Direct Bill</fullName>
                </value>
                <value>
                    <fullName>vPay</fullName>
                </value>
                <value>
                    <fullName>Mastercard</fullName>
                </value>
                <value>
                    <fullName>American Express</fullName>
                </value>
                <value>
                    <fullName>Visa PayNet</fullName>
                </value>
                <value>
                    <fullName>Chase Visa</fullName>
                </value>
                <value>
                    <fullName>Check</fullName>
                </value>
                <value>
                    <fullName>PayNet</fullName>
                </value>
                <value>
                    <fullName>PayNet ID Copy</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Estimated_Check_Out_Date__c</fullName>
        <defaultValue>TODAY() + 365</defaultValue>
        <label>Estimated Check-Out Date</label>
        <type>Date</type>
    </fields>
    <label>Placement</label>
    <nameField>
        <label>Placement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Placements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/UpdatePlacementTest.cls
@isTest
private class UpdatePlacementTest {

    static testMethod void myUnitTest() {
        
        // Insert placement
        Placement__c placement1 = new Placement__c(
                                      RecordTypeId = RecordTypeHelper.hotelPlacementRT(),
                                      Credit_Card_Type__c = 'vPay',
                                      Credit_Card_Number__c = '370268023664444',
                                      Name = 'testPlacementx');
                                        
        insert placement1;
        
         Hotel_Room__c hotelRoom1 = new Hotel_Room__c
                (
                    placement__c = placement1.Id,
                    Room_Type__c = 'Standard Double',
                    Confirmation__c = '123',
                    Check_In__c = Date.newInstance(2013,12,10),
                    Estimated_Check_Out_Date__c = Date.newInstance(2014,12,10));
                    
        insert hotelRoom1;
        
        Hotel_Room__c hotelRoom2 = new Hotel_Room__c
                (
                    placement__c = placement1.Id,
                    Room_Type__c = 'Standard Double',
                    Confirmation__c = '123',
                    Check_In__c = Date.newInstance(2013,11,10),
                    Estimated_Check_Out_Date__c = Date.newInstance(2014,12,14));
                    
        insert hotelRoom2;
        
        hotelRoom1.Cancellation_del__c = '123';
        update hotelRoom1;
        
        hotelRoom2.Cancellation_del__c = '123';
        update hotelRoom2;
        
        Hotel_Room__c hotelRoom3 = new Hotel_Room__c
                (
                    placement__c = placement1.Id,
                    Room_Type__c = 'Standard Double',
                    Confirmation__c = '123',
                    Check_In__c = Date.newInstance(2014,01,10),
                    Estimated_Check_Out_Date__c = Date.newInstance(2014,06,10));
                    
        insert hotelRoom3;
        
        hotelRoom3.CheckOut__c = Date.newInstance(2014,02,1);
        update hotelRoom3;
        
         Hotel_Room__c hotelRoom4 = new Hotel_Room__c
                (
                    placement__c = placement1.Id,
                    Room_Type__c = 'Standard Double',
                    Confirmation__c = '123',
                    Check_In__c = Date.newInstance(2014,01,1),
                    Estimated_Check_Out_Date__c = Date.newInstance(2016,07,10));
                    
        insert hotelRoom4;
                    
        hotelRoom4.CheckOut__c = Date.Today();
        update hotelRoom4;
        
    }
    
    static testMethod void myUnitTest2() {
    	 
        // Insert placement
        Placement__c placement2 = new Placement__c(
                                      RecordTypeId = RecordTypeHelper.hotelPlacementRT(),
                                      Credit_Card_Type__c = 'PayNet',
                                      Credit_Card_Number__c = '370268023664444',
                                      Name = 'testPlacementx');
                                        
        insert placement2;
        
        
        Hotel_Room__c hotelRoom5 = new Hotel_Room__c
                (
                    placement__c = placement2.Id,
                    Room_Type__c = 'Standard Double',
                    Confirmation__c = '123',
                    Check_In__c = Date.newInstance(2014,01,1),
                    Estimated_Check_Out_Date__c = Date.newInstance(2014,07,10));
                    
        insert hotelRoom5;
        
        hotelRoom5.Cancellation_del__c = '123';
        update hotelRoom5;
        
        Hotel_Room__c hotelRoom6 = new Hotel_Room__c
                (
                    placement__c = placement2.Id,
                    Room_Type__c = 'Standard Double',
                    Confirmation__c = '123',
                    Check_In__c = Date.newInstance(2014,01,1),
                    Estimated_Check_Out_Date__c = Date.newInstance(2014,07,10));
                    
        insert hotelRoom6;
        
        hotelRoom6.CheckOut__c = Date.Today();
        update hotelRoom6;
    	
    	
    }
}