src/objects/Hotel_Room__c.object
<CustomObject>
    <description>Holds the information related to a Hotel Booking.</description>
    <fields>
        <fullName>Average_Room_Rate_Without_Taxes_and_Fees__c</fullName>
        <label>Average Room Rate Without Taxes and Fees</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Avg_Cost_Rate__c</fullName>
        <label>Avg Cost Rate</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Avg_Price_Rate__c</fullName>
        <label>Avg Price Rate</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CRS_Room_Rate_Price__c</fullName>
        <label>CRS Room Rate Price</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Hotel_Nightly_Rate__c</fullName>
        <description>The night rate not including tax.</description>
        <inlineHelpText>The hotel nightly rate not including tax.</inlineHelpText>
        <label>Hotel Nightly Rate</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Itemized_Tax__c</fullName>
        <inlineHelpText>Enter the hotel&apos;s tax rate percent.</inlineHelpText>
        <label>Itemized Tax Percentage</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>One_Time_Other_Fees_Taxable__c</fullName>
        <defaultValue>false</defaultValue>
        <label>One Time Other Fees Taxable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>One_Time_Parking_Fees_Taxable__c</fullName>
        <defaultValue>false</defaultValue>
        <label>One Time Parking Fees Taxable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>One_Time_Pet_Fees_Taxable__c</fullName>
        <defaultValue>false</defaultValue>
        <label>One Time Pet Fees Taxable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Other_Fee_Amount__c</fullName>
        <label>Other Fee Amount</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Other_Fee_Description__c</fullName>
        <label>Other Fee Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Other_Fee_Type__c</fullName>
        <label>Other Fee Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Other_Fee_cb__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Daily</fullName>
                </value>
                <value>
                    <fullName>One-time</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Other_Fee_cb__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Other Fee</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Parking_Fee_Amount__c</fullName>
        <label>Parking Fee Amount</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Parking_Fee_Type__c</fullName>
        <label>Parking Fee Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Parking_Fee_cb__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Daily</fullName>
                </value>
                <value>
                    <fullName>One-time</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Parking_Fee_cb__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Parking Fee</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Pet_Fee_Amount__c</fullName>
        <label>Pet Fee Amount</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Pet_Fee_Type__c</fullName>
        <label>Pet Fee Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Pet_Fee_cb__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Daily</fullName>
                </value>
                <value>
                    <fullName>One-time</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Pet_Fee_cb__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Pet Fee</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RC_Last_Modified_By_Id__c</fullName>
        <label>RC Last Modified By Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RC_Last_Modified_By__c</fullName>
        <label>RC Last Modified By</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_Unbilled__c</fullName>
        <label>Total Unbilled</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Hotel Room</label>
    <nameField>
        <displayFormat>Room-{00000}</displayFormat>
        <label>Hotel Room</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hotel Rooms</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/RESTUpdateHotelRoom.cls
@RestResource(urlMapping='/HotelRoom/UpdateHotelRoom/*')
global class RESTUpdateHotelRoom 
{
  @HttpPatch
  global static String updateHotelRoom(RestRequest req, Double avgCostRate , Double avgPriceRate, Double crsRoomRatePrice, Double hotelNightlyRate, Double avgRoomRateWithoutTaxandFees,
                                                        Double itemizedTax, Double totalUnbilled, string petFeeType, Double petFeeAmount,Boolean oneTimePetFeesTaxable, String parkingFeeType, 
                                                        Double parkingFeeAmount, Boolean oneTimeParkingFeesTaxable, String otherFeeType, Double otherFeeAmount, Boolean oneTimeOtherFeesTaxable, 
                                                        String otherFeeDescription, String userId) 
  {
      string roomId = req.RequestURI.substring(req.requestURI.lastIndexOf('/')+1);
            
      Hotel_Room__c hr = [SELECT Id from Hotel_Room__c WHERE Id =: roomId];
       
      
      hr.Avg_Cost_Rate__c = avgCostRate;
      hr.Avg_Price_Rate__c = avgPriceRate;
      hr.CRS_Room_Rate_Price__c = crsRoomRatePrice;
      hr.Hotel_Nightly_Rate__c = hotelNightlyRate;
      hr.Average_Room_Rate_Without_Taxes_and_Fees__c = avgRoomRateWithoutTaxandFees;
      hr.Itemized_Tax__c = itemizedTax;
      hr.Total_Unbilled__c = totalUnbilled;
     
     	hr.Pet_Fee_cb__c = true;
     	hr.Pet_Fee_Type__c = petFeeType;
     	hr.Pet_Fee_Amount__c = petFeeAmount;
     	hr.One_Time_Pet_Fees_Taxable__c = oneTimePetFeesTaxable;
      if (hr.Pet_Fee_Type__c != '')
      {
      	hr.Pet_Fee_cb__c = true;
      }
      else
      {
      	hr.Pet_Fee_cb__c = false;
      }
      
      hr.Parking_Fee_Type__c = parkingFeeType;
      hr.Parking_Fee_Amount__c = parkingFeeAmount;
      hr.One_Time_Parking_Fees_Taxable__c = oneTimeParkingFeesTaxable;
    	if (hr.Parking_Fee_Type__c != '')
   		{
    		hr.Parking_Fee_cb__c = true;
    	}
    	else
    	{
        hr.Parking_Fee_cb__c = false;
      }
    
   		hr.Other_Fee_Type__c = otherFeeType;
   		hr.Other_Fee_Amount__c = otherFeeAmount;
   		hr.One_Time_Other_Fees_Taxable__c = oneTimeOtherFeesTaxable;
   		hr.Other_Fee_Description__c = otherFeeDescription;
    	if (hr.Other_Fee_Type__c != '')
    	{
    		hr.Other_Fee_cb__c = true;
    	}
    	else
    	{
        	hr.Other_Fee_cb__c = false; 
      }
      if (userId.length() > 0)
      {
        User user = new User();
        try
        {
        	user = [select FirstName,LastName from User where id =: userId];
        }
        catch (Exception e)
        {
        	user.FirstName = 'Unknown';
        	user.LastName = 'User';
        }
    
        system.debug(userId);      
  			
        hr.RC_Last_Modified_By__c = (user.FirstName + ' ' + user.LastName + ', ' + system.now().format('M/d/yyyy h:mm a'));
        if (userId.length() == 18)
        {
          hr.RC_Last_Modified_By_Id__c = userId;
        }
        else
        {
          hr.RC_Last_Modified_By_Id__c = '';
        }  
		  }

      update hr;
      return roomId + ' Updated';
   }
}