src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Adjuster_Changed_Date__c</fullName>
        <label>Adjuster Changed Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Adjuster__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The adjuster must already be a contact in the system.</inlineHelpText>
        <label>Adjuster</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Adjuster</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Claims (Adjuster)</relationshipLabel>
        <relationshipName>Opportunities2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Called_In_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Called In By</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities (Called In By)</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Initial_Service_Request__c</fullName>
        <label>Initial Service Request</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Housing</fullName>
                </value>
                <value>
                    <fullName>Hotel</fullName>
                </value>
                <value>
                    <fullName>FRV</fullName>
                </value>
                <value>
                    <fullName>Furniture Only</fullName>
                </value>
                <value>
                    <fullName>Unfurnished</fullName>
                </value>
                <value>
                    <fullName>Trailer-Mobile Home</fullName>
                </value>
                <value>
                    <fullName>Commercial</fullName>
                </value>
                <value>
                    <fullName>Finders Fees</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/AdjusterClaimsScheduler.cls
global class AdjusterClaimsScheduler implements Schedulable 
{
    global void execute(SchedulableContext SC) 
    {
        AdjusterClaims ac = new AdjusterClaims();
        ac.query = 'SELECT Id,Name,Initial_Service_Request__c,Adjuster__c,CreatedDate,Adjuster_Changed_Date__c,Called_In_By__c FROM Opportunity WHERE (not Name LIKE\'6%\') AND (not Name LIKE\'7%\') AND (not Name LIKE\'8%\') AND Initial_Service_Request__c in (\'Housing\',\'FRV\',\'Finders Fees\',\'Hotel\')';
        database.executebatch(ac); 
    } 
}