src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Area_Specialist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Residence Specialist</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Care_Specialist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Care Specialist</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Hotel_Customer_Care_Specialist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Hotel Customer Care Specialist</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Housing_Coordinator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Residence Coordinator</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Initial_Service_Request__c</fullName>
        <label>Initial Service Request</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Housing</fullName>
                </value>
                <value>
                    <fullName>Hotel</fullName>
                </value>
                <value>
                    <fullName>FRV</fullName>
                </value>
                <value>
                    <fullName>Furniture Only</fullName>
                </value>
                <value>
                    <fullName>Unfurnished</fullName>
                </value>
                <value>
                    <fullName>Trailer-Mobile Home</fullName>
                </value>
                <value>
                    <fullName>Commercial</fullName>
                </value>
                <value>
                    <fullName>Finders Fees</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Regional_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Relationship Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities4</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Placement__c.object
<CustomObject>
    <description>Holds information about a housing placement, when the Opportunity stage is set to Moved-In, and a policy holder moves into the temporarry housing.  Besides the detail about the duration of the placement, this object is related to Cases to track any issues related to the placement.</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Claim Lookup</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Placements</relationshipLabel>
        <relationshipName>Placements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ServiceRequest__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Request</label>
        <referenceTo>ServiceRequest__c</referenceTo>
        <relationshipLabel>Placements</relationshipLabel>
        <relationshipName>Placements1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Checked-In</fullName>
                </value>
                <value>
                    <fullName>Checked-Out</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Moved-In</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Moved-Out</fullName>
                </value>
                <value>
                    <fullName>Pending Confirmation</fullName>
                </value>
                <value>
                    <fullName>Quote</fullName>
                </value>
                <value>
                    <fullName>Searching</fullName>
                </value>
                <value>
                    <fullName>Pending Check-In</fullName>
                </value>
                <value>
                    <fullName>Lost Opportunity</fullName>
                </value>
                <value>
                    <fullName>Viewing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Placement</label>
    <nameField>
        <label>Placement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Placements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ServiceRequest__c.object
<CustomObject>
    <description>Holds the different services that a request can include, such as: Hotel Stays, Housing requests, Furniture requests, Fair Rental Value, etc.</description>
    <fields>
        <fullName>Area_Specialist__c</fullName>
        <formula>Opportunity__r.Area_Specialist__r.FirstName &amp; &quot; &quot; &amp; Opportunity__r.Area_Specialist__r.LastName</formula>
        <label>Residence Specialist</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Housing_Coordinator__c</fullName>
        <formula>Opportunity__r.Housing_Coordinator__r.FirstName &amp; &quot; &quot; &amp;  Opportunity__r.Housing_Coordinator__r.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Housing Coordinator</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Claim</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Service Requests</relationshipLabel>
        <relationshipName>Service_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ServiceRequest__c</fullName>
        <formula>Id</formula>
        <label>ServiceRequest</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Request</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Searching</fullName>
                </value>
                <value>
                    <fullName>Pending Confirmation</fullName>
                </value>
                <value>
                    <fullName>Moved-In/Closed</fullName>
                </value>
                <value>
                    <fullName>Finders Fee</fullName>
                </value>
                <value>
                    <fullName>Hold</fullName>
                </value>
                <value>
                    <fullName>Checked-In/Closed</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Lost Opportunity</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Service Request</label>
    <nameField>
        <displayFormat>SR#-{000000}</displayFormat>
        <label>Service Request</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Requests</pluralLabel>
    <recordTypes>
        <fullName>Hotel</fullName>
        <active>true</active>
        <description>For Hotel requests</description>
        <label>Hotel</label>
    </recordTypes>
    <recordTypes>
        <fullName>Housing</fullName>
        <active>true</active>
        <description>For Housing requests</description>
        <label>Housing</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/OpportunityTriggerHandler.cls
public class OpportunityTriggerHandler
{
  /* Chatter Follow and Unfollow for CRS TEAM Section in Opportunity*/
  /*public static void claimFollow(list<opportunity> opprecords,Map<Id,opportunity> oldMap){
   Set<Id> oppId = new Set<Id>();
   Set<Id> UnFollowersClaimId = new Set<Id>();
   Set<Id> UnfollowersSubscriberId = new Set<Id>();
   list<EntitySubscription> FollowentitySubrecords = new list<EntitySubscription>();
   list<EntitySubscription> UnfollowentitySubrecords = new list<EntitySubscription>();
   
    Set<String> deleteRecordUserMatchSet = new Set<String>();
    Map<String,String> oppOldUserCustomerCareSpecialistMap = new Map<String,String>();
    Map<String,String> oppOldUserAreaSpecialistMap = new Map<String,String>();
    Map<String,String> oppOldUserRegionalManagerMap = new Map<String,String>();
    Map<String,String> oppOldUserHotelCustomerCareSpecialistMap = new Map<String,String>();
    Map<String,String> oppOldUserHousingCoordinatorMap =  new Map<String,String>();
   
    for(opportunity opp: opprecords){
                      
            if(Trigger.isInsert){
                
                if(opp.id <> null && opp.Customer_Care_Specialist__c <> null){
                     FollowentitySubrecords.add(new EntitySubscription(ParentId = opp.id, SubscriberId = opp.Customer_Care_Specialist__c));
                }
                
                if(opp.id <> null  && opp.Area_Specialist__c <> null){
                     FollowentitySubrecords.add(new EntitySubscription(ParentId = opp.id, SubscriberId = opp.Area_Specialist__c));
                }
                
                if(opp.id <> null  && opp.Regional_Manager__c <> null){
                     FollowentitySubrecords.add(new EntitySubscription(ParentId = opp.id, SubscriberId = opp.Regional_Manager__c ));
                }
                
                if(opp.id <> null && opp.Hotel_Customer_Care_Specialist__c <> null){
                     FollowentitySubrecords.add(new EntitySubscription(ParentId = opp.id, SubscriberId = opp.Hotel_Customer_Care_Specialist__c ));
                }
                
                if(opp.id <> null && opp.Housing_Coordinator__c <> null){
                     FollowentitySubrecords.add(new EntitySubscription(ParentId = opp.id, SubscriberId = opp.Housing_Coordinator__c ));
                }
            }
            
            if(Trigger.isUpdate && ((opp.Customer_Care_Specialist__c != oldMap.get(opp.Id).Customer_Care_Specialist__c ) || (opp.Hotel_Customer_Care_Specialist__c != oldMap.get(opp.Id).Hotel_Customer_Care_Specialist__c) || (opp.Area_Specialist__c != oldMap.get(opp.Id).Area_Specialist__c) || (opp.Regional_Manager__c != oldMap.get(opp.Id).Regional_Manager__c) || (opp.Housing_Coordinator__c != oldMap.get(opp.Id).Housing_Coordinator__c))){
                
                oppId.add(opp.id);
                
                // Customer care specialist    
                if(oldMap.get(opp.Id).Customer_Care_Specialist__c != null){
                    UnfollowersSubscriberId.add(oldMap.get(opp.Id).Customer_Care_Specialist__c);
                    unFollowersClaimId.add(opp.id);
                    deleteRecordUserMatchSet.add(opp.id+''+oldMap.get(opp.Id).Customer_Care_Specialist__c);    
                    oppOldUserCustomerCareSpecialistMap.put(opp.Id, oldMap.get(opp.Id).Customer_Care_Specialist__c);                        
                }  
                if(opp.Customer_Care_Specialist__c != null){
                     FollowentitySubrecords.add(new EntitySubscription(ParentId = opp.id, SubscriberId = opp.Customer_Care_Specialist__c));
                }
                
                // Area Specialist    
                if(oldMap.get(opp.Id).Area_Specialist__c != null){
                    UnfollowersSubscriberId.add(oldMap.get(opp.Id).Area_Specialist__c);
                    unFollowersClaimId.add(opp.id);
                    deleteRecordUserMatchSet.add(opp.id+''+oldMap.get(opp.Id).Area_Specialist__c);
                    oppOldUserAreaSpecialistMap.put(opp.Id, oldMap.get(opp.Id).Area_Specialist__c);                          
                }
                if(opp.Area_Specialist__c != null){
                    FollowentitySubrecords.add(new EntitySubscription(ParentId = opp.id, SubscriberId = opp.Area_Specialist__c));
                } 
                
                // Regional Manager    
                if(oldMap.get(opp.Id).Regional_Manager__c != null){
                    UnfollowersSubscriberId.add(oldMap.get(opp.Id).Regional_Manager__c);
                    unFollowersClaimId.add(opp.id); 
                    deleteRecordUserMatchSet.add(opp.id+''+oldMap.get(opp.Id).Regional_Manager__c); 
                    oppOldUserRegionalManagerMap.put(opp.Id, oldMap.get(opp.Id).Regional_Manager__c);                          
                }
                if(opp.Regional_Manager__c != null){
                    FollowentitySubrecords.add(new EntitySubscription(ParentId = opp.id, SubscriberId = opp.Regional_Manager__c));
                }                
                
                // Hotel Customer Care Specialist    
                if(oldMap.get(opp.Id).Hotel_Customer_Care_Specialist__c != null){
                    UnfollowersSubscriberId.add(oldMap.get(opp.Id).Hotel_Customer_Care_Specialist__c);
                    unFollowersClaimId.add(opp.id); 
                    deleteRecordUserMatchSet.add(opp.id+''+oldMap.get(opp.Id).Hotel_Customer_Care_Specialist__c);
                    oppOldUserHotelCustomerCareSpecialistMap.put(opp.Id, oldMap.get(opp.Id).Hotel_Customer_Care_Specialist__c);
                }
                if(opp.Hotel_Customer_Care_Specialist__c != null){
                    FollowentitySubrecords.add(new EntitySubscription(ParentId = opp.id, SubscriberId = opp.Hotel_Customer_Care_Specialist__c));                        
                }
                
                // Housing Coordinator    
                if(oldMap.get(opp.Id).Housing_Coordinator__c != null){
                    UnfollowersSubscriberId.add(oldMap.get(opp.Id).Housing_Coordinator__c);
                    unFollowersClaimId.add(opp.id); 
                    deleteRecordUserMatchSet.add(opp.id+''+oldMap.get(opp.Id).Housing_Coordinator__c);
                    oppOldUserHousingCoordinatorMap.put(opp.Id, oldMap.get(opp.Id).Housing_Coordinator__c);
                } 
                if(opp.Housing_Coordinator__c != null){
                    FollowentitySubrecords.add(new EntitySubscription(ParentId = opp.id, SubscriberId = opp.Housing_Coordinator__c));
                } 
                    
            }
                                                                    
    }
    
    
    if(Trigger.isUpdate){    
        // Changing the followers in SR level
        list<ServiceRequest__c> SRRecords = [select id,opportunity__r.Initial_Service_Request__c,opportunity__r.Hotel_Customer_Care_Specialist__c,opportunity__c from ServiceRequest__c where opportunity__c in: oppId AND opportunity__r.Initial_Service_Request__c ='Hotel'];
        list<Placement__c>  PcRecords = [select id,opportunity__c,ServiceRequest__c,opportunity__r.Initial_Service_Request__c,opportunity__r.Hotel_Customer_Care_Specialist__c,opportunity__r.Area_Specialist__c,opportunity__r.Regional_Manager__c,opportunity__r.Customer_Care_Specialist__c,Status__c from Placement__c where opportunity__c in: oppId AND opportunity__r.Initial_Service_Request__c ='Housing'];
        
        // Changing the follower in Hotel Level
        for(ServiceRequest__c SR: SRRecords ){
            if(SR.opportunity__r.Initial_Service_Request__c == 'Hotel' && SR.opportunity__r.Hotel_Customer_Care_Specialist__c <> null){
                
                if(oppOldUserHotelCustomerCareSpecialistMap.keySet().contains(SR.opportunity__c)){   
                    unFollowersClaimId.add(SR.id);
                    deleteRecordUserMatchSet.add(SR.id+''+oppOldUserHotelCustomerCareSpecialistMap.get(SR.opportunity__c));  
                }
                FollowentitySubrecords.add(new EntitySubscription(ParentId = SR.id, SubscriberId = SR.opportunity__r.Hotel_Customer_Care_Specialist__c));
            }
            
        }
        
        // Changing the followers in Housing Level
        for(Placement__c pc: PcRecords ){
            if(pc.opportunity__r.Initial_Service_Request__c == 'Housing' && pc.opportunity__r.Regional_Manager__c <> null && pc.Status__c  != 'Moved-In'){
                if(oppOldUserRegionalManagerMap.keySet().contains(pc.opportunity__c)){      
                    unFollowersClaimId.add(PC.ServiceRequest__c);
                    deleteRecordUserMatchSet.add(PC.ServiceRequest__c+''+oppOldUserRegionalManagerMap.get(pc.opportunity__c));
                }
                    
                FollowentitySubrecords.add(new EntitySubscription(ParentId = PC.ServiceRequest__c, SubscriberId = PC.opportunity__r.Regional_Manager__c ));
            }
            if(pc.opportunity__r.Initial_Service_Request__c == 'Housing' && pc.opportunity__r.Area_Specialist__c <> null && pc.Status__c  != 'Moved-In'){
                if(oppOldUserAreaSpecialistMap.keySet().contains(pc.opportunity__c)){      
                    unFollowersClaimId.add(PC.ServiceRequest__c);
                    deleteRecordUserMatchSet.add(PC.ServiceRequest__c+''+oppOldUserAreaSpecialistMap.get(pc.opportunity__c));
                }
                
                FollowentitySubrecords.add(new EntitySubscription(ParentId = PC.ServiceRequest__c, SubscriberId = PC.opportunity__r.Area_Specialist__c ));
            }
            if(pc.opportunity__r.Initial_Service_Request__c == 'Housing' && pc.opportunity__r.Customer_Care_Specialist__c<> null && pc.Status__c  == 'Moved-In'){
                if(oppOldUserCustomerCareSpecialistMap.keySet().contains(pc.opportunity__c)){      
                    unFollowersClaimId.add(PC.ServiceRequest__c);
                    deleteRecordUserMatchSet.add(PC.ServiceRequest__c+''+oppOldUserCustomerCareSpecialistMap.get(pc.opportunity__c));
                }
                
                FollowentitySubrecords.add(new EntitySubscription(ParentId = PC.ServiceRequest__c, SubscriberId = PC.opportunity__r.Customer_Care_Specialist__c));
            }
            
        }
             
    }
       
       for(EntitySubscription eSub : [select id, parentId, SubscriberId from EntitySubscription where parentId in:unFollowersClaimId AND SubscriberId in:UnfollowersSubscriberId]){
           
           String concatStr = eSub.parentId + '' + eSub.SubscriberId;
           if(deleteRecordUserMatchSet.contains(concatStr))
              UnfollowentitySubrecords.add(eSub); 
           
       }
       
       if(!UnfollowentitySubrecords.IsEmpty())
            Database.Delete(UnfollowentitySubrecords,false);
        
       
            
        if(!FollowentitySubrecords.IsEmpty()) 
            Database.Insert(FollowentitySubrecords,false);
        
   }*/
}