src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>ALE_Spent__c</fullName>
        <defaultValue>0</defaultValue>
        <label>ALE Spent</label>
        <precision>11</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ALE_Unbilled__c</fullName>
        <defaultValue>0</defaultValue>
        <label>ALE Unbilled</label>
        <precision>11</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <recordTypes>
        <fullName>Claim</fullName>
        <active>true</active>
        <businessProcess>Standard Request</businessProcess>
        <label>Claim</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/RESTUpdateClaimALE.cls
@RestResource(urlMapping='/Claim/UpdateClaimALE/*')
global with sharing class RESTUpdateClaimALE 
{
    @HttpPatch
    global static String updateClaimALE(String claimId,Double claimALESpent,Double claimALEUnbilled)   
    { 
        try
        {
              Opportunity claim = [SELECT Id,ALE_Spent__c,ALE_Unbilled__c from Opportunity WHERE Id =: claimId]; 
              claim.ALE_Spent__c = claimALESpent;
              claim.ALE_Unbilled__c = claimALEUnbilled; 
              update claim;
              return 'ALE updated for claim id ' + claimId;
        }
        catch (Exception e)
        {
           Util.sendErrorEmail('Claim ALE Update error','ERROR: ' + e + ' returned updating the claim ALE on claim ' + claimId);       
           return 'ALE update failed for claim id ' + claimId;
        }
    }
}