src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>ALE_Limit_Amount__c</fullName>
        <label>ALE Amount Limit</label>
        <precision>9</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ALE_Spent_Outside_Of_CRS__c</fullName>
        <defaultValue>0</defaultValue>
        <label>ALE Spent Outside of CRS</label>
        <precision>11</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ALE_Spent__c</fullName>
        <defaultValue>0</defaultValue>
        <label>ALE Spent</label>
        <precision>11</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ALE_Unbilled__c</fullName>
        <defaultValue>0</defaultValue>
        <label>ALE Unbilled</label>
        <precision>11</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <recordTypes>
        <fullName>Claim</fullName>
        <active>true</active>
        <businessProcess>Standard Request</businessProcess>
        <label>Claim</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/ClaimALEAmountChartController.cls
public class ClaimALEAmountChartController 
{
    public String claimId {get;set;}
    public String colors = '';

    public ClaimALEAmountChartController(ApexPages.StandardController controller)
    {
        claimId = controller.getRecord().Id;
    }

    public List<PieWedgeData> getPieData() 
    {
        Opportunity claim = [Select ALE_Spent__c,ALE_Unbilled__c,ALE_Spent_Outside_Of_CRS__c,ALE_Limit_Amount__c from Opportunity where Id =: claimId];
        List<PieWedgeData> data = new List<PieWedgeData>();
   
        if (claim.ALE_Limit_Amount__c != 0 && claim.ALE_Limit_Amount__c != null)
        {

            if (claim.ALE_Spent__c == null)
            {
                claim.ALE_Spent__c = 0;
            }
            if (claim.ALE_Spent_Outside_Of_CRS__c == null)
            {
                claim.ALE_Spent_Outside_Of_CRS__c = 0;
            }
            if (claim.ALE_Unbilled__c == null)
            {
                claim.ALE_Unbilled__c = 0;
            }
            if (claim.ALE_Limit_Amount__c == null)
            {
                claim.ALE_Limit_Amount__c = 0;
            }
            
            if (claim.ALE_Spent__c + claim.ALE_Spent_Outside_Of_CRS__c != 0)
            {
                data.add(new PieWedgeData('Spent', integer.valueOf(claim.ALE_Spent__c + claim.ALE_Spent_Outside_Of_CRS__c))); 
                colors = 'Red';
            }
         
            if (claim.ALE_Unbilled__c != 0)
            {   
                data.add(new PieWedgeData('Unbilled', integer.valueOf(claim.ALE_Unbilled__c)));
                if (colors != '')
                {
                    colors += ',';    
                }
                colors += 'Orange';

            }
            if (claim.ALE_Limit_Amount__c != 0 && claim.ALE_Limit_Amount__c > claim.ALE_Spent__c + claim.ALE_Spent_Outside_Of_CRS__c + claim.ALE_Unbilled__c)
            {
                data.add(new PieWedgeData('Remaining', integer.valueOf(claim.ALE_Limit_Amount__c - (claim.ALE_Spent__c + claim.ALE_Spent_Outside_Of_CRS__c + claim.ALE_Unbilled__c))));
                if (colors != '')
                {
                    colors += ',';    
                }
                colors += 'Green';
            }
        }
        
        return data;
    }

    // Wrapper class
    public class PieWedgeData 
    {

        public String name { get; set; }
        public Integer data { get; set; }
       

        public PieWedgeData(String name, Integer data) 
        {
            this.name = name;
            this.data = data;
        }
    }

    public String getColors() 
    {
        return colors;
    }
}