src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Area_Specialist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Residence Specialist</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Care_Specialist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Care Specialist</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Hotel_Customer_Care_Specialist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Hotel Customer Care Specialist</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Housing_Coordinator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Residence Coordinator</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Initial_Call_Date__c</fullName>
        <inlineHelpText>Date that an attempt was made to contact the Policyholder.</inlineHelpText>
        <label>Initial Call Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Initial_Contact_Date__c</fullName>
        <label>Initial Contact Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Policyholder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Policyholder</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Policyholder, Adjuster Policyholder Record Type</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Claims</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Regional_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Relationship Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities4</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Claim</fullName>
        <active>true</active>
        <businessProcess>Standard Request</businessProcess>
        <label>Claim</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Placement__c.object
<CustomObject>
    <description>Holds information about a housing placement, when the Opportunity stage is set to Moved-In, and a policy holder moves into the temporarry housing.  Besides the detail about the duration of the placement, this object is related to Cases to track any issues related to the placement.</description>
    <fields>
        <fullName>Area_Specialist_Email__c</fullName>
        <label>Residence Specialist Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Customer_Care_Specialist_Email__c</fullName>
        <label>Customer Care Specialist Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Hotel_Customer_Care_Specialist_Email__c</fullName>
        <label>Hotel Customer Care Specialist Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Housing_Coordinator_Email__c</fullName>
        <label>Residence Coordinator Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Claim Lookup</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Placements</relationshipLabel>
        <relationshipName>Placements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Regional_Manager_Email__c</fullName>
        <label>Relationship Manager Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Sequence_Number__c</fullName>
        <label>Sequence Number</label>
        <precision>7</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ServiceRequest__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Request</label>
        <referenceTo>ServiceRequest__c</referenceTo>
        <relationshipLabel>Placements</relationshipLabel>
        <relationshipName>Placements1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Placement</label>
    <nameField>
        <label>Placement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Placements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ServiceRequest__c.object
<CustomObject>
    <description>Holds the different services that a request can include, such as: Hotel Stays, Housing requests, Furniture requests, Fair Rental Value, etc.</description>
    <fields>
        <fullName>Area_Specialist_Email__c</fullName>
        <label>Property Specialist Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Area_Specialist__c</fullName>
        <formula>Opportunity__r.Area_Specialist__r.FirstName &amp; &quot; &quot; &amp; Opportunity__r.Area_Specialist__r.LastName</formula>
        <label>Residence Specialist</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Care_Specialist_Email__c</fullName>
        <label>Customer Care Specialist Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Hotel_Customer_Care_Specialist_Email__c</fullName>
        <label>Hotel Customer Care Specialist Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Housing_Coordinator_Email__c</fullName>
        <label>Housing Coordinator Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Housing_Coordinator__c</fullName>
        <formula>Opportunity__r.Housing_Coordinator__r.FirstName &amp; &quot; &quot; &amp;  Opportunity__r.Housing_Coordinator__r.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Housing Coordinator</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Initial_Call_Date__c</fullName>
        <label>Initial Call Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Initial_Contact_Date__c</fullName>
        <label>Initial Contact Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Claim</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Service Requests</relationshipLabel>
        <relationshipName>Service_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Regional_Manager_Email__c</fullName>
        <label>Relationship Manager Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>ServiceRequest__c</fullName>
        <formula>Id</formula>
        <label>ServiceRequest</label>
        <type>Text</type>
    </fields>
    <label>Service Request</label>
    <nameField>
        <displayFormat>SR#-{000000}</displayFormat>
        <label>Service Request</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ServiceRequestDispatcherExtension.cls
public with sharing class ServiceRequestDispatcherExtension 
{
  public ServiceRequestDispatcherExtension(ApexPages.StandardController stdController)
  {
    ServiceRequest__c serviceRequest = (ServiceRequest__c)stdController.getRecord(); 
  }
  
  public PageReference getViewServiceRequest()
  {
    Id id = ApexPages.currentPage().getParameters().get('id'); 
    ServiceRequest__c serviceRequest = [select Id, RecordTypeId, Opportunity__c from ServiceRequest__c where Id = :id];
   
    PageReference newPage;
    
    if (serviceRequest.RecordTypeId == RecordTypeHelper.hotelServiceRequestRT())
    {
        newPage = Page.HotelEntry; 
    }
    else
    {   
        if (serviceRequest.RecordTypeId == RecordTypeHelper.housingServiceRequestRT())
        {
             newPage = Page.HousingEntry;
        }
        else
        {
             newPage = new PageReference('/' + id);
             newPage.getParameters().put('nooverride', '1');
             return newPage.setRedirect(true);
        }
    }
    newPage.getParameters().put('id', id);
    return newPage.setRedirect(true);
  }
  
  public PageReference getNewServiceRequest()
  {
    this.logParams();
    Id rtId = ApexPages.currentPage().getParameters().get('RecordType');
     
    PageReference newPage;
    string claimParam = ApexPages.currentPage().getParameters().get('retURL').replace('/', ''); 
    
    if (rtId == RecordTypeHelper.hotelServiceRequestRT())
    {
        newPage = Page.HotelEntry;
 
        ServiceRequest__c serviceRequest = new ServiceRequest__c();
        serviceRequest.RecordTypeId = RecordTypeHelper.hotelServiceRequestRT();
        system.debug(claimParam);
        if (claimParam != 'a0Po' && claimParam.substring(0,3) != 'a0P')
        {
            
            serviceRequest.Opportunity__c = claimParam.substring(0,15);
            serviceRequest.Initial_Call_Date__c = Datetime.now();
            serviceRequest.Initial_Contact_Date__c = Datetime.now();
        }
                         
        upsert serviceRequest;
        newPage.getParameters().put('id', serviceRequest.id);
    }
    else
    {
        if (rtId == RecordTypeHelper.housingServiceRequestRT())
        {
            newPage = Page.HousingEntry;
     
            ServiceRequest__c serviceRequest = new ServiceRequest__c();
            serviceRequest.RecordTypeId = rtId;
            system.debug(claimParam);
            if (claimParam != 'a0Po' && claimParam.substring(0,3) != 'a0P')
            {
                try
                {
                    serviceRequest.Opportunity__c = claimParam.substring(0,15);
                }
                catch (exception e)
                {
                }
            }

            upsert serviceRequest;
                             
            Double seqNumber;
            try
            {
                seqNumber = [select Sequence_Number__c From Placement__c where Opportunity__c =:serviceRequest.Opportunity__c and RecordTypeId =: RecordTypeHelper.housingPlacementRT() and Sequence_Number__c <> null order by Sequence_Number__c desc limit 1].Sequence_Number__c;
                seqNumber ++;
            }
            catch (exception e)
            {
                seqNumber = 1;
            }
            
            Placement__c relatedPlacement = new Placement__c();
            relatedPlacement.RecordTypeId = RecordTypeHelper.housingPlacementRT();
            relatedPlacement.ServiceRequest__c = serviceRequest.Id;
            relatedPlacement.Opportunity__c = serviceRequest.Opportunity__c;
            Opportunity claim = [select name, Policyholder__r.Name,Customer_Care_Specialist__r.Email,Regional_Manager__r.Email,Area_Specialist__r.Email,Housing_Coordinator__r.Email,Hotel_Customer_Care_Specialist__r.Email from Opportunity where Id =:serviceRequest.Opportunity__c]; 
            relatedPlacement.Name = claim.Name + ' - ' + claim.Policyholder__r.Name + ' #' + seqNumber.intValue();
            relatedPlacement.Sequence_Number__c = seqNumber;
            relatedPlacement.Customer_Care_Specialist_Email__c = claim.Customer_Care_Specialist__r.Email;
            relatedPlacement.Regional_Manager_Email__c = claim.Regional_Manager__r.Email;
            relatedPlacement.Area_Specialist_Email__c = claim.Area_Specialist__r.Email;
            relatedPlacement.Housing_Coordinator_Email__c = claim.Housing_Coordinator__r.Email;
            relatedPlacement.Hotel_Customer_Care_Specialist_Email__c = claim.Hotel_Customer_Care_Specialist__r.Email;
                        
            upsert relatedPlacement;
            newPage.getParameters().put('id', serviceRequest.id);
        }
        else
        {
            String prefix = ServiceRequest__c.SObjectType.getDescribe().getKeyPrefix();
             
            newPage = new PageReference('/' + prefix + '/e');
            newPage.getParameters().put('nooverride', '1');
            newPage = getParameters(newPage); 
                  
            // set _lkid val if it is in the params
            Map<String, String> params = ApexPages.currentPage().getParameters();
            Set<String> keys = params.keySet();
                 
            string lookupId = '';
                
            for(String key : keys)
            {
                if (key.endsWith('_lkid'))
                {
                    newPage.getParameters().put(key, params.get(key));
                    lookupId = key.replace('_lkid', '');
                }
            }
            
            if (lookupId.length() > 0)
            {
                newPage.getParameters().put(lookupId, params.get(lookupId));
            }  
        }   
    }  
    return newPage.setRedirect(true);  
  }
    
  public PageReference getEditServiceRequest()
  {
    Id id = ApexPages.currentPage().getParameters().get('id'); 
    ServiceRequest__c serviceRequest = [select Id, RecordTypeId from ServiceRequest__c where Id = :id];
        
    PageReference newPage;
    
    if (serviceRequest.RecordTypeId == RecordTypeHelper.hotelServiceRequestRT())
    {
        newPage = Page.HotelEntry;
    }
    else
    {
        if (serviceRequest.RecordTypeId == RecordTypeHelper.housingServiceRequestRT())
        {
            newPage = Page.HousingEntry;    
        }
        else
        {
            newPage = new PageReference('/' + id + '/e');
            newPage.getParameters().put('retURL',id);
            newPage.getParameters().put('nooverride', '1');
            return newPage.setRedirect(true);
        }
    }
    newPage.getParameters().put('id', id);
    return newPage.setRedirect(true);
  }
 
  private PageReference getParameters(PageReference page)
  {
    
    Map<String, String> params = ApexPages.currentPage().getParameters();
    String[] keys = new String[]{'RecordType', 'retURL', 'cancelURL'};
    
    for(String s : keys)
    {
      if (params.containsKey(s)) 
      {
        page.getParameters().put(s, params.get(s));
      }
    }
    
    return page;
  }
  
  private void logParams()
  {
    Map<String, String> params = ApexPages.currentPage().getParameters();
    Set<String> keys = params.keySet();
    
    for(String s : keys)
    {
        // s, params.get(s)
        System.debug(LoggingLevel.INFO, 'Page Param => key:' + s + ', val:' + params.get(s));
            
    }
    
  }

}