src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Customer_Care_Specialist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Care Specialist</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Damaged_Property_Address__c</fullName>
        <label>Damaged Property Address</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Damaged_Property_City__c</fullName>
        <label>Damaged Property City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Damaged_Property_Country__c</fullName>
        <label>Damaged Property Country</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Damaged_Property_State__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>USA</fullName>
                </value>
                <value>
                    <fullName>CAN</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Damaged_Property_State__c</fullName>
        <label>Damaged Property State/Province</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DC</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
                <value>
                    <fullName>MN</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
                <value>
                    <fullName>MS</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
                <value>
                    <fullName>NC</fullName>
                </value>
                <value>
                    <fullName>ND</fullName>
                </value>
                <value>
                    <fullName>NE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Damaged_Property_Type__c</fullName>
        <label>Damaged Property Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Apartment</fullName>
                </value>
                <value>
                    <fullName>Condo</fullName>
                </value>
                <value>
                    <fullName>House</fullName>
                </value>
                <value>
                    <fullName>Mobile Home</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Townhouse</fullName>
                </value>
                <value>
                    <fullName>Travel Trailer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Damaged_Property_Zip__c</fullName>
        <label>Damaged Property Zip/Postal Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Hotel_Customer_Care_Specialist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Hotel Customer Care Specialist</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Initial_Service_Request__c</fullName>
        <label>Initial Service Request</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Housing</fullName>
                </value>
                <value>
                    <fullName>Hotel</fullName>
                </value>
                <value>
                    <fullName>FRV</fullName>
                </value>
                <value>
                    <fullName>Furniture Only</fullName>
                </value>
                <value>
                    <fullName>Unfurnished</fullName>
                </value>
                <value>
                    <fullName>Trailer-Mobile Home</fullName>
                </value>
                <value>
                    <fullName>Commercial</fullName>
                </value>
                <value>
                    <fullName>Finders Fees</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Regional_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Relationship Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type_of_Loss__c</fullName>
        <label>Type of Loss</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CAT</fullName>
                </value>
                <value>
                    <fullName>Fire</fullName>
                </value>
                <value>
                    <fullName>Mold</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Tornado</fullName>
                </value>
                <value>
                    <fullName>Water</fullName>
                </value>
                <value>
                    <fullName>Wind</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Placement__c.object
<CustomObject>
    <description>Holds information about a housing placement, when the Opportunity stage is set to Moved-In, and a policy holder moves into the temporarry housing.  Besides the detail about the duration of the placement, this object is related to Cases to track any issues related to the placement.</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Claim Lookup</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Placements</relationshipLabel>
        <relationshipName>Placements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ServiceRequest__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Request</label>
        <referenceTo>ServiceRequest__c</referenceTo>
        <relationshipLabel>Placements</relationshipLabel>
        <relationshipName>Placements1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Checked-In</fullName>
                </value>
                <value>
                    <fullName>Checked-Out</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Moved-In</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Moved-Out</fullName>
                </value>
                <value>
                    <fullName>Pending Confirmation</fullName>
                </value>
                <value>
                    <fullName>Quote</fullName>
                </value>
                <value>
                    <fullName>Searching</fullName>
                </value>
                <value>
                    <fullName>Pending Check-In</fullName>
                </value>
                <value>
                    <fullName>Lost Opportunity</fullName>
                </value>
                <value>
                    <fullName>Viewing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Placement</label>
    <nameField>
        <label>Placement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Placements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ServiceRequest__c.object
<CustomObject>
    <description>Holds the different services that a request can include, such as: Hotel Stays, Housing requests, Furniture requests, Fair Rental Value, etc.</description>
    <fields>
        <fullName>Damaged_Property_Address__c</fullName>
        <formula>Opportunity__r.Damaged_Property_Address__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Damaged Property Address</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Damaged_Property_City__c</fullName>
        <formula>Opportunity__r.Damaged_Property_City__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Damaged Property City</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Damaged_Property_Country__c</fullName>
        <formula>Text(Opportunity__r.Damaged_Property_Country__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Damaged Property Country</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Damaged_Property_State__c</fullName>
        <formula>Text(Opportunity__r.Damaged_Property_State__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Damaged Property State</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Damaged_Property_Type__c</fullName>
        <formula>CASE( Opportunity__r.Damaged_Property_Type__c, &quot;House&quot; , &quot;House&quot; , &quot;Mobile Home&quot; , &quot;Mobile Home&quot; , &quot;Travel Trailer&quot; , &quot;Travel Trailer&quot; , &quot;Condo&quot; , &quot;Condo&quot; , &quot;Apartment&quot; , &quot;Apartment&quot; , &quot;Townhouse&quot; , &quot;Townhouse&quot; , &quot;Other&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Damaged Property Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Damaged_Property_Zip__c</fullName>
        <formula>Opportunity__r.Damaged_Property_Zip__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Damaged Property Zip</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Claim</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Service Requests</relationshipLabel>
        <relationshipName>Service_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ServiceRequest__c</fullName>
        <formula>Id</formula>
        <label>ServiceRequest</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Request</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Searching</fullName>
                </value>
                <value>
                    <fullName>Pending Confirmation</fullName>
                </value>
                <value>
                    <fullName>Moved-In/Closed</fullName>
                </value>
                <value>
                    <fullName>Finders Fee</fullName>
                </value>
                <value>
                    <fullName>Hold</fullName>
                </value>
                <value>
                    <fullName>Checked-In/Closed</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Lost Opportunity</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type_of_Loss__c</fullName>
        <formula>CASE (Opportunity__r.Type_of_Loss__c, &apos;Mold&apos;, &apos;Mold&apos;, &apos;Fire&apos;, &apos;Fire&apos;, &apos;Tornado&apos;, &apos;Tornado&apos;, &apos;Water&apos;, &apos;Water&apos;,&apos;Wind&apos;, &apos;Wind&apos;, &apos;CAT&apos; , &apos;CAT&apos; , &apos;Other&apos;)</formula>
        <label>Type of Loss</label>
        <type>Text</type>
    </fields>
    <label>Service Request</label>
    <nameField>
        <displayFormat>SR#-{000000}</displayFormat>
        <label>Service Request</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Requests</pluralLabel>
    <recordTypes>
        <fullName>Housing</fullName>
        <active>true</active>
        <description>For Housing requests</description>
        <label>Housing</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ServiceRequestDispatcherExtensionTest.cls
@isTest
private class ServiceRequestDispatcherExtensionTest {

   	@testSetup static void setupTestData()
   	{
		// Insert Users
        Profile p = [SELECT Id FROM Profile WHERE Name='Operations User']; 
        User user1 = new User
                (   
                    Alias = 'standt',
                    Email='operationsuser@testorg.com', 
                    EmailEncodingKey='UTF-8', 
                    LastName='Testing', 
                    LanguageLocaleKey='en_US',
                    LocaleSidKey='en_US', 
                    ProfileId = p.Id, 
                    TimeZoneSidKey='America/Los_Angeles', 
                    UserName='operationsuser@crstemphousing.com');
        insert user1; 

		Opportunity opportunity = new Opportunity
                (
                    StageName = 'Submitted',
                    Name = 'testopportunity',
                    Initial_Service_Request__c='Housing',   
                    CloseDate = Date.newInstance(2010,12,10),
                    Type_of_Loss__c = 'Mold',
                    Damaged_Property_Type__c = 'Apartment',
                    Damaged_Property_Address__c = '123 Big Test Lane',
                    Damaged_Property_City__c = 'Mineola',
                    Damaged_Property_State__c = 'CT',
                    Damaged_Property_Zip__c = '11501',
                    Damaged_Property_Country__c = 'USA',
                    Regional_Manager__c = user1.Id,
                    Customer_Care_Specialist__c = user1.Id,
                    Hotel_Customer_Care_Specialist__c = user1.Id);
        insert opportunity;

   		ServiceRequest__c frvSR = new ServiceRequest__c
        		(
                	RecordTypeId = RecordTypeHelper.frvServiceRequestRT(),
				    Opportunity__c = opportunity.Id,
				    Status__c = 'Searching',
				    Adjuster_to_Pay__c = 'Deposits and Fees',
				    Policyholder_to_Pay__c = 'Will Not Pay',
				    THC_Signed__c = Date.newInstance(2009,10,09),
				    THA_Signed__c = Date.newInstance(2009,10,09));		    
        insert frvSR;              
		
		
		ServiceRequest__c housingSRwithPlacement = new ServiceRequest__c
        		(
                	RecordTypeId = RecordTypeHelper.housingServiceRequestRT(),
				    Opportunity__c = opportunity.Id,
				    Status__c = 'Searching',
				    Adjuster_to_Pay__c = 'Deposits and Fees',
				    Policyholder_to_Pay__c = 'Will Not Pay',
				    THC_Signed__c = Date.newInstance(2009,10,09),
				    THA_Signed__c = Date.newInstance(2009,10,09));
		insert housingSRwithPlacement;	
		
		ServiceRequest__c housingSRwithoutPlacement = new ServiceRequest__c
        		(
                	RecordTypeId = RecordTypeHelper.housingServiceRequestRT(),
				    Opportunity__c = opportunity.Id,
				    Status__c = 'Searching',
				    Adjuster_to_Pay__c = 'Deposits and Fees',
				    Policyholder_to_Pay__c = 'Will Not Pay',
				    THC_Signed__c = Date.newInstance(2009,10,10),
				    THA_Signed__c = Date.newInstance(2009,10,09));
		insert housingSRwithoutPlacement;		    
		
		ServiceRequest__c hotelSR = new ServiceRequest__c
        		(
                	RecordTypeId = RecordTypeHelper.hotelServiceRequestRT(),
                	Opportunity__c = opportunity.Id,
                	Status__c = 'Searching',
				    Adjuster_to_Pay__c = 'Deposits and Fees',
				    Policyholder_to_Pay__c = 'Will Not Pay',
				    THC_Signed__c = Date.newInstance(2009,10,09),
				    THA_Signed__c = Date.newInstance(2009,10,09));		    
        insert hotelSR;

        ServiceRequest__c existingHotelSR = new ServiceRequest__c
        		(
                	RecordTypeId = RecordTypeHelper.hotelServiceRequestRT(),
                	Opportunity__c = opportunity.Id,
                	Status__c = 'Searching',
				    Adjuster_to_Pay__c = 'Deposits and Fees',
				    Policyholder_to_Pay__c = 'Will Not Pay',
				    Initial_Call_Date__c = Date.newInstance(2009,10,09),
				    Initial_Contact_Date__c = Date.newInstance(2009,10,09),
            		First_Property_Presented__c = Date.newInstance(2009,10,09),
				    THC_Signed__c = Date.newInstance(2009,10,10),
				    THA_Signed__c = Date.newInstance(2009,10,09));		    
        insert existingHotelSR;    
        
        Placement__c housingPlacement = new Placement__c(
                                        RecordTypeId = RecordTypeHelper.housingPlacementRT(),
                                        Name = 'testhousingPlacement',
                                        Status__c = 'Searching',
                                        ServiceRequest__c = housingSRwithPlacement.Id, 
                                        Move_In_Date__c = Date.newInstance(2015,09,09),
	    								Approved_Through_Date__c = Date.newInstance(2016,09,09));
                                        
	    insert housingPlacement;
   	}


   	static testMethod void testViewServiceRequest() 
	{
		ServiceRequest__c frvSR = [select id from ServiceRequest__c where recordTypeid =: RecordTypeHelper.frvServiceRequestRT()];
		ServiceRequest__c housingSRwithPlacement = [select id from ServiceRequest__c where recordTypeid =: RecordTypeHelper.housingServiceRequestRT() and THC_Signed__c =: Date.newInstance(2009,10,09)];
		ServiceRequest__c housingSRwithoutPlacement = [select id from ServiceRequest__c where recordTypeid =: RecordTypeHelper.housingServiceRequestRT() and THC_Signed__c =: Date.newInstance(2009,10,10)];
		ServiceRequest__c hotelSR = [select id from ServiceRequest__c where recordTypeid =: RecordTypeHelper.hotelServiceRequestRT() and THC_Signed__c =: Date.newInstance(2009,10,09)];
			
		ServiceRequest__c hsr = new ServiceRequest__c();
		ApexPages.StandardController stdCon = new ApexPages.StandardController(hsr);
	    ServiceRequestDispatcherExtension hsrce = new ServiceRequestDispatcherExtension(stdCon);
 		
 		ApexPages.currentPage().getParameters().put('id', housingSRwithPlacement.Id);
 		PageReference pr = hsrce.getViewServiceRequest();
 		
 		ApexPages.currentPage().getParameters().clear();
 		
 		ApexPages.currentPage().getParameters().put('id', hotelSR.Id);
 		pr = hsrce.getViewServiceRequest();
 		
 		ApexPages.currentPage().getParameters().clear();
 		
 		ApexPages.currentPage().getParameters().put('id', frvSR.Id);
 		pr = hsrce.getViewServiceRequest();
 				
	}
	
	static testMethod void testNewServiceRequest()
	{
		ServiceRequest__c housingSRwithoutPlacement = [select id from ServiceRequest__c where recordTypeid =: RecordTypeHelper.housingServiceRequestRT() and THC_Signed__c =: Date.newInstance(2009,10,10)];
		ServiceRequest__c hotelSR = [select id from ServiceRequest__c where recordTypeid =: RecordTypeHelper.hotelServiceRequestRT() and THC_Signed__c =: Date.newInstance(2009,10,09)];
		Opportunity opportunity = [select id from Opportunity where Damaged_Property_Address__c = '123 Big Test Lane'];
					
		ServiceRequest__c hsr = new ServiceRequest__c();
	    ApexPages.StandardController stdCon = new ApexPages.StandardController(hsr);
	    ServiceRequestDispatcherExtension hsrce = new ServiceRequestDispatcherExtension(stdCon);
	    
	    ApexPages.currentPage().getParameters().put('RecordType', RecordTypeHelper.hotelServiceRequestRT());
	    ApexPages.currentPage().getParameters().put('retURL', '/' + opportunity.Id + '?srPos=0&srKp=006' + RecordTypeHelper.hotelServiceRequestRT());
        PageReference pr = hsrce.getNewServiceRequest();
 		
 		ApexPages.currentPage().getParameters().clear();
 		
     	ApexPages.currentPage().getParameters().put('id', hotelSR.Id);
 		ApexPages.currentPage().getParameters().put('retURL', '/' + RecordTypeHelper.hotelServiceRequestRT());
 		ApexPages.currentPage().getParameters().put(RecordTypeHelper.hotelServiceRequestRT() + '_lkid', RecordTypeHelper.hotelServiceRequestRT());
    	ApexPages.currentPage().getParameters().put(RecordTypeHelper.hotelServiceRequestRT(), RecordTypeHelper.hotelServiceRequestRT());
        
        pr = hsrce.getNewServiceRequest();
        
        
        ApexPages.currentPage().getParameters().put('RecordType', RecordTypeHelper.housingServiceRequestRT());
	    ApexPages.currentPage().getParameters().put('retURL', '/' + opportunity.Id + '?srPos=0&srKp=006' + RecordTypeHelper.housingServiceRequestRT());
        pr = hsrce.getNewServiceRequest();
        
        ApexPages.currentPage().getParameters().clear();
 		
     	ApexPages.currentPage().getParameters().put('id', housingSRwithoutPlacement.Id);
 		ApexPages.currentPage().getParameters().put('retURL', '/' + RecordTypeHelper.housingServiceRequestRT());
 		ApexPages.currentPage().getParameters().put(RecordTypeHelper.housingServiceRequestRT() + '_lkid', RecordTypeHelper.housingServiceRequestRT());
    	ApexPages.currentPage().getParameters().put(RecordTypeHelper.housingServiceRequestRT(), RecordTypeHelper.housingServiceRequestRT());
        
        pr = hsrce.getNewServiceRequest();
		
	}
	
	static testMethod void testEditServiceRequest()
	{
		ServiceRequest__c frvSR = [select id from ServiceRequest__c where recordTypeid =: RecordTypeHelper.frvServiceRequestRT()];
		ServiceRequest__c housingSRwithPlacement = [select id from ServiceRequest__c where recordTypeid =: RecordTypeHelper.housingServiceRequestRT() and THC_Signed__c =: Date.newInstance(2009,10,09)];
		ServiceRequest__c hotelSR = [select id from ServiceRequest__c where recordTypeid =: RecordTypeHelper.hotelServiceRequestRT() and THC_Signed__c =: Date.newInstance(2009,10,09)];

		ServiceRequest__c hsr = new ServiceRequest__c();
	    ApexPages.StandardController stdCon = new ApexPages.StandardController(hsr);
	    ServiceRequestDispatcherExtension hsrce = new ServiceRequestDispatcherExtension(stdCon);
	    
	    ApexPages.currentPage().getParameters().put('id', hotelSR.Id);
	    hsrce.getEditServiceRequest();
	    
	    ApexPages.currentPage().getParameters().clear();
	    
	    ApexPages.currentPage().getParameters().put('id', housingSRwithPlacement.Id);
	    hsrce.getEditServiceRequest();
	    
	    ApexPages.currentPage().getParameters().clear();
	    
	    ApexPages.currentPage().getParameters().put('id', frvSR.Id);
	    hsrce.getEditServiceRequest();
	}
}