src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Customer_Care_Specialist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Care Specialist</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities3</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Placement__c.object
<CustomObject>
    <description>Holds information about a housing placement, when the Opportunity stage is set to Moved-In, and a policy holder moves into the temporarry housing.  Besides the detail about the duration of the placement, this object is related to Cases to track any issues related to the placement.</description>
    <fields>
        <fullName>Date_To_Send_NTV__c</fullName>
        <label>Date To Send NTV</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Claim Lookup</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Placements</relationshipLabel>
        <relationshipName>Placements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Checked-In</fullName>
                </value>
                <value>
                    <fullName>Checked-Out</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Moved-In</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Moved-Out</fullName>
                </value>
                <value>
                    <fullName>Pending Confirmation</fullName>
                </value>
                <value>
                    <fullName>Quote</fullName>
                </value>
                <value>
                    <fullName>Searching</fullName>
                </value>
                <value>
                    <fullName>Pending Check-In</fullName>
                </value>
                <value>
                    <fullName>Lost Opportunity</fullName>
                </value>
                <value>
                    <fullName>Viewing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Placement</label>
    <nameField>
        <label>Placement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Placements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Searches__c.object
<CustomObject>
    <description>Used track the property and hotel searches conducted as part of the Sevice Request</description>
    <fields>
        <fullName>Active_NTV_Task__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active NTV Task</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Date_To_Send_NTV__c</fullName>
        <formula>Placement__r.Approved_Through_Date__c -  Days_Notice_Required__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Date To Send NTV</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>NTV_Send_To__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>This is the contact to send the Notice to Vacate to.  Defaults to the Landlord but can be overridden</description>
        <label>NTV Send To</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Landlord, Agent, Broker</value>
            </filterItems>
            <filterItems>
                <field>Contact.Status__c</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Searches (NTV Send To)</relationshipLabel>
        <relationshipName>Searches1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NTV_Send_Via__c</fullName>
        <label>NTV Send Via</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Fax</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Certified Mail</fullName>
                </value>
                <value>
                    <fullName>Insured</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Placement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Placement</label>
        <referenceTo>Placement__c</referenceTo>
        <relationshipName>Searches</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Selected__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Selected</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Service_Request__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Service Request</label>
        <referenceTo>ServiceRequest__c</referenceTo>
        <relationshipName>Searches</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IF(  $RecordType.DeveloperName = &quot;Hotel&quot;, &quot;Check Capacity&quot;,IF(ISPICKVAL(Property__r.Status__c , &quot;Occupied&quot;) , &quot;Not Available&quot;, &quot;Available&quot;))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <label>Search</label>
    <nameField>
        <displayFormat>SR-{000000}</displayFormat>
        <label>Search Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Searches</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/ServiceRequest__c.object
<CustomObject>
    <description>Holds the different services that a request can include, such as: Hotel Stays, Housing requests, Furniture requests, Fair Rental Value, etc.</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Claim</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Service Requests</relationshipLabel>
        <relationshipName>Service_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Request</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Searching</fullName>
                </value>
                <value>
                    <fullName>Pending Confirmation</fullName>
                </value>
                <value>
                    <fullName>Moved-In/Closed</fullName>
                </value>
                <value>
                    <fullName>Finders Fee</fullName>
                </value>
                <value>
                    <fullName>Hold</fullName>
                </value>
                <value>
                    <fullName>Checked-In/Closed</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Lost Opportunity</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Service Request</label>
    <nameField>
        <displayFormat>SR#-{000000}</displayFormat>
        <label>Service Request</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/NTVTaskCreatorScheduler.cls
global class NTVTaskCreatorScheduler implements Schedulable
{
	global void execute(SchedulableContext sc) 
	{
				
		// Get Min and Max Date To Send NTV  		
 		DateTime minNTVDateEmailFax = Util.getMinNTVDate('Email');
        DateTime minNTVDateMailInsured = Util.getMinNTVDate('Insured');
        DateTime maxNTVDateEmailFax = Util.getMaxNTVDate('Email');
        DateTime maxNTVDateMailInsured = Util.getMaxNTVDate('Insured');    

		// Get all Searches/Service Requests that need to have an NTV task created

		NTVTaskCreator ntvTC = new NTVTaskCreator();
		ntvTC.query = 'select Id,Name,Active_NTV_Task__c,Date_To_Send_NTV__c,NTV_Send_Via__c,NTV_Send_To__c,Service_Request__c,placement__c,Service_Request__r.Opportunity__r.Customer_Care_Specialist__c from searches__c where (Selected__c = true and RecordTypeId =  \'' + RecordTypeHelper.housingSearchRT() + '\' and Active_NTV_Task__c = false and Placement__r.Status__c = \'Moved-In\' and Date_To_Send_NTV__c >= ' + minNTVDateEmailFax.format('YYYY-MM-dd') + ' and Date_To_Send_NTV__c <= ' + maxNTVDateEmailFax.format('YYYY-MM-dd') + ' and NTV_Send_Via__c in (\'Email\', \'Fax\')) or (Selected__c = true and RecordTypeId = \'' + RecordTypeHelper.housingSearchRT() + '\' and Active_NTV_Task__c = false and Placement__r.Status__c = \'Moved-In\' and Date_To_Send_NTV__c >= ' + minNTVDateMailInsured.format('YYYY-MM-dd') + ' and Date_To_Send_NTV__c <= ' + maxNTVDateMailInsured.format('YYYY-MM-dd') + ' and NTV_Send_Via__c in (\'Certified Mail\', \'Insured\'))';
		database.executebatch(ntvTC); 
	}
}