src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Customer_Care_Specialist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Care Specialist</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities3</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Placement__c.object
<CustomObject>
    <description>Holds information about a housing placement, when the Opportunity stage is set to Moved-In, and a policy holder moves into the temporarry housing.  Besides the detail about the duration of the placement, this object is related to Cases to track any issues related to the placement.</description>
    <fields>
        <fullName>Date_To_Send_NTV__c</fullName>
        <label>Date To Send NTV</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Claim Lookup</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Placements</relationshipLabel>
        <relationshipName>Placements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Selected_Search__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Selected Search</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.ServiceRequest__c</field>
                <operation>equals</operation>
                <valueField>Searches__c.Service_Request__r.Id</valueField>
            </filterItems>
            <filterItems>
                <field>Searches__c.Selected__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Searches__c</referenceTo>
        <relationshipLabel>Placements</relationshipLabel>
        <relationshipName>Placements</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Placement</label>
    <nameField>
        <label>Placement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Placements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Searches__c.object
<CustomObject>
    <description>Used track the property and hotel searches conducted as part of the Sevice Request</description>
    <fields>
        <fullName>Active_NTV_Task__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active NTV Task</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Date_To_Send_NTV__c</fullName>
        <formula>Placement__r.Approved_Through_Date__c -  Days_Notice_Required__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Date To Send NTV</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>NTV_Send_To__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>This is the contact to send the Notice to Vacate to.  Defaults to the Landlord but can be overridden</description>
        <label>NTV Send To</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Landlord, Agent, Broker</value>
            </filterItems>
            <filterItems>
                <field>Contact.Status__c</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Searches (NTV Send To)</relationshipLabel>
        <relationshipName>Searches1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NTV_Send_Via__c</fullName>
        <label>NTV Send Via</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Fax</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Certified Mail</fullName>
                </value>
                <value>
                    <fullName>Insured</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Placement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Placement</label>
        <referenceTo>Placement__c</referenceTo>
        <relationshipName>Searches</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Request__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Service Request</label>
        <referenceTo>ServiceRequest__c</referenceTo>
        <relationshipName>Searches</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Search</label>
    <nameField>
        <displayFormat>SR-{000000}</displayFormat>
        <label>Search Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Searches</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/ServiceRequest__c.object
<CustomObject>
    <description>Holds the different services that a request can include, such as: Hotel Stays, Housing requests, Furniture requests, Fair Rental Value, etc.</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Claim</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Service Requests</relationshipLabel>
        <relationshipName>Service_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Selected_Search__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Selected Search</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Id</field>
                <operation>equals</operation>
                <valueField>Searches__c.Service_Request__c</valueField>
            </filterItems>
            <filterItems>
                <field>Searches__c.Selected__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Searches__c</referenceTo>
        <relationshipLabel>Service Requests (Selected Search)</relationshipLabel>
        <relationshipName>Service_Requests1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Service Request</label>
    <nameField>
        <displayFormat>SR#-{000000}</displayFormat>
        <label>Service Request</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/NTVTaskCreator.cls
global class NTVTaskCreator implements Database.Batchable<sObject> 
{
	Public String query { get; set;}  
			  
    global database.queryLocator start(Database.BatchableContext BC)
    {
  		system.debug(query);
  		return database.getQueryLocator(query);   		
    }
		
	global void execute(Database.BatchableContext BC, list <Searches__c> scope) 
   	{
   		Set<String> searchNames = new Set<String>();
   		List<Task> tasks = new List<Task>();
   		
		for(Searches__c search : scope) 
    	{
    		Task task = new Task();
			task.RecordTypeId = RecordTypeHelper.unsentNTVTaskRT();
    		task.Type = 'Send NTV';
    		task.Subject = 'Send NTV Via ' + search.NTV_Send_Via__c;
    		task.Status = 'Unsent';
    		task.WhoId = search.NTV_Send_To__c;
    		task.WhatId = search.Service_Request__c;
    		task.Placement__c = search.Placement__c;
   			task.ActivityDate = Util.getNTVTaskDueDate(search.Date_To_Send_NTV__c,search.NTV_Send_Via__c).date();
    		task.OwnerId = search.Service_Request__r.Opportunity__r.Customer_Care_Specialist__c;
    		task.Selected_Search__c = search.Id;
    		task.Service_Request__c = search.Service_Request__c;
 	    	tasks.add(task);
 
    		search.Active_NTV_Task__c = true;
    		searchNames.add(search.Name);
    	}

    	insert tasks;
    	update scope;

    	system.debug(searchNames);
	}
	
	global void finish(Database.BatchableContext BC) 
	{
		
	}
	
}