src/objects/Owner_Assignment_Map__c.object
<CustomObject>
    <fields>
        <fullName>Unassigned_State_Fallback_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Unassigned State Fallback Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Owner_Assignment_Maps</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Owner Assignment Map</label>
    <nameField>
        <label>Owner Assignment Map</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Owner Assignment Maps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Owner_Territory__c.object
<CustomObject>
    <fields>
        <fullName>Owner_Assignment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Owner Assignment</label>
        <referenceTo>Owner_Assignment_Map__c</referenceTo>
        <relationshipName>Owner_Maps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Territory_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Territory Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Owner_Maps</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Owner Territory</label>
    <nameField>
        <label>Owner Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Owner Territories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/UpdateOwnerTerritoryOwner.cls
/*************************************************************************************************************
Created by: Apostletech team
Purpose: When user is made inactive to update territory owner user values
Class calling from a class inactiveUsersAssignmentUpdate to update territory owner user values
*************************************************************************************************************/
public class UpdateOwnerTerritoryOwner{
  @future
  public static void updateOwnerTerritory(List<id> updateOwnerList) {
       List<Owner_Territory__c> territoryUpdateList = new List<Owner_Territory__c>(); 
       List<Owner_Territory__c> ownerterList = [select id, Owner_Assignment__r.Unassigned_State_Fallback_Owner__c from Owner_Territory__c where id =: updateOwnerList];
       for(Owner_Territory__c terId : ownerterList){
       System.debug('***Hello***');
           terId.Territory_Owner__c = terId.Owner_Assignment__r.Unassigned_State_Fallback_Owner__c;
           territoryUpdateList.add(terId);
       }
       if(!territoryUpdateList.isEmpty()) {
          Util.setAlreadyFired('Account');
          update territoryUpdateList;
       }
  }
}