src/objects/Owner_Assignment_Map__c.object
<CustomObject>
    <fields>
        <fullName>Unassigned_State_Fallback_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Unassigned State Fallback Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Owner_Assignment_Maps</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Owner Assignment Map</label>
    <nameField>
        <label>Owner Assignment Map</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Owner Assignment Maps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Owner_Territory__c.object
<CustomObject>
    <fields>
        <fullName>Owner_Assignment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Owner Assignment</label>
        <referenceTo>Owner_Assignment_Map__c</referenceTo>
        <relationshipName>Owner_Maps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Territory_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Territory Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Owner_Maps</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Owner Territory</label>
    <nameField>
        <label>Owner Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Owner Territories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/InactiveUsersAssignmentUpdate.cls
/*************************************************************************************************************
Created by: Apostletech team
Purpose: When user is made inactive to update the owner Territory object territory owner field user
Class calling from a Userinactive trigger to update the values
*************************************************************************************************************/
public class InactiveUsersAssignmentUpdate{
    
    public static void Userupdate(list<user> userslist, Map<Id,user> oldOwnerMap){
        Set<Id> Userid = new Set<Id>();
        for(user u: userslist ){
            if(u.IsActive == False && oldOwnerMap.get(u.id).IsActive <> false){
                Userid.add(u.id);
                System.debug('***User Id ****'+u.id);
            }
        }
        List<Owner_Territory__c> ownerTerritoryList = [select id, Territory_Owner__c, Owner_Assignment__c, Owner_Assignment__r.Unassigned_State_Fallback_Owner__c from Owner_Territory__c where Territory_Owner__c =:Userid ];
        List<id> updateOwnerList = new List<id>();
        if(ownerTerritoryList.size() > 0){
          for(user u: userslist){
            for(Owner_Territory__c ot : ownerTerritoryList){
                if(u.id == ot.Territory_Owner__c  && ot.Owner_Assignment__r.Unassigned_State_Fallback_Owner__c <> null){
                    updateOwnerList.add(ot.id);
                }
            }
          }
        }
        if(!updateOwnerList.isEmpty()){
            UpdateOwnerTerritoryOwner.updateOwnerTerritory(updateOwnerList);
            System.debug('***Hello***');
        }
    } 
}