src/objects/Owner_Territory__c.object
<CustomObject>
    <fields>
        <fullName>Owner_Assignment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Owner Assignment</label>
        <referenceTo>Owner_Assignment_Map__c</referenceTo>
        <relationshipName>Owner_Maps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>States__c</fullName>
        <label>States</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DC</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
                <value>
                    <fullName>MN</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
                <value>
                    <fullName>MS</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
                <value>
                    <fullName>NC</fullName>
                </value>
                <value>
                    <fullName>ND</fullName>
                </value>
                <value>
                    <fullName>NE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Owner Territory</label>
    <nameField>
        <label>Owner Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Owner Territories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DuplicateStateAlert.cls
/*************************************************************************************************************
Created by: Apostletech team
Purpose: When a new record is being created or update with duplicate need to alert with error message
Class calling from a ResetOwnerAssignment trigger to alert 
*************************************************************************************************************/

public class DuplicateStateAlert{

    public static void duplicateAlert(List<Owner_Territory__c> territoryRecords){
        
        List<String> statecodes = new List<String>();
        for(Owner_Territory__c ot : territoryRecords){
            if(ot.States__c <> null && ot.States__c <> ''){
                 
                 List<String> states = ot.States__c.split(';');
                 Set<String> stateTerritorycodes = new Set<String>();
                 stateTerritorycodes.addAll(states);
                 for(String S : stateTerritorycodes){
                     statecodes.add('\''+S+'\'');
                 } 
            }
        }
        
        String queryString = 'select id, States__c, Owner_Assignment__c from Owner_Territory__c where States__c includes(';
            for(String stateValue :statecodes){
                queryString += stateValue + ',';
            }    
            queryString = queryString.removeEnd(',') +')';
            List<Owner_Territory__c> aList = new List<Owner_Territory__c>();
            if(!statecodes.isEmpty()){
                aList = (List<Owner_Territory__c>)Database.query(queryString);
            }
            
            
            String errorMessage = '';
            for(Owner_Territory__c ot : territoryRecords){
                for(Owner_Territory__c o : aList){
                    
                    List<String> states = o.States__c.split(';');
                    Set<String> stateTerritorycodes = new Set<String>();
                    stateTerritorycodes.addAll(states);
                    System.debug('****oldState****'+stateTerritorycodes);
                    
                    List<String> newstates = ot.States__c.split(';');
                    Set<String> stateTercodes = new Set<String>();
                    stateTercodes.addAll(newstates);                    
                    
                    System.debug('****new State****'+stateTercodes);
                    for(String s : stateTercodes){
                        System.debug(stateTerritorycodes+'***Hello***'+s + '///////// '+stateTerritorycodes.contains(s));
                        if(ot.id <> o.id && ot.Owner_Assignment__c == o.Owner_Assignment__c && stateTerritorycodes.contains(s) ){
                             System.debug('****Hello****');
                              //errorMessage = errorMessage + +s+' \n ';
                              ot.addError('Duplicate State Assigned to another Owner Territory', false);
                        }
                    }
                }
               
            }
            
    }
}