src/objects/Owner_Assignment_Map__c.object
<CustomObject>
    <label>Owner Assignment Map</label>
    <nameField>
        <label>Owner Assignment Map</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Owner Assignment Maps</pluralLabel>
    <recordTypes>
        <fullName>RM</fullName>
        <active>true</active>
        <description>Relationship Manager map.</description>
        <label>RM</label>
    </recordTypes>
    <recordTypes>
        <fullName>TSM</fullName>
        <active>true</active>
        <description>Territory Sales Manager map. There can only be one.</description>
        <label>TSM</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TriggerControlSetting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Name hold the trigger Name which we need to control without activating or de-activating the trigger from Object UI.</description>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsAfter__c</fullName>
        <defaultValue>true</defaultValue>
        <label>IsAfter</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsBefore__c</fullName>
        <defaultValue>true</defaultValue>
        <label>IsBefore</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsInsert__c</fullName>
        <defaultValue>true</defaultValue>
        <label>IsInsert</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsUpdate__c</fullName>
        <defaultValue>true</defaultValue>
        <label>IsUpdate</label>
        <type>Checkbox</type>
    </fields>
    <label>Trigger Control Setting</label>
</CustomObject>

src/classes/ValidationSingleTSMandRMhelperClass_TC.cls
@isTest
public class ValidationSingleTSMandRMhelperClass_TC{
    public static testMethod void InsertRecords(){
        TriggerControlSetting__c tg = new TriggerControlSetting__c(name = 'ValidationSingleTSMandRM', IsActive__c = true, IsBefore__c = true, IsAfter__c = true, IsInsert__c = true, IsUpdate__c = true);
             insert tg; 
         RecordType rt3 = [SELECT id,Name 
                                 FROM RecordType 
                                 WHERE SobjectType='Owner_Assignment_Map__c' AND Name='RM'];
         RecordType rt4 = [SELECT id,Name 
                                 FROM RecordType 
                                 WHERE SobjectType='Owner_Assignment_Map__c' AND Name='Default RM'];
         RecordType rt5 = [SELECT id,Name 
                                 FROM RecordType 
                                 WHERE SobjectType='Owner_Assignment_Map__c' AND Name='TSM'];    
         Owner_Assignment_Map__c oa = new Owner_Assignment_Map__c();
         oa.Name = 'test';
         oa.recordtypeId = rt3.id;
         insert oa;
         
         Owner_Assignment_Map__c oa1 = new Owner_Assignment_Map__c();
         oa1.Name = 'test';
         oa1.recordtypeId = rt4.id;
         insert oa1;
         
         Owner_Assignment_Map__c oa2 = new Owner_Assignment_Map__c();
         oa2.Name = 'test';
         oa2.recordtypeId = rt5.id;
         insert oa2;
         
        
     }
}