src/objects/Placement__c.object
<CustomObject>
    <description>Holds information about a housing placement, when the Opportunity stage is set to Moved-In, and a policy holder moves into the temporarry housing.  Besides the detail about the duration of the placement, this object is related to Cases to track any issues related to the placement.</description>
    <fields>
        <fullName>Approved_Through_Date__c</fullName>
        <label>Approved Through Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Move_In_Date__c</fullName>
        <description>Houston populates this based on the quote start date.</description>
        <label>Move In Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Checked-In</fullName>
                </value>
                <value>
                    <fullName>Checked-Out</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Moved-In</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Moved-Out</fullName>
                </value>
                <value>
                    <fullName>Pending Confirmation</fullName>
                </value>
                <value>
                    <fullName>Quote</fullName>
                </value>
                <value>
                    <fullName>Searching</fullName>
                </value>
                <value>
                    <fullName>Pending Check-In</fullName>
                </value>
                <value>
                    <fullName>Lost Opportunity</fullName>
                </value>
                <value>
                    <fullName>Viewing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Placement</label>
    <nameField>
        <label>Placement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Placements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PlacementDispatcherExtensionTest.cls
@isTest
private class PlacementDispatcherExtensionTest {

   	@testSetup static void setupTestData()
   	{
   		Placement__c housingPlacement = new Placement__c(
                                            RecordTypeId = RecordTypeHelper.housingPlacementRT(),
                                            Name = 'testPlacementHousing',
                                            Status__c = 'Searching',
                                            Move_In_Date__c = Date.newInstance(2015,09,09),
	    							        Approved_Through_Date__c = Date.newInstance(2016,09,09));
        insert housingPlacement;	

        Placement__c hotelPlacement = new Placement__c(
                                          RecordTypeId = RecordTypeHelper.hotelPlacementRT(),
                                          Name = 'testPlacementHotel',
                                          Status__c = 'Searching',
                                          Move_In_Date__c = Date.newInstance(2015,09,09),
	    							      Approved_Through_Date__c = Date.newInstance(2016,09,09));
        insert hotelPlacement;	
   	}


   	static testMethod void testViewPlacement() 
	{
		Placement__c placement = new Placement__c();
   		ApexPages.StandardController stdCon = new ApexPages.StandardController(placement);
    	PlacementDispatcherExtension placementDispatcher = new PlacementDispatcherExtension(stdCon);
 		
    	Placement__c housingPlacement = [select id from Placement__c where name = 'testPlacementHousing'];

 		ApexPages.currentPage().getParameters().put('id', housingPlacement.Id);
 		PageReference pr = placementDispatcher.getViewPlacement();
 		
 		Placement__c hotelPlacement = [select id from Placement__c where name = 'testPlacementHotel'];

 		ApexPages.currentPage().getParameters().put('id', hotelPlacement.Id);
 		pr = placementDispatcher.getViewPlacement();
	}
	
	static testMethod void testEditPlacement()
	{
    	Placement__c placement = new Placement__c();
   		ApexPages.StandardController stdCon = new ApexPages.StandardController(placement);
    	PlacementDispatcherExtension placementDispatcher = new PlacementDispatcherExtension(stdCon);

    	Placement__c housingPlacement = [select id from Placement__c where name = 'testPlacementHousing'];
 		
 		ApexPages.currentPage().getParameters().put('id', housingPlacement.Id);
 		PageReference pr = placementDispatcher.getEditPlacement();

 		Placement__c hotelPlacement = [select id from Placement__c where name = 'testPlacementHotel'];
 		
 		ApexPages.currentPage().getParameters().put('id', hotelPlacement.Id);
 		pr = placementDispatcher.getEditPlacement();
 	}
}