src/objects/Placement__c.object
<CustomObject>
    <description>Holds information about a housing placement, when the Opportunity stage is set to Moved-In, and a policy holder moves into the temporarry housing.  Besides the detail about the duration of the placement, this object is related to Cases to track any issues related to the placement.</description>
    <fields>
        <fullName>Approved_Through_Date__c</fullName>
        <label>Approved Through Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Move_In_Date__c</fullName>
        <description>Houston populates this based on the quote start date.</description>
        <label>Move In Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Checked-In</fullName>
                </value>
                <value>
                    <fullName>Checked-Out</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Moved-In</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Moved-Out</fullName>
                </value>
                <value>
                    <fullName>Pending Confirmation</fullName>
                </value>
                <value>
                    <fullName>Quote</fullName>
                </value>
                <value>
                    <fullName>Searching</fullName>
                </value>
                <value>
                    <fullName>Pending Check-In</fullName>
                </value>
                <value>
                    <fullName>Lost Opportunity</fullName>
                </value>
                <value>
                    <fullName>Viewing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Placement</label>
    <nameField>
        <label>Placement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Placements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/RESTCreateExtensionTest.cls
@isTest
private class RESTCreateExtensionTest {

    static testMethod void myUnitTest() 
    {
      // Insert placement
               
      Placement__c placement = new Placement__c(
                                      RecordTypeId = recordTypeHelper.housingPlacementRT(),
                                      Name = 'testPlacementx',
                                      Status__c = 'Moved-Out',
                                      Move_In_Date__c = Date.today().addMonths(-5),
                                      Approved_Through_Date__c = Date.today());
                                        
      insert placement;
        
        
      User user = [select id from User where isActive = true and name = 'Mark Bodde' limit 1];
                
      RestRequest req = new RestRequest();
      if (UserInfo.getOrganizationId() == '00D70000000JTmAEAW') 
      {
          // production endpoint
          req.requestURI = 'https://login.salesforce.com/services/apexrest/Placement/CreateExtension';
      }
      else
      {
          // test endpoint
          req.requestURI = 'https://test.salesforce.com/services/apexrest/Placement/CreateExtension';
      }
      req.httpMethod = 'POST';
        
      Date newApprovedThroughDate = placement.Approved_Through_Date__c.addDays(7);
                
        String placementId = placement.Id;
      String userId = '123';
      String approvedThroughDate = String.valueOf(newApprovedThroughDate);
      Boolean createNTVTask = true;     
            
        RESTCreateExtension.insertExtension(placementId,userId,approvedThroughDate,createNTVTask);

      newApprovedThroughDate = placement.Approved_Through_Date__c.addDays(-10);
        
      approvedThroughDate = String.valueOf(newApprovedThroughDate);
        
      RESTCreateExtension.insertExtension(placementId,userId,approvedThroughDate,createNTVTask);

        //setup request with bad data to cover exceptions
        
        RestContext.request = req;
          
      placementId = '123';
      userId = user.Id;
                    
        RESTCreateExtension.insertExtension(placementId,userId,approvedThroughDate,createNTVTask);
        
    }
}