src/objects/Placement__c.object
<CustomObject>
    <description>Holds information about a housing placement, when the Opportunity stage is set to Moved-In, and a policy holder moves into the temporarry housing.  Besides the detail about the duration of the placement, this object is related to Cases to track any issues related to the placement.</description>
    <fields>
        <fullName>Approved_Through_Date__c</fullName>
        <label>Approved Through Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Move_In_Date__c</fullName>
        <description>Houston populates this based on the quote start date.</description>
        <label>Move In Date</label>
        <type>Date</type>
    </fields>
    <label>Placement</label>
    <nameField>
        <label>Placement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Placements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Quote__c.object
<CustomObject>
    <description>Used to build quotes for Service Requests including: Residential, Un-furnished, Furniture-Only, Hotel, Trailer-Mobile Home, and Commercial.</description>
    <fields>
        <fullName>Approved_Through_Date__c</fullName>
        <label>Approved Through Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Move_In_Date__c</fullName>
        <label>Move In Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Placement_Lookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Placement Lookup</label>
        <referenceTo>Placement__c</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{000000}</displayFormat>
        <label>Quote</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/RESTQuoteDocumentTest.cls
@isTest
public with sharing class RESTQuoteDocumentTest 
{
    static testMethod void myUnitTest() 
    {
   	    
        Placement__c placement = new Placement__c(
                                        RecordTypeId = recordTypeHelper.housingPlacementRT(),
                                        Name = 'testPlacementHousing',
                                        Move_In_Date__c = Date.newInstance(2015,09,09),
	    								Approved_Through_Date__c = Date.newInstance(2016,09,09));
                                        
        insert placement;
        
               
        Quote__c quote = new Quote__c(
                                        RecordTypeId = recordTypeHelper.mulliganQuoteRT(),
                                        Placement_Lookup__c = placement.Id);
                                        
        insert quote;
        
              	      	      	
      	RestRequest req = new RestRequest();
        
        if (UserInfo.getOrganizationId() == '00D70000000JTmAEAW') 
        {
            // production endpoint
            req.requestURI = 'https://login.salesforce.com/services/apexrest//Placement/THCDocument/';
        }
        else
        {
            // test endpoint
            req.requestURI = 'https://test.salesforce.com/services/apexrest//Placement/THCDocument/';
        }
        req.httpMethod = 'POST';
               
        string expectedresult = 'Quote document recieved';
                
        RestContext.request = req;
        
        Blob body;
    		body = Blob.valueOf('This is a test THC doc');
    		req.requestBody = body;
    				
    		req.addParameter('placementId', placement.Id);
    		req.addParameter('quoteName',quote.Name);
    		req.addParameter('quoteId', quote.Id);
    			
    		String results = RESTQuoteDocument.insertQuoteDocument(req);
    		System.assertEquals(expectedresult,results);
       		
       		req.addParameter('placementId', placement.Id);
    		req.addParameter('quoteName',quote.Name);
    		req.addParameter('quoteId', '');
       		
      	results = RESTQuoteDocument.insertQuoteDocument(req);
    }
}