src/objects/Placement__c.object
<CustomObject>
    <description>Holds information about a housing placement, when the Opportunity stage is set to Moved-In, and a policy holder moves into the temporarry housing.  Besides the detail about the duration of the placement, this object is related to Cases to track any issues related to the placement.</description>
    <fields>
        <fullName>ServiceRequest__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Request</label>
        <referenceTo>ServiceRequest__c</referenceTo>
        <relationshipLabel>Placements</relationshipLabel>
        <relationshipName>Placements1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Placement</label>
    <nameField>
        <label>Placement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Placements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ServiceRequest__c.object
<CustomObject>
    <description>Holds the different services that a request can include, such as: Hotel Stays, Housing requests, Furniture requests, Fair Rental Value, etc.</description>
    <fields>
        <fullName>ServiceRequest__c</fullName>
        <formula>Id</formula>
        <label>ServiceRequest</label>
        <type>Text</type>
    </fields>
    <label>Service Request</label>
    <nameField>
        <displayFormat>SR#-{000000}</displayFormat>
        <label>Service Request</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PlacementDispatcherExtension.cls
public with sharing class PlacementDispatcherExtension 
{
	public PlacementDispatcherExtension(ApexPages.StandardController stdController)
    {
    	Placement__c placement = (Placement__c)stdController.getRecord();
    }
  
    public PageReference getViewPlacement()
    {
    	Id id = ApexPages.currentPage().getParameters().get('id'); 
    	Placement__c placement = [select Id, RecordTypeId, ServiceRequest__c from Placement__c where Id = :id];
    	PageReference newPage;
        
	    if (placement.RecordTypeId == RecordTypeHelper.hotelPlacementRT())
	    {
	    	newPage = Page.HotelEntry;
	    }
	    else
	    {
	  		newPage = Page.HousingEntry;
	    }
	    
	    newPage.getParameters().put('id', placement.ServiceRequest__c);
	    return newPage.setRedirect(true);
	}
	
	public PageReference getEditPlacement()
    {
	  	Id id = ApexPages.currentPage().getParameters().get('id'); 
	    Placement__c placement = [select Id, RecordTypeId, ServiceRequest__c from Placement__c where Id = :id];
    	PageReference newPage;
	    
	    if (placement.RecordTypeId == RecordTypeHelper.hotelPlacementRT())
	    {
	    	newPage = Page.HotelEntry;
	    }
	    else
	    {
	 		newPage = Page.HousingEntry;	
	    }
	    
	    newPage.getParameters().put('id', placement.ServiceRequest__c);
	    return newPage.setRedirect(true);
    }
}