src/objects/Placement__c.object
<CustomObject>
    <description>Holds information about a housing placement, when the Opportunity stage is set to Moved-In, and a policy holder moves into the temporarry housing.  Besides the detail about the duration of the placement, this object is related to Cases to track any issues related to the placement.</description>
    <fields>
        <fullName>Approved_Through_Date__c</fullName>
        <label>Approved Through Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Move_In_Date__c</fullName>
        <description>Houston populates this based on the quote start date.</description>
        <label>Move In Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Checked-In</fullName>
                </value>
                <value>
                    <fullName>Checked-Out</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Moved-In</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Moved-Out</fullName>
                </value>
                <value>
                    <fullName>Pending Confirmation</fullName>
                </value>
                <value>
                    <fullName>Quote</fullName>
                </value>
                <value>
                    <fullName>Searching</fullName>
                </value>
                <value>
                    <fullName>Pending Check-In</fullName>
                </value>
                <value>
                    <fullName>Lost Opportunity</fullName>
                </value>
                <value>
                    <fullName>Viewing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Placement</label>
    <nameField>
        <label>Placement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Placements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/HousingPlacementsToMovedOutTest.cls
@isTest
private class HousingPlacementsToMovedOutTest {

	static testMethod void myUnitTest() 
    {
        	Placement__c housingPlacement = new Placement__c
    	(
        	RecordTypeId = RecordTypeHelper.housingPlacementRT(), 
	        Name = 'testPlacementHousing',
	        Status__c = 'Moved-In',
	        Move_In_Date__c = Date.newInstance(2013,09,09),
		    Approved_Through_Date__c = Date.newInstance(2014,01,01));
		   
		insert housingPlacement;
    	    	
    	HousingPlacementsToMovedOut HPsToMovedOut = new HousingPlacementsToMovedOut();
    	
    	housingPlacement = [select Status__c from Placement__c where id =: housingPlacement.Id];
    	
    	System.assertEquals('Moved-Out', housingPlacement.Status__c); 
        
        // Test scheduler
        
        SchedulableContext sc;
        HousingPlacementsToMovedOutScheduler MoveOutScheduler = new HousingPlacementsToMovedOutScheduler();	   
        MoveOutScheduler.execute(sc);
   }
}