src/objects/Quote__c.object
<CustomObject>
    <description>Used to build quotes for Service Requests including: Residential, Un-furnished, Furniture-Only, Hotel, Trailer-Mobile Home, and Commercial.</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Submitted</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{000000}</displayFormat>
        <label>Quote</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/RESTQuoteError.cls
@RestResource(urlMapping='/Quote/QuoteError/*')
global with sharing class RESTQuoteError 
{
	@HttpPost
	global static void insertQuoteError(RestRequest req)   
	{ 
		string quoteId = req.params.get('quoteId');
		string quoteError = req.params.get('quoteError');
				
	   	try
	    {
	    	Quote__c quote = [select Name,Status__c from Quote__c where Id =: quoteId];
	    	quote.Status__c = quoteError;
	   		update quote;
	    }
	    catch (QueryException e)
        {
        	 Util.sendErrorEmail('Billing system error processing quote','ERROR: ' + e + ' returned processing quote Id ' + quoteId);		
        }
	}	
}