src/objects/ServiceRequest__c.object
<CustomObject>
    <description>Holds the different services that a request can include, such as: Hotel Stays, Housing requests, Furniture requests, Fair Rental Value, etc.</description>
    <fields>
        <fullName>ServiceRequest__c</fullName>
        <formula>Id</formula>
        <label>ServiceRequest</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Request</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Searching</fullName>
                </value>
                <value>
                    <fullName>Pending Confirmation</fullName>
                </value>
                <value>
                    <fullName>Moved-In/Closed</fullName>
                </value>
                <value>
                    <fullName>Finders Fee</fullName>
                </value>
                <value>
                    <fullName>Hold</fullName>
                </value>
                <value>
                    <fullName>Checked-In/Closed</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Lost Opportunity</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Service Request</label>
    <nameField>
        <displayFormat>SR#-{000000}</displayFormat>
        <label>Service Request</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/RESTDocumentTest.cls
@isTest
private class RESTDocumentTest 
{
    static testMethod void myUnitTest() 
    {
      	
    	// Insert ServiceRequest 
        ServiceRequest__c serviceRequest = new ServiceRequest__c
        		(
                	RecordTypeId = RecordTypeHelper.hotelServiceRequestRT(),
				    Status__c = 'Request');
		insert serviceRequest;

      	// Insert User
        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User']; 
        User user = new User
                (   Alias = 'standt',
                    Email='standarduser@testorg.com', 
                    EmailEncodingKey='UTF-8', 
                    LastName='Testing', 
                    LanguageLocaleKey='en_US',
                    LocaleSidKey='en_US', 
                    ProfileId = p.Id, 
                    TimeZoneSidKey='America/Los_Angeles', 
                    UserName='standarduser@crstemphousing.com');
        insert user;        

       	string documentName = 'Test Document';
      	      	
      	RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
      
        req.requestURI = util.getInstanceBaseURL() + '/services/apexrest/Documents';
       
        req.httpMethod = 'POST';
        
        string expectedresult = documentName + ' saved';
                
        RestContext.request = req;
		RestContext.response = res;
		
		req.addParameter('Id', serviceRequest.Id);
		req.addParameter('userId', user.Id);
		req.addParameter('name', documentName);
	
		Blob body;
		body = Blob.valueOf('This is a test doc');
		req.requestBody = body;
		
		String results = RESTDocument.insertDocument();
		System.assertEquals(expectedresult,results);
    }
}