src/objects/StatementParams__c.object
<CustomObject>
    <description>Custom object used for Statement parameters</description>
    <fields>
        <fullName>Placement_Id__c</fullName>
        <label>Placement Id</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>StatementParams</label>
    <nameField>
        <label>Custom Object Label Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>StatementParams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestStatementController.cls
@isTest
public class TestStatementController 
{
    @isTest
    static void StatementControllerTest() 
	{
	  Test.setMock(HttpCalloutMock.class, new StatementHttpCalloutMock());  
	    
	  StatementParams__c sp = new StatementParams__c();
	  
         ApexPages.currentPage().getParameters().clear();
    ApexPages.currentPage().getParameters().put('claim', '1234'); 
      
        
	ApexPages.standardController controller = new ApexPages.standardController(sp);
    StatementController sc = new StatementController(controller);
 
    sc.checkParams();
    sp.Placement_Id__c = '12232';
    sc.checkParams();
    
 
    sc.runStatement();
    
    
	}
}